StateManager< T > Struct Template Reference
#include <statemanager.h>
Public Member Functions
T read () const
T previous () const
T go_back ()
void clear_history ()
bool is (T s) const
bool is_not (T s) const
const std::string_view tostring () const
void set (T ns)
virtual T default_value () const =0
void reset ()
virtual ~StateManager ()
Private Attributes
std::stack< T > prev
T state
Constructor & Destructor Documentation
 StateManager()
template<typename T >
virtual StateManager< T >::~StateManager () [inline], [virtual]
Member Function Documentation
clear_history()
template<typename T >
void StateManager< T >::clear_history () [inline]
References StateManager< T >::prev.
Referenced by StateManager< T >::reset().
default_value()
template<typename T >
virtual T StateManager< T >::default_value () const [pure virtual]
Implemented in MenuState, and GameState.
Referenced by StateManager< T >::reset().
go_back()
template<typename T >
T StateManager< T >::go_back () [inline]
References StateManager< T >::prev, and StateManager< T >::state.
is()
template<typename T >
bool StateManager< T >::is (T s) const [inline]
References StateManager< T >::state.
is_not()
template<typename T >
bool StateManager< T >::is_not (T s) const [inline]
References StateManager< T >::state.
previous()
template<typename T >
T StateManager< T >::previous () const [inline]
References StateManager< T >::prev.
read()
template<typename T >
T StateManager< T >::read () const [inline]
References StateManager< T >::state.
reset()
template<typename T >
void StateManager< T >::reset () [inline]
References StateManager< T >::clear_history(), StateManager< T >::default_value(), and StateManager< T >::set().
set()
template<typename T >
void StateManager< T >::set (T ns) [inline]
References StateManager< T >::prev, and StateManager< T >::state.
Referenced by StateManager< T >::reset().
tostring()
template<typename T >
const std::string_view StateManager< T >::tostring () const [inline]
References StateManager< T >::state.
Member Data Documentation
prev
template<typename T >
std::stack<T> StateManager< T >::prev [private]
Referenced by StateManager< T >::clear_history(), StateManager< T >::go_back(), StateManager< T >::previous(), and StateManager< T >::set().
state
template<typename T >
T StateManager< T >::state [private]
Referenced by StateManager< T >::go_back(), StateManager< T >::is(), StateManager< T >::is_not(), StateManager< T >::read(), StateManager< T >::set(), and StateManager< T >::tostring().
The documentation for this struct was generated from the following file:
src/statemanager.h