ui::IUIContextInputManager Struct Reference
#include <ui_context.h>
Public Member Functions
virtual ~IUIContextInputManager ()
virtual void init ()
virtual void begin (float dt)
virtual void cleanup ()
bool is_mouse_inside (const Rectangle &rect) const
bool process_char_press_event (CharPressedEvent event)
bool process_keyevent (KeyPressedEvent event)
bool process_gamepad_button_event (GamepadButtonPressedEvent event)
bool process_gamepad_axis_event (GamepadAxisMovedEvent event)
bool _pressedButtonWithoutEat (GamepadButton butt) const
bool pressedButtonWithoutEat (const InputName &name) const
void eatButton ()
bool pressed (const InputName &name)
void handleBadGamepadAxis (const KeyMapInputRequestError &, menu::State, const InputName)
void eatAxis ()
bool _pressedWithoutEat (int code) const
bool pressedWithoutEat (const InputName &name) const
void eatKey ()
bool is_held_down_debounced (const InputName &name)
bool is_held_down (const InputName &name)
Public Attributes
MouseInfo mouse_info
int key = -1
int mod = -1
GamepadButton button
GamepadAxisWithDir axis_info
int keychar = -1
int modchar = -1
float yscrolled
float keyHeldDownTimer = 0.f
float prevKeyHeldDownTimer = 0.f
float keyHeldDownTimerReset = 0.15f
float lastDt
Constructor & Destructor Documentation
 IUIContextInputManager()
virtual ui::IUIContextInputManager::~IUIContextInputManager () [inline], [virtual]
Member Function Documentation
_pressedButtonWithoutEat()
bool ui::IUIContextInputManager::_pressedButtonWithoutEat (GamepadButton butt) const [inline]
References button.
Referenced by pressed().
_pressedWithoutEat()
bool ui::IUIContextInputManager::_pressedWithoutEat (int code) const [inline]
References key, and mod.
Referenced by pressed(), pressedButtonWithoutEat(), and pressedWithoutEat().
begin()
virtual void ui::IUIContextInputManager::begin (float dt) [inline], [virtual]
Reimplemented in ui::UIContext.
References get_mouse_info(), ext::get_mouse_wheel_move(), lastDt, mouse_info, and yscrolled.
Referenced by ui::UIContext::begin().
cleanup()
virtual void ui::IUIContextInputManager::cleanup () [inline], [virtual]
Reimplemented in ui::UIContext.
References key, keychar, keyHeldDownTimer, mod, modchar, and prevKeyHeldDownTimer.
Referenced by ui::UIContext::cleanup().
eatAxis()
void ui::IUIContextInputManager::eatAxis () [inline]
References axis_info.
Referenced by pressed().
eatButton()
void ui::IUIContextInputManager::eatButton () [inline]
References button.
Referenced by pressed().
eatKey()
void ui::IUIContextInputManager::eatKey () [inline]
References key.
Referenced by pressed().
handleBadGamepadAxis()
void ui::IUIContextInputManager::handleBadGamepadAxis (const KeyMapInputRequestError & , menu::State , const InputName) [inline]
Referenced by pressed().
init()
virtual void ui::IUIContextInputManager::init () [inline], [virtual]
Reimplemented in ui::UIContext.
References mouse_info, and yscrolled.
Referenced by ui::UIContext::init().
is_held_down()
bool ui::IUIContextInputManager::is_held_down (const InputName & name) [inline]
References KeyMap::is_event(), and ui::STATE.
Referenced by is_held_down_debounced(), and ui::slider().
is_held_down_debounced()
bool ui::IUIContextInputManager::is_held_down_debounced (const InputName & name) [inline]
References is_held_down(), keyHeldDownTimer, keyHeldDownTimerReset, and lastDt.
is_mouse_inside()
bool ui::IUIContextInputManager::is_mouse_inside (const Rectangle & rect) const [inline]
References mouse_info, and MouseInfo::pos.
Referenced by ui::active_if_mouse_inside().
pressed()
bool ui::IUIContextInputManager::pressed (const InputName & name) [inline]
References _pressedButtonWithoutEat(), _pressedWithoutEat(), GamepadAxisWithDir::axis, axis_info, GamepadAxisWithDir::dir, eatAxis(), eatButton(), eatKey(), EPSILON, KeyMap::get_axis(), KeyMap::get_button(), KeyMap::get_key_code(), handleBadGamepadAxis(), and ui::STATE.
Referenced by ui::button().
pressedButtonWithoutEat()
bool ui::IUIContextInputManager::pressedButtonWithoutEat (const InputName & name) const [inline]
References _pressedWithoutEat(), KeyMap::get_button(), and ui::STATE.
pressedWithoutEat()
bool ui::IUIContextInputManager::pressedWithoutEat (const InputName & name) const [inline]
References _pressedWithoutEat(), KeyMap::get_key_code(), and ui::STATE.
process_char_press_event()
bool ui::IUIContextInputManager::process_char_press_event (CharPressedEvent event) [inline]
References keychar.
process_gamepad_axis_event()
bool ui::IUIContextInputManager::process_gamepad_axis_event (GamepadAxisMovedEvent event) [inline]
References GamepadAxisWithDir::axis, axis_info, KeyMap::does_layer_map_contain_axis(), and ui::STATE.
process_gamepad_button_event()
bool ui::IUIContextInputManager::process_gamepad_button_event (GamepadButtonPressedEvent event) [inline]
References button, KeyMap::does_layer_map_contain_button(), and ui::STATE.
process_keyevent()
bool ui::IUIContextInputManager::process_keyevent (KeyPressedEvent event) [inline]
References KeyMap::does_layer_map_contain_key(), KeyMap::get_key_code(), key, mod, modchar, and ui::STATE.
Member Data Documentation
axis_info
GamepadAxisWithDir ui::IUIContextInputManager::axis_info
Referenced by eatAxis(), pressed(), and process_gamepad_axis_event().
button
GamepadButton ui::IUIContextInputManager::button
Referenced by _pressedButtonWithoutEat(), eatButton(), and process_gamepad_button_event().
key
int ui::IUIContextInputManager::key = -1
Referenced by _pressedWithoutEat(), cleanup(), eatKey(), and process_keyevent().
keychar
int ui::IUIContextInputManager::keychar = -1
Referenced by cleanup(), and process_char_press_event().
keyHeldDownTimer
float ui::IUIContextInputManager::keyHeldDownTimer = 0.f
Referenced by cleanup(), and is_held_down_debounced().
keyHeldDownTimerReset
float ui::IUIContextInputManager::keyHeldDownTimerReset = 0.15f
Referenced by is_held_down_debounced().
lastDt
float ui::IUIContextInputManager::lastDt
Referenced by begin(), and is_held_down_debounced().
mod
int ui::IUIContextInputManager::mod = -1
Referenced by _pressedWithoutEat(), cleanup(), and process_keyevent().
modchar
int ui::IUIContextInputManager::modchar = -1
Referenced by cleanup(), and process_keyevent().
mouse_info
MouseInfo ui::IUIContextInputManager::mouse_info
Referenced by begin(), ui::button(), ui::UIContext::cleanup(), init(), is_mouse_inside(), and ui::slider().
prevKeyHeldDownTimer
float ui::IUIContextInputManager::prevKeyHeldDownTimer = 0.f
Referenced by cleanup().
yscrolled
float ui::IUIContextInputManager::yscrolled
Referenced by begin(), init(), and ui::scroll_view().
The documentation for this struct was generated from the following file:
src/engine/ui_context.h