ui::IUIContextParentStacking Struct Reference
#include <ui_context.h>
Public Member Functions
void push_parent (Widget *widget)
void pop_parent ()
Widget * active_parent ()
void push_parent (std::shared_ptr< Widget > widget)
void add_child (Widget *child)
Public Attributes
std::stack< Widget * > parentstack
Member Function Documentation
active_parent()
Widget * ui::IUIContextParentStacking::active_parent () [inline]
References parentstack.
Referenced by add_child().
add_child()
void ui::IUIContextParentStacking::add_child (Widget * child) [inline]
References active_parent(), and ui::Widget::add_child().
Referenced by ui::init_widget().
pop_parent()
void ui::IUIContextParentStacking::pop_parent () [inline]
References parentstack.
Referenced by ui::button_list(), and ui::dropdown().
push_parent() [1/2]
void ui::IUIContextParentStacking::push_parent (std::shared_ptr< Widget > widget) [inline]
References push_parent().
push_parent() [2/2]
void ui::IUIContextParentStacking::push_parent (Widget * widget) [inline]
References parentstack.
Referenced by ui::button_list(), ui::dropdown(), and push_parent().
Member Data Documentation
parentstack
std::stack<Widget*> ui::IUIContextParentStacking::parentstack
Referenced by active_parent(), pop_parent(), and push_parent().
The documentation for this struct was generated from the following file:
src/engine/ui_context.h