ui::IUIContextLastFrame Struct Reference
#include <ui_context.h>
Classes
struct LastFrame
Public Member Functions
LastFrame get_last_frame (uuid id) const
void write_last_frame (const uuid &id, LastFrame f)
void reset_last_frame ()
Public Attributes
std::map< uuid, LastFrame > last_frame
Member Function Documentation
get_last_frame()
LastFrame ui::IUIContextLastFrame::get_last_frame (uuid id) const [inline]
References last_frame.
Referenced by ui::init_widget().
reset_last_frame()
void ui::IUIContextLastFrame::reset_last_frame () [inline]
References last_frame.
Referenced by ui::UIContext::cleanup().
write_last_frame()
void ui::IUIContextLastFrame::write_last_frame (const uuid & id, LastFrame f) [inline]
References last_frame, and ui::IUIContextLastFrame::LastFrame::was_written_this_frame.
Referenced by ui::init_widget().
Member Data Documentation
last_frame
std::map<uuid, LastFrame> ui::IUIContextLastFrame::last_frame
Referenced by get_last_frame(), reset_last_frame(), and write_last_frame().
The documentation for this struct was generated from the following file:
src/engine/ui_context.h