Entity Struct Reference
#include <entity.h>
Public Types
enum FrontFaceDirection { FORWARD = 0x1
, RIGHT = 0x2
, BACK = 0x4
, LEFT = 0x8
 }
Public Member Functions
FrontFaceDirection offsetFaceDirection (FrontFaceDirection startingDirection, float offset) const
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
void update_name (const std::string &new_name)
virtual bool can_take_item_from () const
virtual bool collides (BoundingBox b) const
virtual BoundingBox bounds () const
virtual void update_position (const vec3 &p)
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void render () const final
virtual void update (float dt) final
Static Public Member Functions
static vec2 tile_infront_given_pos (vec2 tile, int distance, FrontFaceDirection direction)
Public Attributes
const std::map< FrontFaceDirection, float > FrontFaceDirectionMap
const std::map< int, FrontFaceDirection > DirectionToFrontFaceMap
int id
vec3 raw_position
vec3 prev_position
vec3 position
vec3 pushed_force {0.0, 0.0, 0.0}
Color face_color
Color base_color
bool cleanup = false
bool is_highlighted = false
bool is_held = false
FrontFaceDirection face_direction = FrontFaceDirection::FORWARD
std::shared_ptr< Item > held_item = nullptr
int name_length = 1
std::string name = ``
Protected Member Functions
Entity ()
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual void render_debug_mode () const
virtual void render_highlighted () const
virtual void render_normal () const
virtual void render_floating_name () const
virtual std::optional< ModelInfo > model () const
vec3 snap_position () const
virtual void update_held_item_position ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void always_update (float)
virtual void planning_update (float)
virtual void in_round_update (float)
virtual bool is_snappable ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Private Member Functions
template<typename S >
void serialize (S &s)
Member Enumeration Documentation
FrontFaceDirection
enum Entity::FrontFaceDirection
Enumerator
FORWARD
RIGHT
BACK
LEFT
Constructor & Destructor Documentation
Entity() [1/5]
Entity::Entity (vec3 p, Color face_color_in, Color base_color_in) [inline]
References snap_position().
Entity() [2/5]
Entity::Entity (vec2 p, Color face_color_in, Color base_color_in) [inline]
Entity() [3/5]
Entity::Entity (vec3 p, Color c) [inline]
References snap_position().
Entity() [4/5]
Entity::Entity (vec2 p, Color c) [inline]
 Entity()
virtual Entity::~Entity () [inline], [virtual]
Entity() [5/5]
Entity::Entity () [inline], [protected]
Member Function Documentation
add_to_navmesh()
virtual bool Entity::add_to_navmesh () [inline], [virtual]
Reimplemented in Furniture.
always_update()
virtual void Entity::always_update (float) [inline], [protected], [virtual]
Reimplemented in Person, and Player.
References is_highlighted, is_snappable(), raw_position, snap_position(), and update_held_item_position().
Referenced by Person::always_update(), Player::always_update(), and update().
bounds()
virtual BoundingBox Entity::bounds () const [inline], [virtual]
References get_bounds(), and size().
Referenced by collides(), and render_debug_mode().
can_place_item_into()
virtual bool Entity::can_place_item_into (std::shared_ptr< Item > = nullptr) [inline], [protected], [virtual]
Reimplemented in Furniture.
can_take_item_from()
virtual bool Entity::can_take_item_from () const [inline], [virtual]
collides()
virtual bool Entity::collides (BoundingBox b) const [inline], [virtual]
References bounds().
get_heading()
virtual vec2 Entity::get_heading () [inline], [protected], [virtual]
References util::deg2rad(), and FrontFaceDirectionMap.
Referenced by turn_to_face_entity().
in_round_update()
virtual void Entity::in_round_update (float) [inline], [protected], [virtual]
Reimplemented in AIPerson, and Customer.
Referenced by AIPerson::in_round_update(), and update().
is_collidable()
virtual bool Entity::is_collidable () [inline], [virtual]
Reimplemented in Player, RemotePlayer, CustomerSpawner, and TargetCube.
References is_held.
Referenced by Person::handle_collision().
is_snappable()
virtual bool Entity::is_snappable () [inline], [protected], [virtual]
Reimplemented in AIPerson.
Referenced by always_update().
model()
virtual std::optional< ModelInfo > Entity::model () const [inline], [protected], [virtual]
Reimplemented in Person.
Referenced by render_highlighted(), and render_normal().
offsetFaceDirection()
FrontFaceDirection Entity::offsetFaceDirection (FrontFaceDirection startingDirection, float offset) const [inline]
References DirectionToFrontFaceMap, and FrontFaceDirectionMap.
Referenced by rotate_facing_clockwise().
on_drop()
virtual void Entity::on_drop (vec3 location) [inline], [virtual]
References vec::snap(), and update_position().
on_pickup()
virtual void Entity::on_pickup () [inline], [virtual]
planning_update()
virtual void Entity::planning_update (float) [inline], [protected], [virtual]
Reimplemented in BasePlayer.
Referenced by BasePlayer::planning_update(), and update().
raw_bounds()
virtual BoundingBox Entity::raw_bounds () const [inline], [protected], [virtual]
References get_bounds(), and size().
render()
virtual void Entity::render () const [inline], [final], [virtual]
References render_debug_mode(), and render_normal().
render_debug_mode()
virtual void Entity::render_debug_mode () const [inline], [protected], [virtual]
Reimplemented in AIPerson, and Player.
References bounds().
Referenced by render(), and AIPerson::render_debug_mode().
render_floating_name()
virtual void Entity::render_floating_name () const [inline], [protected], [virtual]
References raylib::DrawFloatingText(), name, and TILESIZE.
Referenced by render_normal().
render_highlighted()
virtual void Entity::render_highlighted () const [inline], [protected], [virtual]
References face_direction, FrontFaceDirectionMap, model(), and size().
Referenced by render_normal().
render_normal()
virtual void Entity::render_normal () const [inline], [protected], [virtual]
Reimplemented in Customer, Furniture, and Player.
References face_direction, FrontFaceDirectionMap, model(), render_floating_name(), render_highlighted(), and size().
Referenced by render(), Player::render_debug_mode(), Customer::render_normal(), Furniture::render_normal(), and Player::render_normal().
rotate_facing_clockwise()
void Entity::rotate_facing_clockwise () [inline]
References offsetFaceDirection().
serialize()
template<typename S >
void Entity::serialize (S & s) [inline], [private]
References base_color, cleanup, face_color, face_direction, held_item, is_held, is_highlighted, name, name_length, position, prev_position, pushed_force, and raw_position.
size()
virtual vec3 Entity::size () const [inline], [protected], [virtual]
Reimplemented in Person.
References TILESIZE.
Referenced by bounds(), raw_bounds(), render_highlighted(), and render_normal().
snap_position()
vec3 Entity::snap_position () const [inline], [protected]
References vec::snap().
Referenced by always_update(), Entity(), and tile_infront().
tile_infront()
virtual vec2 Entity::tile_infront (int distance) [inline], [virtual]
References snap_position(), tile_infront_given_pos(), and vec::to2().
Referenced by Player::handle_in_planning_grab_or_drop().
tile_infront_given_pos()
static vec2 Entity::tile_infront_given_pos (vec2 tile, int distance, FrontFaceDirection direction) [inline], [static]
References BACK, FORWARD, LEFT, RIGHT, and TILESIZE.
Referenced by EntityHelper::getMatchingEntityInFront(), and tile_infront().
turn_to_face_entity()
virtual void Entity::turn_to_face_entity (Entity * target) [inline], [protected], [virtual]
References vec::dot2(), get_heading(), vec::norm(), and util::rad2deg().
update()
virtual void Entity::update (float dt) [inline], [final], [virtual]
References always_update(), in_round_update(), game::InRound, and planning_update().
update_held_item_position()
virtual void Entity::update_held_item_position () [inline], [protected], [virtual]
Reimplemented in Furniture.
References BACK, FORWARD, held_item, LEFT, position, RIGHT, and TILESIZE.
Referenced by always_update().
update_name()
void Entity::update_name (const std::string & new_name) [inline]
References name, and name_length.
Referenced by Customer::init().
update_position()
virtual void Entity::update_position (const vec3 & p) [inline], [virtual]
Referenced by on_drop().
Member Data Documentation
base_color
Color Entity::base_color
Referenced by serialize().
cleanup
bool Entity::cleanup = false
Referenced by serialize().
DirectionToFrontFaceMap
const std::map<int, FrontFaceDirection> Entity::DirectionToFrontFaceMap
Initial value:
{
        {0, FORWARD}, {45, FORWARD | RIGHT}, {90, RIGHT},
        {135, BACK | RIGHT}, {180, BACK}, {225, BACK | LEFT},
        {270, LEFT}, {315, FORWARD | LEFT}}
Referenced by offsetFaceDirection().
face_color
Color Entity::face_color
Referenced by serialize().
face_direction
FrontFaceDirection Entity::face_direction = FrontFaceDirection::FORWARD
Referenced by Player::handle_in_game_grab_or_drop(), Player::handle_in_planning_grab_or_drop(), BasePlayer::highlight_facing_furniture(), BasePlayer::planning_update(), render_highlighted(), render_normal(), serialize(), Person::update_facing_direction(), and RemotePlayer::update_remotely().
FrontFaceDirectionMap
const std::map<FrontFaceDirection, float> Entity::FrontFaceDirectionMap
Initial value:
{
        {FORWARD, 0.0f}, {FORWARD | RIGHT, 45.0f}, {RIGHT, 90.0f},
        {BACK | RIGHT, 135.0f}, {BACK, 180.0f}, {BACK | LEFT, 225.0f},
        {LEFT, 270.0f}, {FORWARD | LEFT, 315.0f}}
Referenced by get_heading(), offsetFaceDirection(), render_highlighted(), and render_normal().
held_item
std::shared_ptr<Item> Entity::held_item = nullptr
Referenced by Furniture::can_place_item_into(), Player::handle_in_game_grab_or_drop(), Furniture::has_held_item(), serialize(), update_held_item_position(), Furniture::update_held_item_position(), and Customer::wait_in_queue().
id
int Entity::id
is_held
bool Entity::is_held = false
Referenced by Furniture::can_be_picked_up(), is_collidable(), and serialize().
is_highlighted
bool Entity::is_highlighted = false
Referenced by always_update(), and serialize().
name
std::string Entity::name = ``
Referenced by render_floating_name(), serialize(), update_name(), and RemotePlayer::update_remotely().
name_length
int Entity::name_length = 1
Referenced by serialize(), and update_name().
position
vec3 Entity::position
Referenced by Player::get_position_after_input(), AIPerson::get_wandering_job(), Player::handle_in_game_grab_or_drop(), Player::handle_in_planning_grab_or_drop(), BasePlayer::highlight_facing_furniture(), AIPerson::navigate_to(), BasePlayer::planning_update(), Player::rotate_furniture(), serialize(), CustomerSpawner::spawn(), update_held_item_position(), Furniture::update_held_item_position(), RemotePlayer::update_remotely(), RemotePlayer::update_xaxis_position(), RemotePlayer::update_zaxis_position(), GameCam::updateToTarget(), Customer::wait_in_queue(), and Player::work_furniture().
prev_position
vec3 Entity::prev_position
Referenced by serialize().
pushed_force
vec3 Entity::pushed_force {0.0, 0.0, 0.0}
Referenced by Person::always_update(), AIPerson::in_round_update(), and serialize().
raw_position
vec3 Entity::raw_position
Referenced by always_update(), Person::get_face_direction(), Player::get_position_after_input(), Person::handle_collision(), Customer::in_round_update(), Furniture::render_progress_bar(), serialize(), AIPerson::update_xaxis_position(), Player::update_xaxis_position(), TargetCube::update_xaxis_position(), AIPerson::update_zaxis_position(), Player::update_zaxis_position(), and TargetCube::update_zaxis_position().
The documentation for this struct was generated from the following file:
src/entity.h