NavMesh Struct Reference
#include <navmesh.h>
Public Member Functions
void addEntity (int e_id, Polygon p)
void removeEntity (int e_id)
void addShape (Polygon p, bool merge=true)
void removeShape (Polygon p)
bool overlap (Polygon a, Polygon b) const
Public Attributes
std::map< int, Polygon > entityShapes
std::vector< Polygon > shapes
Member Function Documentation
addEntity()
void NavMesh::addEntity (int e_id, Polygon p) [inline]
References entityShapes.
addShape()
void NavMesh::addShape (Polygon p, bool merge = true) [inline]
References overlap(), and shapes.
overlap()
bool NavMesh::overlap (Polygon a, Polygon b) const [inline]
References Polygon::inside(), and Polygon::points.
Referenced by addShape(), and removeShape().
removeEntity()
void NavMesh::removeEntity (int e_id) [inline]
References entityShapes.
removeShape()
void NavMesh::removeShape (Polygon p) [inline]
References overlap(), and shapes.
Member Data Documentation
entityShapes
std::map<int, Polygon> NavMesh::entityShapes
Referenced by addEntity(), and removeEntity().
shapes
std::vector<Polygon> NavMesh::shapes
Referenced by addShape(), and removeShape().
The documentation for this struct was generated from the following file:
src/engine/navmesh.h