FPSLayer Struct Reference
#include <fpslayer.h>
Public Member Functions
FPSLayer ()
virtual void onUpdate (float) override
virtual void onDraw (float) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
void onEvent (Event &event)
virtual bool onKeyPressed (KeyPressedEvent &)
virtual bool onGamepadButtonPressed (GamepadButtonPressedEvent &)
virtual bool onGamepadAxisMoved (GamepadAxisMovedEvent &)
virtual bool onCharPressedEvent (CharPressedEvent &)
const std::string & getname () const
Additional Inherited Members
Public Attributes inherited from Layer
int id
std::string name
Constructor & Destructor Documentation
FPSLayer()
FPSLayer::FPSLayer () [inline]
References profile::Profiler::clear().
Member Function Documentation
onDraw()
virtual void FPSLayer::onDraw (float) [inline], [override], [virtual]
Implements Layer.
References ext::draw_fps(), GlobalValueRegister::get(), GLOBALS, network::return_ping, network::there_ping, and network::total_ping.
onUpdate()
virtual void FPSLayer::onUpdate (float) [inline], [override], [virtual]
Implements Layer.
The documentation for this struct was generated from the following file:
src/layers/fpslayer.h