KeyMap Struct Reference
#include <keymap.h>
Public Member Functions
void forEachInputInMap (std::function< void(Event &)> cb) const
Static Public Member Functions
static void forEachCharTyped (std::function< void(Event &)> cb)
static float is_event (const menu::State &state, const InputName &name)
static bool is_event_once_DO_NOT_USE (const menu::State &state, const InputName &name)
static int get_key_code (const menu::State &state, const InputName &name)
static const tl::expected< GamepadAxisWithDir, KeyMapInputRequestError > get_axis (const menu::State &state, const InputName &name)
static GamepadButton get_button (const menu::State &state, const InputName &name)
static bool does_layer_map_contain_key (const menu::State &state, int keycode)
static bool does_layer_map_contain_button (const menu::State &state, GamepadButton button)
static bool does_layer_map_contain_axis (const menu::State state, GamepadAxis axis)
static const AnyInputs get_valid_inputs (const menu::State &state, const InputName &name)
static const std::vector< int > get_valid_keys (const menu::State &state, const InputName &name)
Private Member Functions
KeyMap ()
LayerMapping & get_or_create_layer_map (const menu::State &state)
void load_game_keys ()
void load_ui_keys ()
void load_default_keys ()
Static Private Member Functions
static void load_controller_db ()
static float visit_key (int keycode)
static float visit_key_down (int keycode)
static float visit_axis (GamepadAxisWithDir axis_with_dir)
static float visit_button (GamepadButton button)
static float visit_button_down (GamepadButton button)
Private Attributes
FullMap mapping
Constructor & Destructor Documentation
KeyMap()
KeyMap::KeyMap () [inline], [private]
Member Function Documentation
does_layer_map_contain_axis()
static bool KeyMap::does_layer_map_contain_axis (const menu::State state, GamepadAxis axis) [inline], [static]
Referenced by ui::IUIContextInputManager::process_gamepad_axis_event().
does_layer_map_contain_button()
static bool KeyMap::does_layer_map_contain_button (const menu::State & state, GamepadButton button) [inline], [static]
Referenced by ui::IUIContextInputManager::process_gamepad_button_event().
does_layer_map_contain_key()
static bool KeyMap::does_layer_map_contain_key (const menu::State & state, int keycode) [inline], [static]
Referenced by ui::IUIContextInputManager::process_keyevent().
forEachCharTyped()
static void KeyMap::forEachCharTyped (std::function< void(Event &)> cb) [inline], [static]
forEachInputInMap()
void KeyMap::forEachInputInMap (std::function< void(Event &)> cb) const [inline]
get_axis()
static const tl::expected< GamepadAxisWithDir, KeyMapInputRequestError > KeyMap::get_axis (const menu::State & state, const InputName & name) [inline], [static]
References get_valid_inputs(), and NO_VALID_INPUT.
Referenced by ui::IUIContextInputManager::pressed().
get_button()
static GamepadButton KeyMap::get_button (const menu::State & state, const InputName & name) [inline], [static]
References get_valid_inputs().
Referenced by GameDebugLayer::onGamepadButtonPressed(), GameLayer::onGamepadButtonPressed(), BasePauseLayer::onGamepadButtonPressed(), ui::IUIContextInputManager::pressed(), and ui::IUIContextInputManager::pressedButtonWithoutEat().
get_key_code()
static int KeyMap::get_key_code (const menu::State & state, const InputName & name) [inline], [static]
References get_valid_inputs().
Referenced by GameDebugLayer::onKeyPressed(), GameLayer::onKeyPressed(), BasePauseLayer::onKeyPressed(), ui::IUIContextInputManager::pressed(), ui::IUIContextInputManager::pressedWithoutEat(), and ui::IUIContextInputManager::process_keyevent().
get_or_create_layer_map()
LayerMapping & KeyMap::get_or_create_layer_map (const menu::State & state) [inline], [private]
get_valid_inputs()
static const AnyInputs KeyMap::get_valid_inputs (const menu::State & state, const InputName & name) [inline], [static]
Referenced by get_axis(), get_button(), get_key_code(), is_event(), is_event_once_DO_NOT_USE(), and SettingsLayer::SettingsLayer().
get_valid_keys()
static const std::vector< int > KeyMap::get_valid_keys (const menu::State & state, const InputName & name) [inline], [static]
Referenced by SettingsLayer::draw_keybindings().
is_event()
static float KeyMap::is_event (const menu::State & state, const InputName & name) [inline], [static]
References get_valid_inputs().
Referenced by Player::always_update(), ui::IUIContextInputManager::is_held_down(), Player::update_xaxis_position(), TargetCube::update_xaxis_position(), Player::update_zaxis_position(), and TargetCube::update_zaxis_position().
is_event_once_DO_NOT_USE()
static bool KeyMap::is_event_once_DO_NOT_USE (const menu::State & state, const InputName & name) [inline], [static]
References get_valid_inputs().
Referenced by Player::always_update().
load_controller_db()
static void KeyMap::load_controller_db () [inline], [static], [private]
References log_warn, and ext::set_gamepad_mappings().
load_default_keys()
void KeyMap::load_default_keys () [inline], [private]
load_game_keys()
void KeyMap::load_game_keys () [inline], [private]
References GamepadAxisWithDir::axis, menu::Game, Pause, PlayerBack, PlayerDoWork, PlayerForward, PlayerLeft, PlayerPickup, PlayerRight, PlayerRotateFurniture, TargetBack, TargetForward, TargetLeft, TargetRight, ToggleDebug, ToggleLobby, ToggleNetworkView, and TogglePlanning.
load_ui_keys()
void KeyMap::load_ui_keys () [inline], [private]
References GamepadAxisWithDir::axis, Pause, menu::Root, menu::UI, ValueDown, ValueLeft, ValueRight, ValueUp, WidgetBack, WidgetBackspace, WidgetCtrl, WidgetMod, WidgetNext, WidgetPaste, and WidgetPress.
visit_axis()
static float KeyMap::visit_axis (GamepadAxisWithDir axis_with_dir) [inline], [static], [private]
References GamepadAxisWithDir::axis, GamepadAxisWithDir::dir, ext::get_gamepad_axis_movement(), and util::sgn().
visit_button()
static float KeyMap::visit_button (GamepadButton button) [inline], [static], [private]
visit_button_down()
static float KeyMap::visit_button_down (GamepadButton button) [inline], [static], [private]
visit_key()
static float KeyMap::visit_key (int keycode) [inline], [static], [private]
References ext::is_key_pressed().
visit_key_down()
static float KeyMap::visit_key_down (int keycode) [inline], [static], [private]
References ext::is_key_down().
Member Data Documentation
mapping
FullMap KeyMap::mapping [private]
The documentation for this struct was generated from the following file:
src/engine/keymap.h