ui::components Namespace Reference
Functions
std::shared_ptr< Widget > mk_button (uuid id, SizeExpectation bx=button_x, SizeExpectation by=button_y)
std::shared_ptr< Widget > mk_icon_button (uuid id)
std::shared_ptr< Widget > mk_padding (SizeExpectation s1, SizeExpectation s2)
std::shared_ptr< Widget > mk_but_pad ()
std::shared_ptr< Widget > mk_root ()
std::shared_ptr< Widget > mk_row ()
std::shared_ptr< Widget > mk_column ()
std::shared_ptr< Widget > mk_text_id (uuid id)
std::shared_ptr< Widget > mk_text ()
Variables
const SizeExpectation icon_button_x = {.mode = Pixels, .value = 75.f}
const SizeExpectation icon_button_y = {.mode = Pixels, .value = 25.f}
const SizeExpectation button_x = {.mode = Pixels, .value = 130.f}
const SizeExpectation button_y = {.mode = Pixels, .value = 50.f}
const SizeExpectation padd_x = {.mode = Pixels, .value = 120.f}
const SizeExpectation padd_y = {.mode = Pixels, .value = 25.f}
Function Documentation
mk_but_pad()
std::shared_ptr< Widget > ui::components::mk_but_pad () [inline]
References ui::get(), ui::UIContext::own(), padd_x, and padd_y.
Referenced by NetworkLayer::draw_base_screen(), NetworkLayer::draw_connected_screen(), and MenuLayer::draw_menu_buttons().
mk_button()
std::shared_ptr< Widget > ui::components::mk_button (uuid id, SizeExpectation bx = button_x, SizeExpectation by = button_y) [inline]
References ui::get(), and ui::UIContext::own().
Referenced by SettingsLayer::back_button(), NetworkLayer::draw_base_screen(), NetworkLayer::draw_connected_screen(), SettingsLayer::draw_keybindings(), MenuLayer::draw_menu_buttons(), AboutLayer::draw_ui(), and BasePauseLayer::onDraw().
mk_column()
std::shared_ptr< Widget > ui::components::mk_column () [inline]
References ui::Children, ui::Column, ui::get(), and ui::UIContext::own().
Referenced by NetworkLayer::draw_base_screen().
mk_icon_button()
std::shared_ptr< Widget > ui::components::mk_icon_button (uuid id) [inline]
References ui::get(), icon_button_x, icon_button_y, and ui::UIContext::own().
Referenced by NetworkLayer::draw_connected_screen(), and NetworkLayer::draw_username().
mk_padding()
std::shared_ptr< Widget > ui::components::mk_padding (SizeExpectation s1, SizeExpectation s2) [inline]
References ui::get(), and ui::UIContext::own().
Referenced by SettingsLayer::back_button(), MenuLayer::draw_menu_buttons(), SettingsLayer::draw_root_settings(), MenuLayer::draw_title_section(), AboutLayer::draw_ui(), SettingsLayer::draw_ui(), SettingsLayer::master_volume(), SettingsLayer::music_volume(), and SettingsLayer::resolution_switcher().
mk_root()
std::shared_ptr< Widget > ui::components::mk_root () [inline]
References ui::get(), ui::UIContext::own(), ui::Row, Size_Px, WIN_HF(), and WIN_WF().
Referenced by AboutLayer::draw_ui(), SettingsLayer::draw_ui(), MenuLayer::onDraw(), and NetworkLayer::onDraw().
mk_row()
std::shared_ptr< Widget > ui::components::mk_row () [inline]
References ui::Children, ui::get(), ui::UIContext::own(), and ui::Row.
Referenced by NetworkLayer::draw_base_screen(), and NetworkLayer::draw_username().
mk_text()
std::shared_ptr< Widget > ui::components::mk_text () [inline]
References ui::get(), ui::UIContext::own(), and Size_Px.
Referenced by NetworkLayer::draw_connected_screen(), NetworkLayer::draw_ip_input_screen(), NetworkLayer::draw_username(), SettingsLayer::enable_post_processing(), SettingsLayer::master_volume(), SettingsLayer::music_volume(), SettingsLayer::resolution_switcher(), and SettingsLayer::streamer_safe_box().
mk_text_id()
std::shared_ptr< Widget > ui::components::mk_text_id (uuid id) [inline]
References ui::get(), ui::UIContext::own(), and Size_Px.
Variable Documentation
button_x
const SizeExpectation ui::components::button_x = {.mode = Pixels, .value = 130.f}
button_y
const SizeExpectation ui::components::button_y = {.mode = Pixels, .value = 50.f}
icon_button_x
const SizeExpectation ui::components::icon_button_x = {.mode = Pixels, .value = 75.f}
Referenced by mk_icon_button().
icon_button_y
const SizeExpectation ui::components::icon_button_y = {.mode = Pixels, .value = 25.f}
Referenced by mk_icon_button().
padd_x
const SizeExpectation ui::components::padd_x = {.mode = Pixels, .value = 120.f}
Referenced by mk_but_pad().
padd_y
const SizeExpectation ui::components::padd_y = {.mode = Pixels, .value = 25.f}
Referenced by mk_but_pad().