GameDebugLayer Struct Reference
#include <gamedebuglayer.h>
Public Member Functions
GameDebugLayer ()
virtual ~GameDebugLayer ()
void toggle_to_planning ()
void toggle_to_inround ()
bool onGamepadAxisMoved (GamepadAxisMovedEvent &) override
bool onGamepadButtonPressed (GamepadButtonPressedEvent &event) override
bool onKeyPressed (KeyPressedEvent &event) override
virtual void onUpdate (float) override
virtual void onDraw (float dt) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
void onEvent (Event &event)
virtual bool onKeyPressed (KeyPressedEvent &)
virtual bool onGamepadButtonPressed (GamepadButtonPressedEvent &)
virtual bool onGamepadAxisMoved (GamepadAxisMovedEvent &)
virtual bool onCharPressedEvent (CharPressedEvent &)
const std::string & getname () const
Public Attributes
bool debug_ui_enabled = false
bool network_ui_enabled = false
std::shared_ptr< ui::UIContext > ui_context
Public Attributes inherited from Layer
int id
std::string name
Private Member Functions
void debug_ui (float dt)
Constructor & Destructor Documentation
GameDebugLayer()
GameDebugLayer::GameDebugLayer () [inline]
References debug_ui_enabled, GLOBALS, network_ui_enabled, GlobalValueRegister::set(), and ui_context.
 GameDebugLayer()
virtual GameDebugLayer::~GameDebugLayer () [inline], [virtual]
Member Function Documentation
debug_ui()
void GameDebugLayer::debug_ui (float dt) [inline], [private]
References debug_ui_enabled, Size_Pct, Size_Px, ui_context, WIN_HF(), and WIN_WF().
Referenced by onDraw().
onDraw()
virtual void GameDebugLayer::onDraw (float dt) [inline], [override], [virtual]
Implements Layer.
References debug_ui(), debug_ui_enabled, network_ui_enabled, and MenuState::s_in_game().
onGamepadAxisMoved()
bool GameDebugLayer::onGamepadAxisMoved (GamepadAxisMovedEvent &) [inline], [override], [virtual]
Reimplemented from Layer.
onGamepadButtonPressed()
bool GameDebugLayer::onGamepadButtonPressed (GamepadButtonPressedEvent & event) [inline], [override], [virtual]
Reimplemented from Layer.
References GamepadButtonPressedEvent::button, debug_ui_enabled, menu::Game, KeyMap::get_button(), network_ui_enabled, MenuState::s_in_game(), toggle_to_inround(), toggle_to_planning(), and ui_context.
onKeyPressed()
bool GameDebugLayer::onKeyPressed (KeyPressedEvent & event) [inline], [override], [virtual]
Reimplemented from Layer.
References debug_ui_enabled, menu::Game, KeyMap::get_key_code(), EntityHelper::invalidatePathCache(), KeyEvent::keycode, game::Lobby, network_ui_enabled, MenuState::s_in_game(), toggle_to_inround(), toggle_to_planning(), and ui_context.
onUpdate()
virtual void GameDebugLayer::onUpdate (float) [inline], [override], [virtual]
Implements Layer.
References MenuState::s_in_game().
toggle_to_inround()
void GameDebugLayer::toggle_to_inround () [inline]
References EntityHelper::invalidatePathCache(), and GameState::s_toggle_to_inround().
Referenced by onGamepadButtonPressed(), and onKeyPressed().
toggle_to_planning()
void GameDebugLayer::toggle_to_planning () [inline]
References EntityHelper::invalidatePathCache(), and GameState::s_toggle_to_planning().
Referenced by onGamepadButtonPressed(), and onKeyPressed().
Member Data Documentation
debug_ui_enabled
bool GameDebugLayer::debug_ui_enabled = false
Referenced by debug_ui(), GameDebugLayer(), onDraw(), onGamepadButtonPressed(), and onKeyPressed().
network_ui_enabled
bool GameDebugLayer::network_ui_enabled = false
Referenced by GameDebugLayer(), onDraw(), onGamepadButtonPressed(), and onKeyPressed().
ui_context
std::shared_ptr<ui::UIContext> GameDebugLayer::ui_context
Referenced by debug_ui(), GameDebugLayer(), onGamepadButtonPressed(), and onKeyPressed().
The documentation for this struct was generated from the following file:
src/layers/gamedebuglayer.h