Trie Struct Reference
#include <trie.h>
Classes
struct Node
Public Member Functions
Trie ()
void add (const std::string &phrase)
bool contains (const std::string &phrase)
std::vector< std::string > dump (Node cur, const std::string &prefix)
std::vector< std::string > dump (const std::string &prefix=``)
Public Attributes
Node root
Private Member Functions
void add_ (Node &cur, const std::string &phrase)
void reset ()
std::optional< Node > subtrie (Node cur, const std::string &phrase)
bool contains_ (Node cur, const std::string &phrase)
Constructor & Destructor Documentation
Trie()
Trie::Trie () [inline]
References reset().
Member Function Documentation
add()
void Trie::add (const std::string & phrase) [inline]
References add_(), and root.
Referenced by SettingsLayer::SettingsLayer(), test_trie_insert_once(), test_trie_insert_once_and_dump(), test_trie_insert_once_and_found(), test_trie_insert_once_missing(), test_trie_insert_ten(), test_trie_insert_ten_and_dump(), test_trie_insert_ten_and_found(), and test_trie_insert_ten_similar_and_dump_prefix().
add_()
void Trie::add_ (Node & cur, const std::string & phrase) [inline], [private]
References add_(), Trie::Node::children, and Trie::Node::is_end.
Referenced by add(), and add_().
contains()
bool Trie::contains (const std::string & phrase) [inline]
References contains_(), and root.
Referenced by test_trie_insert_once_and_found(), test_trie_insert_once_missing(), and test_trie_insert_ten_and_found().
contains_()
bool Trie::contains_ (Node cur, const std::string & phrase) [inline], [private]
References subtrie().
Referenced by contains().
dump() [1/2]
std::vector< std::string > Trie::dump (const std::string & prefix = ``) [inline]
References dump(), root, and subtrie().
dump() [2/2]
std::vector< std::string > Trie::dump (Node cur, const std::string & prefix) [inline]
Referenced by dump(), test_trie_insert_once_and_dump(), test_trie_insert_ten_and_dump(), and test_trie_insert_ten_similar_and_dump_prefix().
reset()
void Trie::reset () [inline], [private]
References root.
Referenced by Trie().
subtrie()
std::optional< Node > Trie::subtrie (Node cur, const std::string & phrase) [inline], [private]
References Trie::Node::children, and subtrie().
Referenced by contains_(), dump(), and subtrie().
Member Data Documentation
root
Node Trie::root
Referenced by add(), contains(), dump(), operator<<(), and reset().
The documentation for this struct was generated from the following file:
src/engine/trie.h