WaitInQueueJob Struct Reference
#include <job.h>
Public Member Functions
WaitInQueueJob ()
virtual State run_state_initialize (const std::shared_ptr< Entity > &entity, float dt) override
virtual State run_state_working_at_start (const std::shared_ptr< Entity > &entity, float dt) override
virtual State run_state_working_at_end (const std::shared_ptr< Entity > &entity, float dt) override
virtual void before_each_job_tick (const std::shared_ptr< Entity > &, float) override
template<typename S >
void serialize (S &s)
Public Member Functions inherited from Job
bool path_empty () const
const vec2 & path_front () const
const std::deque< vec2 > & get_path () const
int p_size () const
vec2 path_index (int index) const
void path_pop_front ()
void update_path (const std::deque< vec2 > &new_path)
template<typename S >
void serialize (S &s)
void run_job_tick (const std::shared_ptr< Entity > &entity, float dt)
Job ()
Job (JobType _type, vec2 _start, vec2 _end)
virtual ~Job ()
Public Attributes
std::shared_ptr< Entity > reg
int spot_in_line = -1
Public Attributes inherited from Job
enum Job::State state = State::Initialize
JobType type
vec2 start
vec2 end
std::optional< vec2 > local
Additional Inherited Members
Public Types inherited from Job
enum struct State {
Initialize
, HeadingToStart
, HeadingToEnd
, WorkingAtStart
,
WorkingAtEnd
, Completed
 }
Static Public Member Functions inherited from Job
static Job * create_job_of_type (vec2, vec2, JobType type)
Protected Member Functions inherited from Job
virtual State run_state_initialize (const std::shared_ptr< Entity > &, float)
virtual State run_state_heading_to_start (const std::shared_ptr< Entity > &entity, float dt)
virtual State run_state_heading_to_end (const std::shared_ptr< Entity > &entity, float dt)
virtual State run_state_working_at_start (const std::shared_ptr< Entity > &, float)
virtual State run_state_working_at_end (const std::shared_ptr< Entity > &, float)
virtual void on_cleanup ()
virtual void before_each_job_tick (const std::shared_ptr< Entity > &, float)
bool has_local_target () const
Constructor & Destructor Documentation
WaitInQueueJob()
WaitInQueueJob::WaitInQueueJob () [inline]
Member Function Documentation
before_each_job_tick()
void WaitInQueueJob::before_each_job_tick (const std::shared_ptr< Entity > & entity, float) [override], [virtual]
Reimplemented from Job.
References Transform::as2(), and reg.
run_state_initialize()
Job::State WaitInQueueJob::run_state_initialize (const std::shared_ptr< Entity > & entity, float dt) [override], [virtual]
Reimplemented from Job.
References Job::end, HasWaitingQueue::get_next_pos(), Job::HeadingToStart, Job::Initialize, log_warn, reg, spot_in_line, Job::start, VALIDATE, WIQ_add_to_queue_and_get_position(), WIQ_position_in_line(), and WIQ_wait_and_return().
run_state_working_at_end()
Job::State WaitInQueueJob::run_state_working_at_end (const std::shared_ptr< Entity > & entity, float dt) [override], [virtual]
Reimplemented from Job.
References system_manager::logging_manager::announce(), Transform::as2(), Job::Completed, Job::create_job_of_type(), CanHoldItem::empty(), CanHoldItem::item(), reg, CanHoldItem::update(), VALIDATE, WIQ_leave_line(), WIQ_wait_and_return(), and Job::WorkingAtEnd.
run_state_working_at_start()
Job::State WaitInQueueJob::run_state_working_at_start (const std::shared_ptr< Entity > & entity, float dt) [override], [virtual]
Reimplemented from Job.
References system_manager::logging_manager::announce(), Job::HeadingToEnd, log_info, reg, spot_in_line, Job::start, VALIDATE, WIQ_can_move_up(), WIQ_position_in_line(), WIQ_wait_and_return(), and Job::WorkingAtStart.
serialize()
template<typename S >
void WaitInQueueJob::serialize (S & s) [inline]
References reg, and spot_in_line.
Member Data Documentation
reg
std::shared_ptr<Entity> WaitInQueueJob::reg
Referenced by before_each_job_tick(), run_state_initialize(), run_state_working_at_end(), run_state_working_at_start(), and serialize().
spot_in_line
int WaitInQueueJob::spot_in_line = -1
Referenced by run_state_initialize(), run_state_working_at_start(), and serialize().
The documentation for this struct was generated from the following files:
src/job.h
src/job.cpp