Furniture Struct Reference
#include <furniture.h>
Public Member Functions
Furniture (vec2 pos, Color face_color_in)
Furniture (vec3 pos, Color face_color_in)
Furniture (vec2 pos, Color face_color_in, Color base_color_in)
virtual void update_held_item_position () override
virtual void render_normal () const override
void render_progress_bar () const
virtual void do_work (float, Person *)
virtual bool has_work () const
virtual bool add_to_navmesh () override
virtual bool can_rotate () const
virtual bool can_be_picked_up ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr) override
virtual bool has_held_item () const
Public Member Functions inherited from Entity
FrontFaceDirection offsetFaceDirection (FrontFaceDirection startingDirection, float offset) const
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
void update_name (const std::string &new_name)
virtual bool can_take_item_from () const
virtual bool collides (BoundingBox b) const
virtual BoundingBox bounds () const
virtual void update_position (const vec3 &p)
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void render () const final
virtual void update (float dt) final
Protected Member Functions
Furniture ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual void render_debug_mode () const
virtual void render_highlighted () const
virtual void render_normal () const
virtual void render_floating_name () const
virtual std::optional< ModelInfo > model () const
vec3 snap_position () const
virtual void update_held_item_position ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void always_update (float)
virtual void planning_update (float)
virtual void in_round_update (float)
virtual bool is_snappable ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Protected Attributes
float pct_work_complete = 0.f
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Public Types inherited from Entity
enum FrontFaceDirection { FORWARD = 0x1
, RIGHT = 0x2
, BACK = 0x4
, LEFT = 0x8
 }
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, FrontFaceDirection direction)
Public Attributes inherited from Entity
const std::map< FrontFaceDirection, float > FrontFaceDirectionMap
const std::map< int, FrontFaceDirection > DirectionToFrontFaceMap
int id
vec3 raw_position
vec3 prev_position
vec3 position
vec3 pushed_force {0.0, 0.0, 0.0}
Color face_color
Color base_color
bool cleanup = false
bool is_highlighted = false
bool is_held = false
FrontFaceDirection face_direction = FrontFaceDirection::FORWARD
std::shared_ptr< Item > held_item = nullptr
int name_length = 1
std::string name = ``
Constructor & Destructor Documentation
Furniture() [1/4]
Furniture::Furniture () [inline], [protected]
Furniture() [2/4]
Furniture::Furniture (vec2 pos, Color face_color_in) [inline]
Furniture() [3/4]
Furniture::Furniture (vec3 pos, Color face_color_in) [inline]
Furniture() [4/4]
Furniture::Furniture (vec2 pos, Color face_color_in, Color base_color_in) [inline]
Member Function Documentation
add_to_navmesh()
virtual bool Furniture::add_to_navmesh () [inline], [override], [virtual]
Reimplemented from Entity.
can_be_picked_up()
virtual bool Furniture::can_be_picked_up () [inline], [virtual]
References Entity::is_held.
can_place_item_into()
virtual bool Furniture::can_place_item_into (std::shared_ptr< Item > = nullptr) [inline], [override], [virtual]
Reimplemented from Entity.
References Entity::held_item.
can_rotate()
virtual bool Furniture::can_rotate () const [inline], [virtual]
do_work()
virtual void Furniture::do_work (float , Person *) [inline], [virtual]
has_held_item()
virtual bool Furniture::has_held_item () const [inline], [virtual]
References Entity::held_item.
has_work()
virtual bool Furniture::has_work () const [inline], [virtual]
Referenced by render_progress_bar().
render_normal()
virtual void Furniture::render_normal () const [inline], [override], [virtual]
Reimplemented from Entity.
References Entity::render_normal(), and render_progress_bar().
render_progress_bar()
void Furniture::render_progress_bar () const [inline]
References has_work(), pct_work_complete, Entity::raw_position, and TILESIZE.
Referenced by render_normal().
serialize()
template<typename S >
void Furniture::serialize (S & s) [inline], [private]
References pct_work_complete.
update_held_item_position()
virtual void Furniture::update_held_item_position () [inline], [override], [virtual]
Reimplemented from Entity.
References Entity::held_item, Entity::position, and TILESIZE.
Member Data Documentation
pct_work_complete
float Furniture::pct_work_complete = 0.f [protected]
Referenced by render_progress_bar(), and serialize().
The documentation for this struct was generated from the following file:
src/furniture.h