Files Struct Reference
#include <files.h>
Public Member Functions
Files (FilesConfig config)
fs::path game_folder () const
bool ensure_game_folder_exists ()
fs::path settings_filepath () const
fs::path resource_folder () const
fs::path game_controller_db () const
std::string fetch_resource_path (std::string_view group, std::string_view name) const
void for_resources_in_folder (std::string_view group, std::string_view folder, std::function< void(std::string, std::string)>) const
void folder_locations () const
Public Attributes
std::string root = `example_game`
std::string settings_file = `settings.bin`
Constructor & Destructor Documentation
Files()
Files::Files (FilesConfig config) [explicit]
References ensure_game_folder_exists().
Member Function Documentation
ensure_game_folder_exists()
bool Files::ensure_game_folder_exists ()
References game_folder(), and log_info.
Referenced by Files().
fetch_resource_path()
std::string Files::fetch_resource_path (std::string_view group, std::string_view name) const
References resource_folder().
folder_locations()
void Files::folder_locations () const
References log_info.
for_resources_in_folder()
void Files::for_resources_in_folder (std::string_view group, std::string_view folder, std::function< void(std::string, std::string)> cb) const
References resource_folder().
game_controller_db()
fs::path Files::game_controller_db () const
References resource_folder().
game_folder()
fs::path Files::game_folder () const
References root.
Referenced by ensure_game_folder_exists(), and settings_filepath().
resource_folder()
fs::path Files::resource_folder () const
Referenced by fetch_resource_path(), for_resources_in_folder(), and game_controller_db().
settings_filepath()
fs::path Files::settings_filepath () const
References game_folder(), and settings_file.
Member Data Documentation
root
std::string Files::root = `example_game`
Referenced by game_folder().
settings_file
std::string Files::settings_file = `settings.bin`
Referenced by settings_filepath().
The documentation for this struct was generated from the following files:
src/engine/files.h
src/engine/files.cpp