src/engine/random.h File Reference
#include <random>
Functions
int randIn (int a, int b)
int randSign ()
std::mt19937 make_engine (size_t seed)
Function Documentation
make_engine()
std::mt19937 make_engine (size_t seed) [inline]
Referenced by GameMapInfo::update_seed().
randIn()
int randIn (int a, int b) [inline]
Referenced by create_wandering_job(), Library< T >::get_random_match(), get_random_name(), Pill::init(), and randSign().
randSign()
int randSign () [inline]
References randIn().
Referenced by system_manager::person_update_given_new_pos().