EventDispatcher Struct Reference
#include <event.h>
Public Member Functions
EventDispatcher (Event &e)
template<typename T >
bool dispatch (std::function< bool(T &)> func)
Public Attributes
Event & event
Constructor & Destructor Documentation
EventDispatcher()
EventDispatcher::EventDispatcher (Event & e) [inline], [explicit]
Member Function Documentation
dispatch()
template<typename T >
bool EventDispatcher::dispatch (std::function< bool(T &)> func) [inline]
References event, and Event::getEventType().
Referenced by App::onEvent(), AboutLayer::onEvent(), GameDebugLayer::onEvent(), GameLayer::onEvent(), MenuLayer::onEvent(), NetworkLayer::onEvent(), BasePauseLayer::onEvent(), and SettingsLayer::onEvent().
Member Data Documentation
event
Event& EventDispatcher::event
Referenced by dispatch().
The documentation for this struct was generated from the following file:
src/engine/event.h