CanHoldFurniture Struct Reference
#include <can_hold_furniture.h>
Public Member Functions
virtual ~CanHoldFurniture ()
bool empty () const
bool is_holding_furniture () const
template<typename T >
std::shared_ptr< T > asT () const
void update (std::shared_ptr< Entity > furniture)
std::shared_ptr< Entity > furniture () const
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
std::shared_ptr< Entity > held_furniture = nullptr
Constructor & Destructor Documentation
 CanHoldFurniture()
virtual CanHoldFurniture::~CanHoldFurniture () [inline], [virtual]
Member Function Documentation
asT()
template<typename T >
std::shared_ptr< T > CanHoldFurniture::asT () const [inline]
References held_furniture.
empty()
bool CanHoldFurniture::empty () const [inline]
References held_furniture.
Referenced by system_manager::handle_autodrop_furniture_when_exiting_planning(), and is_holding_furniture().
furniture()
std::shared_ptr< Entity > CanHoldFurniture::furniture () const [inline]
References held_furniture.
Referenced by system_manager::input_process_manager::planning::drop_held_furniture(), and update().
is_holding_furniture()
bool CanHoldFurniture::is_holding_furniture () const [inline]
References empty().
Referenced by system_manager::ui::render_player_info(), and system_manager::sophie().
serialize()
template<typename S >
void CanHoldFurniture::serialize (S & s) [inline], [private]
References held_furniture.
update()
void CanHoldFurniture::update (std::shared_ptr< Entity > furniture) [inline]
References furniture(), and held_furniture.
Referenced by system_manager::input_process_manager::planning::drop_held_furniture().
Member Data Documentation
held_furniture
std::shared_ptr<Entity> CanHoldFurniture::held_furniture = nullptr [private]
Referenced by asT(), empty(), furniture(), serialize(), and update().
The documentation for this struct was generated from the following file:
src/components/can_hold_furniture.h