CanBeHighlighted Struct Reference
#include <can_be_highlighted.h>
Public Member Functions
virtual ~CanBeHighlighted ()
bool is_highlighted () const
bool is_not_highlighted () const
void update (bool is_h)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
bool highlighted
Constructor & Destructor Documentation
 CanBeHighlighted()
virtual CanBeHighlighted::~CanBeHighlighted () [inline], [virtual]
Member Function Documentation
is_highlighted()
bool CanBeHighlighted::is_highlighted () const [inline]
References highlighted.
Referenced by is_not_highlighted(), and system_manager::render_manager::render_normal().
is_not_highlighted()
bool CanBeHighlighted::is_not_highlighted () const [inline]
References is_highlighted().
serialize()
template<typename S >
void CanBeHighlighted::serialize (S & s) [inline], [private]
References highlighted.
update()
void CanBeHighlighted::update (bool is_h) [inline]
References highlighted.
Referenced by system_manager::reset_highlighted().
Member Data Documentation
highlighted
bool CanBeHighlighted::highlighted [private]
Referenced by is_highlighted(), serialize(), and update().
The documentation for this struct was generated from the following file:
src/components/can_be_highlighted.h