util Namespace Reference
Classes
struct overloaded
Functions
void force_segfault ()
template<class... Ts>
overloaded (Ts...) -> overloaded< Ts... >
template<typename T >
int sgn (T val)
static float deg2rad (float deg)
static float rad2deg (float rad)
static std::vector< std::string > split_string (const std::string &str, const std::string &delimiter)
std::vector< std::string > split_re (const std::string &input, const std::string &regex)
static float clamp (float a, float mn, float mx)
static float round_up (float value, int decimal_places)
static float trunc (float value, int decimal_places)
static float lerp (float a, float b, float pct)
template<template< typename... > class Container, typename K , typename V , typename... Ts>
V map_get_or_default (Container< K, V, Ts... > map, K key, V def_value)
template<typename Range , typename Value = typename Range::value_type>
std::string join (Range const &elements, const char *const delimiter)
int words_in_string (const std::string &str)
Function Documentation
clamp()
static float util::clamp (float a, float mn, float mx) [static]
Referenced by system_manager::input_process_manager::collect_user_input(), Settings::update_master_volume(), and Settings::update_music_volume().
deg2rad()
static float util::deg2rad (float deg) [static]
Referenced by Transform::get_heading(), and system_manager::ui::render_timer().
force_segfault()
void util::force_segfault () [inline]
join()
template<typename Range , typename Value = typename Range::value_type>
std::string util::join (Range const & elements, const char *const delimiter) [inline]
lerp()
static float util::lerp (float a, float b, float pct) [static]
Referenced by system_manager::ui::render_timer().
map_get_or_default()
template<template< typename... > class Container, typename K , typename V , typename... Ts>
V util::map_get_or_default (Container< K, V, Ts... > map, K key, V def_value) [inline]
overloaded()
template<class... Ts>
util::overloaded (Ts...) -> overloaded< Ts... >
rad2deg()
static float util::rad2deg (float rad) [static]
Referenced by system_manager::input_process_manager::collect_user_input(), and Transform::turn_to_face_pos().
round_up()
static float util::round_up (float value, int decimal_places) [static]
sgn()
template<typename T >
int util::sgn (T val)
Referenced by KeyMap::visit_axis().
split_re()
std::vector< std::string > util::split_re (const std::string & input, const std::string & regex) [inline]
Referenced by test_trie_insert_ten(), test_trie_insert_ten_and_dump(), test_trie_insert_ten_and_found(), and test_trie_insert_ten_similar_and_dump_prefix().
split_string()
static std::vector< std::string > util::split_string (const std::string & str, const std::string & delimiter) [static]
Referenced by GameMapInfo::generate_map(), and test::setup().
trunc()
static float util::trunc (float value, int decimal_places) [static]
Referenced by system_manager::ui::render_block_state_change_reason(), and Transform::trunc().
words_in_string()
int util::words_in_string (const std::string & str) [inline]