GlobalValueRegister Struct Reference
#include <globals_register.h>
Public Member Functions
template<typename T >
T * get_ptr (const std::string &name) const
template<typename T >
T get (const std::string &name) const
template<typename T >
T get_or_default (const std::string &name, T default_value) const
template<typename T >
void set (const std::string &name, T *value)
template<typename T >
T update (const std::string &name, T value)
bool contains (const std::string &name) const
Public Attributes
std::map< std::string, void * > globals
Member Function Documentation
contains()
bool GlobalValueRegister::contains (const std::string & name) const [inline]
References globals.
Referenced by get_or_default().
get()
template<typename T >
T GlobalValueRegister::get (const std::string & name) const [inline]
Referenced by FPSLayer::onDraw(), and SpeechBubble::render().
get_or_default()
template<typename T >
T GlobalValueRegister::get_or_default (const std::string & name, T default_value) const [inline]
References contains().
Referenced by is_server(), GameLayer::onDraw(), and SystemManager::render().
get_ptr()
template<typename T >
T * GlobalValueRegister::get_ptr (const std::string & name) const [inline]
References globals.
Referenced by LobbyMapInfo::onDraw(), GameLayer::onDraw(), GameLayer::onUpdate(), and network::Client::send_player_input_packet().
set()
template<typename T >
void GlobalValueRegister::set (const std::string & name, T * value) [inline]
References globals.
Referenced by App::App(), network::Client::Client(), network::Client::client_process_message_string(), GameDebugLayer::GameDebugLayer(), GameLayer::GameLayer(), App::onWindowResize(), network::Server::run(), network::Server::Server(), and network::Info::set_role().
update()
template<typename T >
T GlobalValueRegister::update (const std::string & name, T value) [inline]
Member Data Documentation
globals
std::map<std::string, void*> GlobalValueRegister::globals
Referenced by contains(), get_ptr(), and set().
The documentation for this struct was generated from the following file:
src/engine/globals_register.h