system_manager::job_system Namespace Reference
Functions
Job * create_wandering_job (std::shared_ptr< Entity > entity)
void replace_job_with_job_type (std::shared_ptr< Entity > entity, float, JobType job_type)
void find_new_job (std::shared_ptr< Entity > entity, float dt)
void replace_finished_job (std::shared_ptr< Entity > entity, float dt)
void update_job_information (std::shared_ptr< Entity > entity, float dt)
void handle_job_holder_pushed (std::shared_ptr< Entity > entity, float)
void update_position_from_job (std::shared_ptr< Entity > entity, float dt)
void render_job_visual (std::shared_ptr< Entity > entity, float)
Function Documentation
create_wandering_job()
Job * system_manager::job_system::create_wandering_job (std::shared_ptr< Entity > entity) [inline]
References EntityHelper::isWalkable(), randIn(), and Wandering.
Referenced by replace_job_with_job_type().
find_new_job()
void system_manager::job_system::find_new_job (std::shared_ptr< Entity > entity, float dt) [inline]
References CanPerformJob::get_next_job_type(), CanPerformJob::job(), CanPerformJob::job_queue(), and replace_job_with_job_type().
Referenced by replace_finished_job(), and update_job_information().
handle_job_holder_pushed()
void system_manager::job_system::handle_job_holder_pushed (std::shared_ptr< Entity > entity, float) [inline]
References SoundLibrary::get(), CanPerformJob::has_job(), CanPerformJob::job(), and CanBePushed::pushed_force.
Referenced by SystemManager::in_round_update().
render_job_visual()
void system_manager::job_system::render_job_visual (std::shared_ptr< Entity > entity, float) [inline]
References CanPerformJob::has_job(), CanPerformJob::job(), TILESIZE, and vec::to3().
Referenced by system_manager::render_manager::render_debug().
replace_finished_job()
void system_manager::job_system::replace_finished_job (std::shared_ptr< Entity > entity, float dt) [inline]
References Job::Completed, find_new_job(), and CanPerformJob::job().
replace_job_with_job_type()
void system_manager::job_system::replace_job_with_job_type (std::shared_ptr< Entity > entity, float , JobType job_type) [inline]
References create_wandering_job(), log_warn, CanPerformJob::update(), Wait, WaitInQueue, and Wandering.
Referenced by find_new_job().
update_job_information()
void system_manager::job_system::update_job_information (std::shared_ptr< Entity > entity, float dt) [inline]
References system_manager::logging_manager::announce(), Transform::as2(), Job::Completed, CanHoldItem::empty(), find_new_job(), astar::find_path(), Job::HeadingToEnd, Job::HeadingToStart, Job::Initialize, EntityHelper::isWalkable(), CanHoldItem::item(), CanPerformJob::job(), log_info, log_warn, M_ASSERT, CanPerformJob::needs_job(), HasWaitingQueue::next_line_position, HasWaitingQueue::ppl_in_line, CanPerformJob::push_and_reset(), TILESIZE, CanHoldItem::update(), Wait, WaitInQueue, Wandering, Job::WorkingAtEnd, and Job::WorkingAtStart.
Referenced by SystemManager::in_round_update().
update_position_from_job()
void system_manager::job_system::update_position_from_job (std::shared_ptr< Entity > entity, float dt) [inline]
References CanHaveAilment::ailment(), CanPerformJob::has_job(), CanPerformJob::job(), Transform::position, Transform::raw_position, and HasBaseSpeed::speed().