HasWaitingQueue Struct Reference
#include <has_waiting_queue.h>
Public Member Functions
virtual ~HasWaitingQueue ()
bool is_full () const
bool has_space () const
std::shared_ptr< Entity > person (int i)
void erase (int index)
int get_next_pos () const
bool matching_id (int id, int i) const
bool has_matching_person (int id) const
HasWaitingQueue & add_customer (const std::shared_ptr< Entity > &customer)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
void dump_contents () const
template<typename S >
void serialize (S &s)
Private Attributes
std::array< std::shared_ptr< Entity >, max_queue_size > ppl_in_line
int next_line_position = 0
Constructor & Destructor Documentation
 HasWaitingQueue()
virtual HasWaitingQueue::~HasWaitingQueue () [inline], [virtual]
Member Function Documentation
add_customer()
HasWaitingQueue & HasWaitingQueue::add_customer (const std::shared_ptr< Entity > & customer)
References has_matching_person(), log_info, DebugName::name(), next_line_position, ppl_in_line, and VALIDATE.
dump_contents()
void HasWaitingQueue::dump_contents () const [private]
References log_info, max_queue_size, and ppl_in_line.
erase()
void HasWaitingQueue::erase (int index) [inline]
References max_queue_size, next_line_position, and ppl_in_line.
get_next_pos()
int HasWaitingQueue::get_next_pos () const [inline]
References next_line_position.
Referenced by WaitInQueueJob::run_state_initialize(), and WIQ_add_to_queue_and_get_position().
has_matching_person()
bool HasWaitingQueue::has_matching_person (int id) const
References log_warn, matching_id(), and max_queue_size.
Referenced by add_customer(), and WIQ_position_in_line().
has_space()
bool HasWaitingQueue::has_space () const [inline]
References max_queue_size, and next_line_position.
Referenced by is_full().
is_full()
bool HasWaitingQueue::is_full () const [inline]
References has_space().
matching_id()
bool HasWaitingQueue::matching_id (int id, int i) const
References ppl_in_line.
Referenced by has_matching_person().
person()
std::shared_ptr< Entity > HasWaitingQueue::person (int i) [inline]
References ppl_in_line.
serialize()
template<typename S >
void HasWaitingQueue::serialize (S & s) [inline], [private]
References next_line_position, and ppl_in_line.
Member Data Documentation
next_line_position
int HasWaitingQueue::next_line_position = 0 [private]
Referenced by add_customer(), erase(), get_next_pos(), has_space(), and serialize().
ppl_in_line
std::array<std::shared_ptr<Entity>, max_queue_size> HasWaitingQueue::ppl_in_line [private]
Referenced by add_customer(), dump_contents(), erase(), matching_id(), person(), and serialize().
The documentation for this struct was generated from the following files:
src/components/has_waiting_queue.h
src/job.cpp