App Struct Reference
#include <app.h>
Public Member Functions
App (const AppSettings &)
~App ()
void pushLayer (Layer *layer)
void pushOverlay (Layer *layer)
void onEvent (Event &event)
bool onWindowResize (WindowResizeEvent event)
void processEvent (Event &e)
void close ()
void run ()
void loop (float dt)
Public Attributes
bool running = false
LayerStack layerstack
int width
int height
raylib::RenderTexture2D mainRT
Private Member Functions
void draw_all_to_texture (float dt)
void render_to_screen ()
Static Private Member Functions
static void start_post_processing ()
static void end_post_processing ()
Constructor & Destructor Documentation
App()
App::App (const AppSettings & settings) [explicit]
References GLOBALS, height, mainRT, GlobalValueRegister::set(), and width.
 App()
App::~App ()
References mainRT.
Member Function Documentation
close()
void App::close ()
References running.
draw_all_to_texture()
void App::draw_all_to_texture (float dt) [private]
References layerstack, mainRT, and TRACY_ZONE_SCOPED.
Referenced by loop().
end_post_processing()
void App::end_post_processing () [static], [private]
Referenced by render_to_screen().
loop()
void App::loop (float dt)
References draw_all_to_texture(), layerstack, processEvent(), render_to_screen(), TRACY_FRAME_MARK, and TRACY_ZONE_SCOPED.
Referenced by run().
onEvent()
void App::onEvent (Event & event)
References EventDispatcher::dispatch(), and onWindowResize().
Referenced by processEvent().
onWindowResize()
bool App::onWindowResize (WindowResizeEvent event)
References GLOBALS, height, WindowResizeEvent::height, log_info, mainRT, GlobalValueRegister::set(), width, and WindowResizeEvent::width.
Referenced by onEvent().
processEvent()
void App::processEvent (Event & e)
References LayerStack::begin(), LayerStack::end(), Event::handled, layerstack, onEvent(), and TRACY_ZONE_SCOPED.
Referenced by loop().
pushLayer()
void App::pushLayer (Layer * layer)
References layerstack, and LayerStack::push().
pushOverlay()
void App::pushOverlay (Layer * layer)
References layerstack, and LayerStack::pushOverlay().
render_to_screen()
void App::render_to_screen () [private]
References end_post_processing(), mainRT, start_post_processing(), and TRACY_ZONE_SCOPED.
Referenced by loop().
run()
void App::run ()
References log_info, loop(), and running.
start_post_processing()
void App::start_post_processing () [static], [private]
References ShaderLibrary::get().
Referenced by render_to_screen().
Member Data Documentation
height
int App::height
Referenced by App(), and onWindowResize().
layerstack
LayerStack App::layerstack
Referenced by draw_all_to_texture(), loop(), processEvent(), pushLayer(), and pushOverlay().
mainRT
raylib::RenderTexture2D App::mainRT
Referenced by App(), draw_all_to_texture(), onWindowResize(), render_to_screen(), and ~App().
running
bool App::running = false
Referenced by close(), and run().
width
int App::width
Referenced by App(), and onWindowResize().
The documentation for this struct was generated from the following files:
src/engine/app.h
src/engine/app.cpp