ModelRenderer Struct Reference
#include <model_renderer.h>
Public Member Functions
virtual ~ModelRenderer ()
bool has_model () const
std::optional< ModelInfo > model_info () const
raylib::Model model () const
void update (const ModelInfo &new_info)
void update_model_name (const std::string &new_name)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
std::optional< ModelInfo > info
Constructor & Destructor Documentation
 ModelRenderer()
virtual ModelRenderer::~ModelRenderer () [inline], [virtual]
Member Function Documentation
has_model()
bool ModelRenderer::has_model () const [inline]
References model_info().
Referenced by system_manager::render_manager::render_model_highlighted(), and system_manager::render_manager::render_model_normal().
model()
raylib::Model ModelRenderer::model () const [inline]
References ModelLibrary::get(), and model_info().
Referenced by system_manager::render_manager::render_model_highlighted(), and system_manager::render_manager::render_model_normal().
model_info()
std::optional< ModelInfo > ModelRenderer::model_info () const [inline]
References info.
Referenced by has_model(), model(), system_manager::render_manager::render_model_highlighted(), and system_manager::render_manager::render_model_normal().
serialize()
template<typename S >
void ModelRenderer::serialize (S & s) [inline], [private]
References info.
update()
void ModelRenderer::update (const ModelInfo & new_info) [inline]
References info.
Referenced by system_manager::render_manager::update_character_model_from_index().
update_model_name()
void ModelRenderer::update_model_name (const std::string & new_name) [inline]
References info.
Referenced by system_manager::refetch_dynamic_model_names().
Member Data Documentation
info
std::optional<ModelInfo> ModelRenderer::info [private]
Referenced by model_info(), serialize(), update(), and update_model_name().
The documentation for this struct was generated from the following file:
src/components/model_renderer.h