tests Namespace Reference
Functions
void run_all ()
void test_half ()
void test_tenth ()
void lerp_test ()
void test_empty ()
void test_just_root ()
void test_single_child ()
void test_two_children ()
void test_two_children_parent_size ()
void test_two_children_parent_size_too_small ()
void test_add_child ()
void test_add_child_again ()
void test_autolayout_wrap_column ()
void test_widget_fill_space_after_column_small ()
void test_widget_fill_space_after_column_with_child ()
void test_widget_fill_space_after_column_with_children ()
void test_widget_fill_space_after_column ()
void test_widget_fill_space_after_column_complex ()
void test_ui_widget ()
Function Documentation
lerp_test()
void tests::lerp_test ()
References test_half(), and test_tenth().
Referenced by run_all().
run_all()
void tests::run_all ()
References all_tests(), lerp_test(), test_all_pathing(), and test_ui_widget().
Referenced by main().
test_add_child()
void tests::test_add_child ()
References ui::Widget::add_child(), ui::Widget::children, M_TEST_EQ, ui::SizeExpectation::mode, ui::Widget::parent, and ui::Widget::size_expected.
Referenced by test_ui_widget().
test_add_child_again()
void tests::test_add_child_again ()
References ui::Widget::add_child(), ui::Widget::children, M_TEST_EQ, M_TEST_NEQ, and ui::Widget::parent.
Referenced by test_ui_widget().
test_autolayout_wrap_column()
void tests::test_autolayout_wrap_column ()
References ui::Widget::add_child(), ui::Widget::children, ui::Widget::computed_relative_pos, ui::Widget::computed_size, ui::Widget::growflags, M_TEST_EQ, ui::SizeExpectation::mode, ui::Widget::parent, and ui::Widget::size_expected.
Referenced by test_ui_widget().
test_empty()
void tests::test_empty ()
Referenced by test_ui_widget().
test_half()
void tests::test_half ()
References vec::lerp(), and M_TEST_EQ.
Referenced by lerp_test().
test_just_root()
void tests::test_just_root ()
References ui::Widget::computed_size, M_TEST_EQ, ui::SizeExpectation::mode, ui::Widget::size_expected, WIN_H(), WIN_HF(), WIN_W(), and WIN_WF().
Referenced by test_ui_widget().
test_single_child()
void tests::test_single_child ()
References ui::Widget::add_child(), ui::Widget::computed_size, M_TEST_EQ, ui::SizeExpectation::mode, ui::Widget::size_expected, WIN_H(), WIN_HF(), WIN_W(), and WIN_WF().
Referenced by test_ui_widget().
test_tenth()
void tests::test_tenth ()
References vec::lerp(), and M_TEST_EQ.
Referenced by lerp_test().
test_two_children()
void tests::test_two_children ()
References ui::Widget::add_child(), ui::Widget::computed_size, M_TEST_EQ, ui::SizeExpectation::mode, ui::Widget::size_expected, WIN_H(), WIN_HF(), WIN_W(), and WIN_WF().
Referenced by test_ui_widget().
test_two_children_parent_size()
void tests::test_two_children_parent_size ()
References ui::Widget::add_child(), ui::Widget::computed_size, M_TEST_EQ, ui::SizeExpectation::mode, ui::Widget::size_expected, WIN_H(), WIN_HF(), and WIN_WF().
Referenced by test_ui_widget().
test_two_children_parent_size_too_small()
void tests::test_two_children_parent_size_too_small ()
References ui::Widget::add_child(), ui::Widget::computed_size, M_TEST_EQ, M_TEST_LEQ, ui::SizeExpectation::mode, and ui::Widget::size_expected.
Referenced by test_ui_widget().
test_ui_widget()
void tests::test_ui_widget ()
References test_add_child(), test_add_child_again(), test_autolayout_wrap_column(), test_empty(), test_just_root(), test_single_child(), test_two_children(), test_two_children_parent_size(), test_two_children_parent_size_too_small(), test_widget_fill_space_after_column(), test_widget_fill_space_after_column_complex(), test_widget_fill_space_after_column_small(), and test_widget_fill_space_after_column_with_children().
Referenced by run_all().
test_widget_fill_space_after_column()
void tests::test_widget_fill_space_after_column ()
References ui::Widget::add_child(), and M_TEST_EQ.
Referenced by test_ui_widget().
test_widget_fill_space_after_column_complex()
void tests::test_widget_fill_space_after_column_complex ()
References ui::Widget::add_child(), and M_TEST_EQ.
Referenced by test_ui_widget().
test_widget_fill_space_after_column_small()
void tests::test_widget_fill_space_after_column_small ()
References ui::Widget::add_child(), and M_TEST_EQ.
Referenced by test_ui_widget().
test_widget_fill_space_after_column_with_child()
void tests::test_widget_fill_space_after_column_with_child ()
References ui::Widget::add_child(), and M_TEST_EQ.
test_widget_fill_space_after_column_with_children()
void tests::test_widget_fill_space_after_column_with_children ()
References ui::Widget::add_child(), and M_TEST_EQ.
Referenced by test_ui_widget().