FontSizeCache Struct Reference
#include <font_sizer.h>
Public Member Functions
virtual void init ()
void set_font (raylib::Font f)
float get_font_size_impl (const std::string &content, float width, float height, float spacing) const
float get_font_size (const std::string &content, float width, float height, float spacing)
Public Attributes
raylib::Font font
std::unordered_map< size_t, float > _font_size_memo
Member Function Documentation
get_font_size()
float FontSizeCache::get_font_size (const std::string & content, float width, float height, float spacing) [inline]
References _font_size_memo, FZInfo::content, get_font_size_impl(), and log_trace.
Referenced by ui::UIContext::_draw_text(), and ToastLayer::onDraw().
get_font_size_impl()
float FontSizeCache::get_font_size_impl (const std::string & content, float width, float height, float spacing) const [inline]
References log_trace.
Referenced by get_font_size().
init()
virtual void FontSizeCache::init () [inline], [virtual]
Reimplemented in ui::UIContext.
References set_font().
Referenced by ui::UIContext::init(), and ToastLayer::ToastLayer().
set_font()
void FontSizeCache::set_font (raylib::Font f) [inline]
Referenced by init().
Member Data Documentation
_font_size_memo
std::unordered_map<size_t, float> FontSizeCache::_font_size_memo
Referenced by get_font_size().
font
raylib::Font FontSizeCache::font
The documentation for this struct was generated from the following file:
src/engine/font_sizer.h