network::Client Struct Reference
#include <client.h>
Classes
struct ConnectionInfo
Public Member Functions
Client ()
void update_username (std::string new_name)
void lock_in_ip ()
void tick (float dt)
void send_player_input_packet (int my_id)
void client_process_message_string (std::string msg)
Public Attributes
struct network::Client::ConnectionInfo conn_info
int id = 0
std::shared_ptr< internal::Client > client_p
std::map< int, std::shared_ptr< RemotePlayer > > remote_players
std::shared_ptr< Map > map
std::vector< ClientPacket::AnnouncementInfo > announcements
float next_tick_reset = 0.02f
float next_tick = 0.0f
Constructor & Destructor Documentation
Client()
network::Client::Client () [inline]
References client_p, client_process_message_string(), GLOBALS, map, and GlobalValueRegister::set().
Member Function Documentation
client_process_message_string()
void network::Client::client_process_message_string (std::string msg) [inline]
References network::ClientPacket::PlayerJoinInfo::all_clients, network::ClientPacket::Announcement, announcements, client_entities_DO_NOT_USE, network::ClientPacket::client_id, network::ClientPacket::PlayerJoinInfo::client_id, network::ClientPacket::PlayerLeaveInfo::client_id, client_items_DO_NOT_USE, client_p, Map::entities(), network::ClientPacket::PlayerInfo::facing_direction, network::ClientPacket::GameState, GLOBALS, network::ClientPacket::GameStateInfo::host_game_state, network::ClientPacket::GameStateInfo::host_menu_state, network::ClientPacket::PlayerJoinInfo::is_you, Map::items(), network::ClientPacket::PlayerInfo::location, log_info, log_warn, map, network::ClientPacket::Map, network::ClientPacket::MapInfo::map, network::ClientPacket::msg, network::ClientPacket::msg_type, network::ClientPacket::PlayerJoin, network::ClientPacket::PlayerLeave, network::ClientPacket::PlayerLocation, remote_players, GlobalValueRegister::set(), network::ClientPacket::PlayerJoinInfo::username, and network::ClientPacket::PlayerInfo::username.
Referenced by Client().
lock_in_ip()
void network::Client::lock_in_ip () [inline]
References client_p, conn_info, network::Client::ConnectionInfo::host_ip_address, and network::Client::ConnectionInfo::ip_set.
send_player_input_packet()
void network::Client::send_player_input_packet (int my_id) [inline]
References client_p, Entity::get(), GlobalValueRegister::get_ptr(), GLOBALS, and network::ClientPacket::PlayerControl.
Referenced by tick().
tick()
void network::Client::tick (float dt) [inline]
References announcements, client_p, next_tick, next_tick_reset, and send_player_input_packet().
update_username()
void network::Client::update_username (std::string new_name) [inline]
References client_p.
Member Data Documentation
announcements
std::vector<ClientPacket::AnnouncementInfo> network::Client::announcements
Referenced by client_process_message_string(), and tick().
client_p
std::shared_ptr<internal::Client> network::Client::client_p
Referenced by Client(), client_process_message_string(), lock_in_ip(), send_player_input_packet(), tick(), and update_username().
conn_info
struct network::Client::ConnectionInfo network::Client::conn_info
Referenced by lock_in_ip().
id
int network::Client::id = 0
map
std::shared_ptr<Map> network::Client::map
Referenced by Client(), and client_process_message_string().
next_tick
float network::Client::next_tick = 0.0f
Referenced by tick().
next_tick_reset
float network::Client::next_tick_reset = 0.02f
Referenced by tick().
remote_players
std::map<int, std::shared_ptr<RemotePlayer> > network::Client::remote_players
Referenced by client_process_message_string().
The documentation for this struct was generated from the following file:
src/network/client.h