SettingsLayer Struct Reference
#include <settingslayer.h>
Public Types
enum ActiveWindow { Root = 0
, KeyBindings = 1
 }
Public Member Functions
SettingsLayer ()
virtual ~SettingsLayer ()
bool onKeyPressed (KeyPressedEvent &event) override
bool onGamepadButtonPressed (GamepadButtonPressedEvent &event) override
void streamer_safe_box ()
void enable_post_processing ()
void master_volume ()
void music_volume ()
void resolution_switcher ()
void back_button ()
void draw_root_settings (float)
void draw_keybindings (float)
void draw_ui (float dt)
virtual void onUpdate (float) override
virtual void onDraw (float dt) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
void onEvent (Event &event)
virtual bool onKeyPressed (KeyPressedEvent &)
virtual bool onGamepadButtonPressed (GamepadButtonPressedEvent &)
virtual bool onGamepadAxisMoved (GamepadAxisMovedEvent &)
virtual bool onCharPressedEvent (CharPressedEvent &)
const std::string & getname () const
Public Attributes
enum SettingsLayer::ActiveWindow activeWindow = ActiveWindow::Root
Trie keyBindingTrie
std::array< std::pair< InputName, std::string_view >, magic_enum::enum_count< InputName >()> keyInputNames
std::vector< std::pair< InputName, AnyInputs > > keyInputValues
std::shared_ptr< ui::UIContext > ui_context
bool windowSizeDropdownState = false
int windowSizeDropdownIndex = 0
bool resolution_dropdown_open = false
int resolution_selected_index = 0
Public Attributes inherited from Layer
int id
std::string name
Member Enumeration Documentation
ActiveWindow
enum SettingsLayer::ActiveWindow
Enumerator
Root
KeyBindings
Constructor & Destructor Documentation
SettingsLayer()
SettingsLayer::SettingsLayer () [inline]
References Trie::add(), menu::Game, KeyMap::get_valid_inputs(), keyBindingTrie, keyInputNames, keyInputValues, resolution_selected_index, and ui_context.
 SettingsLayer()
virtual SettingsLayer::~SettingsLayer () [inline], [virtual]
Member Function Documentation
back_button()
void SettingsLayer::back_button () [inline]
References ui::button(), ui::components::mk_button(), ui::components::mk_padding(), MK_UUID, ui::padding(), ui::ROOT_ID, Size_Pct, and Size_Px.
Referenced by draw_root_settings().
draw_keybindings()
void SettingsLayer::draw_keybindings (float) [inline]
References ui::button(), menu::Game, KeyMap::get_valid_keys(), keyInputNames, ui::components::mk_button(), MK_UUID_LOOP, and ui::ROOT_ID.
Referenced by draw_ui().
draw_root_settings()
void SettingsLayer::draw_root_settings (float) [inline]
References back_button(), enable_post_processing(), master_volume(), ui::components::mk_padding(), music_volume(), ui::padding(), resolution_switcher(), Size_Px, and streamer_safe_box().
Referenced by draw_ui().
draw_ui()
void SettingsLayer::draw_ui (float dt) [inline]
References activeWindow, ui::Children, ui::Column, ui::div(), draw_keybindings(), draw_root_settings(), KeyBindings, ui::components::mk_padding(), ui::components::mk_root(), ui::padding(), Root, Size_Pct, Size_Px, ui_context, and WIN_HF().
Referenced by onDraw().
enable_post_processing()
void SettingsLayer::enable_post_processing () [inline]
References ui::checkbox(), ui::Children, ui::div(), ui::components::mk_text(), MK_UUID, ui::ROOT_ID, Size_Px, ui::text(), and ui_context.
Referenced by draw_root_settings().
master_volume()
void SettingsLayer::master_volume () [inline]
References ui::Children, ui::div(), ui::components::mk_padding(), ui::components::mk_text(), MK_UUID, ui::padding(), ui::ROOT_ID, Size_Px, ui::slider(), ui::text(), and ui_context.
Referenced by draw_root_settings().
music_volume()
void SettingsLayer::music_volume () [inline]
References ui::Children, ui::div(), ui::components::mk_padding(), ui::components::mk_text(), MK_UUID, ui::padding(), ui::ROOT_ID, Size_Px, ui::slider(), ui::text(), and ui_context.
Referenced by draw_root_settings().
onDraw()
virtual void SettingsLayer::onDraw (float dt) [inline], [override], [virtual]
Implements Layer.
References ext::clear_background(), draw_ui(), menu::Settings, and ui_context.
onGamepadButtonPressed()
bool SettingsLayer::onGamepadButtonPressed (GamepadButtonPressedEvent & event) [inline], [override], [virtual]
Reimplemented from Layer.
References menu::Settings, and ui_context.
onKeyPressed()
bool SettingsLayer::onKeyPressed (KeyPressedEvent & event) [inline], [override], [virtual]
Reimplemented from Layer.
References activeWindow, KeyEvent::keycode, Root, menu::Settings, and ui_context.
onUpdate()
virtual void SettingsLayer::onUpdate (float) [inline], [override], [virtual]
Implements Layer.
References menu::Settings.
resolution_switcher()
void SettingsLayer::resolution_switcher () [inline]
References ui::Children, ui::div(), ui::dropdown(), ui::components::mk_padding(), ui::components::mk_text(), ui::padding(), resolution_dropdown_open, resolution_selected_index, Size_Px, ui::text(), and ui_context.
Referenced by draw_root_settings().
streamer_safe_box()
void SettingsLayer::streamer_safe_box () [inline]
References ui::checkbox(), ui::Children, ui::div(), ui::components::mk_text(), MK_UUID, ui::ROOT_ID, Size_Px, ui::text(), and ui_context.
Referenced by draw_root_settings().
Member Data Documentation
activeWindow
enum SettingsLayer::ActiveWindow SettingsLayer::activeWindow = ActiveWindow::Root
Referenced by draw_ui(), and onKeyPressed().
keyBindingTrie
Trie SettingsLayer::keyBindingTrie
Referenced by SettingsLayer().
keyInputNames
std::array<std::pair<InputName, std::string_view>, magic_enum::enum_count<InputName>()> SettingsLayer::keyInputNames
Referenced by draw_keybindings(), and SettingsLayer().
keyInputValues
std::vector<std::pair<InputName, AnyInputs> > SettingsLayer::keyInputValues
Referenced by SettingsLayer().
resolution_dropdown_open
bool SettingsLayer::resolution_dropdown_open = false
Referenced by resolution_switcher().
resolution_selected_index
int SettingsLayer::resolution_selected_index = 0
Referenced by resolution_switcher(), and SettingsLayer().
ui_context
std::shared_ptr<ui::UIContext> SettingsLayer::ui_context
Referenced by draw_ui(), enable_post_processing(), master_volume(), music_volume(), onDraw(), onGamepadButtonPressed(), onKeyPressed(), resolution_switcher(), SettingsLayer(), and streamer_safe_box().
windowSizeDropdownIndex
int SettingsLayer::windowSizeDropdownIndex = 0
windowSizeDropdownState
bool SettingsLayer::windowSizeDropdownState = false
The documentation for this struct was generated from the following file:
src/layers/settingslayer.h