astar Namespace Reference
Classes
struct ScoreValue
Functions
float path_estimate (const vec2 &a, const vec2 &b)
float distance_between (const vec2 &a, const vec2 &b)
vec2 get_lowest_f (const std::set< vec2 > &set, std::map< vec2, ScoreValue > &fscore)
std::vector< vec2 > get_neighbors (vec2 start, std::function< bool(vec2 pos)> is_walkable)
std::deque< vec2 > reconstruct_path (std::deque< vec2 > path, std::map< vec2, vec2 > &parent_map, vec2 current)
std::deque< vec2 > find_path_impl (vec2 start, vec2 end, std::function< bool(vec2 pos)> is_walkable)
std::deque< vec2 > find_path (vec2 start, vec2 end, std::function< bool(vec2 pos)> is_walkable)
Function Documentation
distance_between()
float astar::distance_between (const vec2 & a, const vec2 & b) [inline]
References vec::distance().
Referenced by find_path_impl().
find_path()
std::deque< vec2 > astar::find_path (vec2 start, vec2 end, std::function< bool(vec2 pos)> is_walkable) [inline]
References find_path(), and find_path_impl().
Referenced by find_path(), test::p(), Job::travel_to_position(), and generation::helper::validate().
find_path_impl()
std::deque< vec2 > astar::find_path_impl (vec2 start, vec2 end, std::function< bool(vec2 pos)> is_walkable) [inline]
References vec::distance(), distance_between(), find_path_impl(), get_lowest_f(), get_neighbors(), log_warn, path_estimate(), reconstruct_path(), and TILESIZE.
Referenced by find_path(), and find_path_impl().
get_lowest_f()
vec2 astar::get_lowest_f (const std::set< vec2 > & set, std::map< vec2, ScoreValue > & fscore) [inline]
Referenced by find_path_impl().
get_neighbors()
std::vector< vec2 > astar::get_neighbors (vec2 start, std::function< bool(vec2 pos)> is_walkable) [inline]
References vec::forEachNeighbor(), and TILESIZE.
Referenced by find_path_impl(), and test::neighbors::test_all_neighbors().
path_estimate()
float astar::path_estimate (const vec2 & a, const vec2 & b) [inline]
References vec::distance().
Referenced by find_path_impl().
reconstruct_path()
std::deque< vec2 > astar::reconstruct_path (std::deque< vec2 > path, std::map< vec2, vec2 > & parent_map, vec2 current) [inline]
References reconstruct_path().
Referenced by find_path_impl(), and reconstruct_path().