network::internal::Client Struct Reference
#include <client.h>
Public Member Functions
Client ()
~Client ()
bool is_connected () const
bool is_not_connected () const
void set_process_message (std::function< void(std::string)> cb)
void set_address (SteamNetworkingIPAddr addy)
void set_address (std::string ip)
void startup ()
bool run ()
void send_string_to_server (std::string msg, Channel channel)
ClientPacket deserialize_to_packet (std::string msg)
void send_packet_to_server (ClientPacket packet)
void send_join_info_request ()
void send_leave_info_request ()
void on_steam_network_connection_status_changed (SteamNetConnectionStatusChangedCallback_t *info)
Static Public Member Functions
static void SteamNetConnectionStatusChangedCallback (SteamNetConnectionStatusChangedCallback_t *pInfo)
Public Attributes
SteamNetworkingIPAddr address
ISteamNetworkingSockets * interface = nullptr
HSteamNetConnection connection
bool running = false
std::string username
std::function< void(std::string)> process_message_cb
Static Public Attributes
static Client * callback_instance
Constructor & Destructor Documentation
Client()
network::internal::Client::Client () [inline]
 Client()
network::internal::Client::~Client () [inline]
References send_leave_info_request().
Member Function Documentation
deserialize_to_packet()
ClientPacket network::internal::Client::deserialize_to_packet (std::string msg) [inline]
is_connected()
bool network::internal::Client::is_connected () const [inline]
References connection.
Referenced by is_not_connected().
is_not_connected()
bool network::internal::Client::is_not_connected () const [inline]
References is_connected().
on_steam_network_connection_status_changed()
void network::internal::Client::on_steam_network_connection_status_changed (SteamNetConnectionStatusChangedCallback_t * info) [inline]
References connection, interface, log_info, log_warn, running, send_join_info_request(), send_leave_info_request(), and VALIDATE.
Referenced by SteamNetConnectionStatusChangedCallback().
run()
bool network::internal::Client::run () [inline]
References callback_instance, connection, interface, process_message_cb, running, and VALIDATE.
send_join_info_request()
void network::internal::Client::send_join_info_request () [inline]
References HASHED_VERSION, log_info, network::ClientPacket::PlayerJoin, send_packet_to_server(), and username.
Referenced by on_steam_network_connection_status_changed().
send_leave_info_request()
void network::internal::Client::send_leave_info_request () [inline]
References log_info, network::ClientPacket::PlayerLeave, and send_packet_to_server().
Referenced by on_steam_network_connection_status_changed(), and ~Client().
send_packet_to_server()
void network::internal::Client::send_packet_to_server (ClientPacket packet) [inline]
References network::ClientPacket::channel, and send_string_to_server().
Referenced by send_join_info_request(), and send_leave_info_request().
send_string_to_server()
void network::internal::Client::send_string_to_server (std::string msg, Channel channel) [inline]
References connection, and interface.
Referenced by send_packet_to_server().
set_address() [1/2]
void network::internal::Client::set_address (std::string ip) [inline]
References address, and network::DEFAULT_PORT.
set_address() [2/2]
void network::internal::Client::set_address (SteamNetworkingIPAddr addy) [inline]
References address.
set_process_message()
void network::internal::Client::set_process_message (std::function< void(std::string)> cb) [inline]
References process_message_cb.
startup()
void network::internal::Client::startup () [inline]
[connection int32] Upper limit of buffered pending bytes to be sent, if this is reached SendMessage will return k_EResultLimitExceeded Default is 512k (524288 bytes)
[connection int32] Timeout value (in ms) to use after connection is established
References address, connection, interface, log_info, log_warn, running, and SteamNetConnectionStatusChangedCallback().
SteamNetConnectionStatusChangedCallback()
static void network::internal::Client::SteamNetConnectionStatusChangedCallback (SteamNetConnectionStatusChangedCallback_t * pInfo) [inline], [static]
References callback_instance, log_warn, and on_steam_network_connection_status_changed().
Referenced by startup().
Member Data Documentation
address
SteamNetworkingIPAddr network::internal::Client::address
Referenced by set_address(), and startup().
callback_instance
Client* network::internal::Client::callback_instance [inline], [static]
Referenced by run(), and SteamNetConnectionStatusChangedCallback().
connection
HSteamNetConnection network::internal::Client::connection
Referenced by is_connected(), on_steam_network_connection_status_changed(), run(), send_string_to_server(), and startup().
interface
ISteamNetworkingSockets* network::internal::Client::interface = nullptr
Referenced by on_steam_network_connection_status_changed(), run(), send_string_to_server(), and startup().
process_message_cb
std::function<void(std::string)> network::internal::Client::process_message_cb
Referenced by run(), and set_process_message().
running
bool network::internal::Client::running = false
Referenced by on_steam_network_connection_status_changed(), run(), and startup().
username
std::string network::internal::Client::username
Referenced by send_join_info_request().
The documentation for this struct was generated from the following file:
src/network/internal/client.h