GameLayer Struct Reference
#include <gamelayer.h>
Public Member Functions
GameLayer ()
virtual ~GameLayer ()
bool onGamepadAxisMoved (GamepadAxisMovedEvent &) override
bool onGamepadButtonPressed (GamepadButtonPressedEvent &event) override
bool onKeyPressed (KeyPressedEvent &event) override
void play_music ()
virtual void onUpdate (float dt) override
virtual void onDraw (float dt) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
void onEvent (Event &event)
virtual bool onKeyPressed (KeyPressedEvent &)
virtual bool onGamepadButtonPressed (GamepadButtonPressedEvent &)
virtual bool onGamepadAxisMoved (GamepadAxisMovedEvent &)
virtual bool onCharPressedEvent (CharPressedEvent &)
const std::string & getname () const
Public Attributes
std::shared_ptr< Entity > active_player
std::shared_ptr< GameCam > cam
raylib::Model bag_model
Public Attributes inherited from Layer
int id
std::string name
Constructor & Destructor Documentation
GameLayer()
GameLayer::GameLayer () [inline]
References cam, GLOBALS, and GlobalValueRegister::set().
 GameLayer()
virtual GameLayer::~GameLayer () [inline], [virtual]
Member Function Documentation
onDraw()
virtual void GameLayer::onDraw (float dt) [inline], [override], [virtual]
Implements Layer.
References ext::clear_background(), GlobalValueRegister::get_or_default(), GlobalValueRegister::get_ptr(), global_player, GLOBALS, MenuState::s_in_game(), TILESIZE, and TRACY_ZONE_SCOPED.
onGamepadAxisMoved()
bool GameLayer::onGamepadAxisMoved (GamepadAxisMovedEvent &) [inline], [override], [virtual]
Reimplemented from Layer.
onGamepadButtonPressed()
bool GameLayer::onGamepadButtonPressed (GamepadButtonPressedEvent & event) [inline], [override], [virtual]
Reimplemented from Layer.
References GamepadButtonPressedEvent::button, menu::Game, KeyMap::get_button(), MenuState::s_in_game(), and GameState::s_pause().
onKeyPressed()
bool GameLayer::onKeyPressed (KeyPressedEvent & event) [inline], [override], [virtual]
Reimplemented from Layer.
References menu::Game, KeyMap::get_key_code(), KeyEvent::keycode, MenuState::s_in_game(), and GameState::s_pause().
onUpdate()
virtual void GameLayer::onUpdate (float dt) [inline], [override], [virtual]
Implements Layer.
References cam, GlobalValueRegister::get_ptr(), global_player, GLOBALS, Map::grab_things(), play_music(), Transform::pos(), MenuState::s_in_game(), GameState::s_should_update(), and TRACY_ZONE_SCOPED.
play_music()
void GameLayer::play_music () [inline]
References ENABLE_SOUND, and MusicLibrary::get().
Referenced by onUpdate().
Member Data Documentation
active_player
std::shared_ptr<Entity> GameLayer::active_player
bag_model
raylib::Model GameLayer::bag_model
cam
std::shared_ptr<GameCam> GameLayer::cam
Referenced by GameLayer(), and onUpdate().
The documentation for this struct was generated from the following file:
src/layers/gamelayer.h