src/entity.h File Reference
#include `components/base_component.h`
#include `components/can_be_ghost_player.h`
#include `components/can_be_held.h`
#include `components/can_be_highlighted.h`
#include `components/can_be_pushed.h`
#include `components/can_be_taken_from.h`
#include `components/can_grab_from_other_furniture.h`
#include `components/can_have_ailment.h`
#include `components/can_highlight_others.h`
#include `components/can_hold_furniture.h`
#include `components/can_hold_item.h`
#include `components/can_perform_job.h`
#include `components/collects_user_input.h`
#include `components/conveys_held_item.h`
#include `components/custom_item_position.h`
#include `components/debug_name.h`
#include `components/has_base_speed.h`
#include `components/has_client_id.h`
#include `components/has_dynamic_model_name.h`
#include `components/has_name.h`
#include `components/has_speech_bubble.h`
#include `components/has_timer.h`
#include `components/has_waiting_queue.h`
#include `components/has_work.h`
#include `components/indexer.h`
#include `components/is_item_container.h`
#include `components/is_rotatable.h`
#include `components/is_snappable.h`
#include `components/is_solid.h`
#include `components/is_spawner.h`
#include `components/is_trigger_area.h`
#include `components/model_renderer.h`
#include `components/responds_to_user_input.h`
#include `components/shows_progress_bar.h`
#include `components/simple_colored_box_renderer.h`
#include `components/transform.h`
#include `components/uses_character_model.h`
#include `engine/assert.h`
#include `external_include.h`
#include <bitsery/ext/pointer.h>
#include <bitsery/ext/std_map.h>
#include <array>
#include <map>
#include `dataclass/names.h`
#include `drawing_util.h`
#include `engine/astar.h`
#include `engine/is_server.h`
#include `engine/model_library.h`
#include `engine/util.h`
#include `globals.h`
#include `item.h`
#include `item_helper.h`
#include `preload.h`
#include `raylib.h`
#include `text_util.h`
#include `vec_util.h`
Classes
struct Entity
struct DebugOptions
Namespaces
namespace bitsery
namespace entities
Typedefs
using StdMap = bitsery::ext::StdMap
typedef Transform::Transform::FrontFaceDirection EntityDir
typedef Entity Furniture
Functions
template<typename S >
void bitsery::serialize (S &s, std::shared_ptr< Entity > &entity)
static void register_all_components ()
static void add_entity_components (Entity *entity)
static Entity * make_entity (const DebugOptions &options, vec3 p={-2, -2, -2})
static void add_person_components (Entity *person)
static void add_player_components (Entity *player)
static Entity * make_remote_player (vec3 pos)
static void update_player_remotely (std::shared_ptr< Entity > entity, float *location, std::string username, int facing_direction)
static void update_player_rare_remotely (std::shared_ptr< Entity > entity, int model_index)
static Entity * make_player (vec3 p)
static Entity * make_aiperson (const DebugOptions &options, vec3 p)
static Entity * make_customer (vec2 p, bool has_ailment=true)
static Entity * entities::make_furniture (const DebugOptions &options, vec2 pos, Color face, Color base, bool is_static=false)
static Entity * entities::make_table (vec2 pos)
static Entity * entities::make_character_switcher (vec2 pos)
static Entity * entities::make_wall (vec2 pos, Color c=ui::color::brown)
static Entity * entities::make_conveyer (vec2 pos)
static Entity * entities::make_grabber (vec2 pos)
static Entity * entities::make_register (vec2 pos)
template<typename I >
static Entity * entities::make_itemcontainer (vec2 pos)
static Entity * entities::make_bagbox (vec2 pos)
static Entity * entities::make_medicine_cabinet (vec2 pos)
static Entity * entities::make_pill_dispenser (vec2 pos)
static Entity * entities::make_trigger_area (vec3 pos, float width, float height, std::string title=`DEFAULT TRIGGER`)
static Entity * entities::make_customer_spawner (vec3 pos)
static Entity * entities::make_sophie (vec3 pos)
Variables
static std::atomic_int ENTITY_ID_GEN = 0
Typedef Documentation
EntityDir
typedef Transform::Transform::FrontFaceDirection EntityDir
Furniture
typedef Entity Furniture
StdMap
using StdMap = bitsery::ext::StdMap
Function Documentation
add_entity_components()
static void add_entity_components (Entity * entity) [static]
References Entity::addComponent().
add_person_components()
static void add_person_components (Entity * person) [static]
References Entity::addComponent(), ENABLE_MODELS, Entity::get(), ModelInfo::model_name, and TILESIZE.
Referenced by make_aiperson(), make_player(), and make_remote_player().
add_player_components()
static void add_player_components (Entity * player) [static]
References Entity::addComponent(), and Entity::get().
Referenced by make_player(), and make_remote_player().
make_aiperson()
static Entity * make_aiperson (const DebugOptions & options, vec3 p) [static]
References add_person_components(), Entity::addComponent(), make_entity(), and Wandering.
Referenced by make_customer().
make_customer()
static Entity * make_customer (vec2 p, bool has_ailment = true) [static]
References Entity::addComponent(), Entity::get(), get_random_name(), make_aiperson(), Ailment::make_insomnia(), DebugOptions::name, vec::to3(), WaitInQueue, and Wandering.
Referenced by generation::helper::generate_entity_from_character(), and entities::make_customer_spawner().
make_entity()
static Entity * make_entity (const DebugOptions & options, vec3 p = {-2, -2, -2}) [static]
Referenced by generation::helper::generate_entity_from_character(), make_aiperson(), entities::make_customer_spawner(), entities::make_furniture(), make_player(), make_remote_player(), entities::make_sophie(), entities::make_trigger_area(), and mk_entity().
make_player()
static Entity * make_player (vec3 p) [static]
References add_person_components(), add_player_components(), Entity::addComponent(), and make_entity().
Referenced by network::Server::process_player_join_packet().
make_remote_player()
static Entity * make_remote_player (vec3 pos) [static]
References add_person_components(), add_player_components(), and make_entity().
Referenced by network::Client::client_process_message_string().
register_all_components()
static void register_all_components () [static]
References Entity::addAll().
Referenced by main().
update_player_rare_remotely()
static void update_player_rare_remotely (std::shared_ptr< Entity > entity, int model_index) [static]
References UsesCharacterModel::fetch_model_name(), ModelInfo::model_name, and UsesCharacterModel::update_index_CLIENT_ONLY().
Referenced by network::Client::client_process_message_string().
update_player_remotely()
static void update_player_remotely (std::shared_ptr< Entity > entity, float * location, std::string username, int facing_direction) [static]
References Transform::update(), and Transform::update_face_direction().
Referenced by network::Client::client_process_message_string().
Variable Documentation
ENTITY_ID_GEN
std::atomic_int ENTITY_ID_GEN = 0 [static]