BasePauseLayer Struct Reference
#include <pauselayer.h>
Public Member Functions
BasePauseLayer (const char *name, game::State e_state)
virtual ~BasePauseLayer ()
virtual void onEvent (Event &event) override
bool onGamepadButtonPressed (GamepadButtonPressedEvent &event)
bool onKeyPressed (KeyPressedEvent &event)
virtual void onUpdate (float) override
virtual void onDraw (float dt) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
virtual void onEvent (Event &)=0
const std::string & getname () const
Public Attributes
std::shared_ptr< ui::UIContext > ui_context
game::State enabled_state
Public Attributes inherited from Layer
int id
std::string name
Constructor & Destructor Documentation
BasePauseLayer()
BasePauseLayer::BasePauseLayer (const char * name, game::State e_state) [inline]
References ui_context.
 BasePauseLayer()
virtual BasePauseLayer::~BasePauseLayer () [inline], [virtual]
Member Function Documentation
onDraw()
virtual void BasePauseLayer::onDraw (float dt) [inline], [override], [virtual]
Implements Layer.
References ui::button(), ui::Children, ui::Column, ui::div(), enabled_state, ui::components::mk_button(), MK_UUID, ui::padding(), ui::ROOT_ID, MenuState::s_in_game(), menu::Settings, Size_Pct, Size_Px, ui_context, WIN_HF(), and WIN_WF().
onEvent()
virtual void BasePauseLayer::onEvent (Event & event) [inline], [override], [virtual]
Implements Layer.
References EventDispatcher::dispatch(), enabled_state, onGamepadButtonPressed(), and onKeyPressed().
onGamepadButtonPressed()
bool BasePauseLayer::onGamepadButtonPressed (GamepadButtonPressedEvent & event) [inline]
References GamepadButtonPressedEvent::button, menu::Game, KeyMap::get_button(), and ui_context.
Referenced by onEvent().
onKeyPressed()
bool BasePauseLayer::onKeyPressed (KeyPressedEvent & event) [inline]
References menu::Game, KeyMap::get_key_code(), KeyEvent::keycode, and ui_context.
Referenced by onEvent().
onUpdate()
virtual void BasePauseLayer::onUpdate (float) [inline], [override], [virtual]
Implements Layer.
Member Data Documentation
enabled_state
game::State BasePauseLayer::enabled_state
Referenced by onDraw(), and onEvent().
ui_context
std::shared_ptr<ui::UIContext> BasePauseLayer::ui_context
Referenced by BasePauseLayer(), onDraw(), onGamepadButtonPressed(), and onKeyPressed().
The documentation for this struct was generated from the following file:
src/pauselayer.h