ItemHelper Struct Reference
#include <item_helper.h>
Public Types
enum ForEachFlow { NormalFlow = 0
, Continue = 1
, Break = 2
 }
Static Public Member Functions
static Items & get_items ()
static void addItem (std::shared_ptr< Item > e)
static void removeItem (std::shared_ptr< Item > e)
static void cleanup ()
static void forEachItem (std::function< ForEachFlow(std::shared_ptr< Item >)> cb)
template<typename T >
static constexpr std::vector< std::shared_ptr< T > > getitemsInRange (vec2 pos, float range)
template<typename T >
static constexpr std::shared_ptr< T > getClosestMatchingItem (vec2 pos, float range, std::function< bool(std::shared_ptr< T >)> filter={})
Member Enumeration Documentation
ForEachFlow
enum ItemHelper::ForEachFlow
Enumerator
NormalFlow
Continue
Break
Member Function Documentation
addItem()
static void ItemHelper::addItem (std::shared_ptr< Item > e) [inline], [static]
References get_items().
Referenced by system_manager::backfill_empty_container().
cleanup()
static void ItemHelper::cleanup () [inline], [static]
References get_items().
forEachItem()
static void ItemHelper::forEachItem (std::function< ForEachFlow(std::shared_ptr< Item >)> cb) [inline], [static]
References get_items().
get_items()
static Items & ItemHelper::get_items () [inline], [static]
References client_items_DO_NOT_USE, client_lobby_items_DO_NOT_USE, is_server(), game::Lobby, server_items_DO_NOT_USE, and server_lobby_items_DO_NOT_USE.
Referenced by addItem(), cleanup(), forEachItem(), getitemsInRange(), LevelInfo::grab_things(), and removeItem().
getClosestMatchingItem()
template<typename T >
static constexpr std::shared_ptr< T > ItemHelper::getClosestMatchingItem (vec2 pos, float range, std::function< bool(std::shared_ptr< T >)> filter = {}) [inline], [static], [constexpr]
getitemsInRange()
template<typename T >
static constexpr std::vector< std::shared_ptr< T > > ItemHelper::getitemsInRange (vec2 pos, float range) [inline], [static], [constexpr]
References vec::distance(), get_items(), and vec::to2().
removeItem()
static void ItemHelper::removeItem (std::shared_ptr< Item > e) [inline], [static]
References get_items().
The documentation for this struct was generated from the following file:
src/item_helper.h