HasTimer Struct Reference
#include <has_timer.h>
Public Types
enum Renderer { Round
 }
enum WaitingReason { None
, CustomersInStore
, HoldingFurniture
, WaitingReasonLast
 }
Public Member Functions
virtual ~HasTimer ()
HasTimer ()
HasTimer (Renderer _type, float t)
auto & pass_time (float dt)
float pct () const
std::string text_reason (WaitingReason wr)
std::string text_reason (int i)
bool read_reason (WaitingReason wr) const
bool read_reason (int i) const
void write_reason (WaitingReason wr, bool value)
bool store_is_closed () const
void on_complete (float dt)
void reset_if_complete (float dt)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Public Attributes
enum HasTimer::Renderer type
float currentRoundTime
float totalRoundTime
float roundSwitchCountdownReset = 5.f
float roundSwitchCountdown = 5.f
enum HasTimer::WaitingReason waiting_reason = None
std::bitset< WaitingReason::WaitingReasonLast > block_state_change_reasons
Private Member Functions
template<typename S >
void serialize (S &s)
Member Enumeration Documentation
Renderer
enum HasTimer::Renderer
Enumerator
Round
WaitingReason
enum HasTimer::WaitingReason
Enumerator
None
CustomersInStore
HoldingFurniture
WaitingReasonLast
Constructor & Destructor Documentation
 HasTimer()
virtual HasTimer::~HasTimer () [inline], [virtual]
HasTimer() [1/2]
HasTimer::HasTimer () [inline]
HasTimer() [2/2]
HasTimer::HasTimer (Renderer _type, float t) [inline], [explicit]
References currentRoundTime, totalRoundTime, and type.
Member Function Documentation
on_complete()
void HasTimer::on_complete (float dt) [inline]
References currentRoundTime, CustomersInStore, HoldingFurniture, game::InRound, log_warn, game::Planning, read_reason(), roundSwitchCountdown, roundSwitchCountdownReset, and totalRoundTime.
Referenced by reset_if_complete().
pass_time()
auto & HasTimer::pass_time (float dt) [inline]
References currentRoundTime.
pct()
float HasTimer::pct () const [inline]
References currentRoundTime, and totalRoundTime.
read_reason() [1/2]
bool HasTimer::read_reason (int i) const [inline]
References block_state_change_reasons.
read_reason() [2/2]
bool HasTimer::read_reason (WaitingReason wr) const [inline]
References read_reason().
Referenced by on_complete(), and read_reason().
reset_if_complete()
void HasTimer::reset_if_complete (float dt) [inline]
References currentRoundTime, and on_complete().
Referenced by system_manager::run_timer().
serialize()
template<typename S >
void HasTimer::serialize (S & s) [inline], [private]
References block_state_change_reasons, currentRoundTime, roundSwitchCountdown, roundSwitchCountdownReset, totalRoundTime, and type.
store_is_closed()
bool HasTimer::store_is_closed () const [inline]
References currentRoundTime, and GameState::s_in_round().
Referenced by system_manager::job_system::ensure_has_job().
text_reason() [1/2]
std::string HasTimer::text_reason (int i) [inline]
References text_reason().
text_reason() [2/2]
std::string HasTimer::text_reason (WaitingReason wr) [inline]
References CustomersInStore, HoldingFurniture, None, and WaitingReasonLast.
Referenced by text_reason().
write_reason()
void HasTimer::write_reason (WaitingReason wr, bool value) [inline]
References block_state_change_reasons, roundSwitchCountdown, and roundSwitchCountdownReset.
Member Data Documentation
block_state_change_reasons
std::bitset<WaitingReason::WaitingReasonLast> HasTimer::block_state_change_reasons
Referenced by read_reason(), serialize(), and write_reason().
currentRoundTime
float HasTimer::currentRoundTime
Referenced by HasTimer(), on_complete(), pass_time(), pct(), reset_if_complete(), serialize(), and store_is_closed().
roundSwitchCountdown
float HasTimer::roundSwitchCountdown = 5.f
Referenced by on_complete(), serialize(), and write_reason().
roundSwitchCountdownReset
float HasTimer::roundSwitchCountdownReset = 5.f
Referenced by on_complete(), serialize(), and write_reason().
totalRoundTime
float HasTimer::totalRoundTime
Referenced by HasTimer(), on_complete(), pct(), and serialize().
type
enum HasTimer::Renderer HasTimer::type
Referenced by HasTimer(), and serialize().
waiting_reason
enum HasTimer::WaitingReason HasTimer::waiting_reason = None
The documentation for this struct was generated from the following file:
src/components/has_timer.h