system_manager::input_process_manager Namespace Reference
Namespaces
namespace inround
namespace planning
Functions
void collect_user_input (std::shared_ptr< Entity > entity, float dt)
void process_player_movement_input (std::shared_ptr< Entity > entity, float dt, InputName input_name, float input_amount)
void process_input (const std::shared_ptr< Entity > entity, const UserInput &input)
Function Documentation
collect_user_input()
void system_manager::input_process_manager::collect_user_input (std::shared_ptr< Entity > entity, float dt) [inline]
References util::clamp(), menu::Game, GlobalValueRegister::get_ptr(), GLOBALS, KeyMap::is_event(), KeyMap::is_event_once_DO_NOT_USE(), log_warn, CollectsUserInput::publish(), util::rad2deg(), and CollectsUserInput::write().
Referenced by SystemManager::always_update().
process_input()
void system_manager::input_process_manager::process_input (const std::shared_ptr< Entity > entity, const UserInput & input) [inline]
References system_manager::input_process_manager::planning::handle_grab_or_drop(), system_manager::input_process_manager::inround::handle_grab_or_drop(), game::Planning, process_player_movement_input(), system_manager::input_process_manager::planning::rotate_furniture(), GameState::s_in_round(), and system_manager::input_process_manager::inround::work_furniture().
Referenced by SystemManager::process_inputs().
process_player_movement_input()
void system_manager::input_process_manager::process_player_movement_input (std::shared_ptr< Entity > entity, float dt, InputName input_name, float input_amount) [inline]
References system_manager::person_update_given_new_pos(), Transform::pos(), HasBaseSpeed::speed(), and Transform::trunc().
Referenced by process_input().