DebugName Struct Reference
#include <debug_name.h>
Public Member Functions
virtual ~DebugName ()
void update (const std::string &new_name)
const std::string & name () const
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
int name_length = 1
std::string _name = ``
Constructor & Destructor Documentation
 DebugName()
virtual DebugName::~DebugName () [inline], [virtual]
Member Function Documentation
name()
const std::string & DebugName::name () const [inline]
References _name.
Referenced by HasWaitingQueue::add_customer(), SystemManager::always_update(), system_manager::count_max_trigger_area_entrants(), system_manager::count_trigger_area_entrants(), EntityHelper::getAllWithName(), and system_manager::process_grabber_items().
serialize()
template<typename S >
void DebugName::serialize (S & s) [inline], [private]
References _name, and name_length.
update()
void DebugName::update (const std::string & new_name) [inline]
References _name, and name_length.
Member Data Documentation
_name
std::string DebugName::_name = `` [private]
Referenced by name(), serialize(), and update().
name_length
int DebugName::name_length = 1 [private]
Referenced by serialize(), and update().
The documentation for this struct was generated from the following file:
src/components/debug_name.h