system_manager Namespace Reference
probably needed by map and not included in there
Namespaces
namespace input_process_manager
namespace job_system
namespace logging_manager
namespace render_manager
namespace ui
Functions
void person_update_given_new_pos (int id, Transform &transform, std::shared_ptr< Entity > person, float, vec3 new_pos_x, vec3 new_pos_z)
void transform_snapper (std::shared_ptr< Entity > entity, float)
void update_held_furniture_position (std::shared_ptr< Entity > entity, float)
void update_held_item_position (std::shared_ptr< Entity > entity, float)
void reset_highlighted (std::shared_ptr< Entity > entity, float)
void highlight_facing_furniture (std::shared_ptr< Entity > entity, float)
void move_entity_based_on_push_force (std::shared_ptr< Entity > entity, float, vec3 &new_pos_x, vec3 &new_pos_z)
void process_conveyer_items (std::shared_ptr< Entity > entity, float dt)
void process_grabber_items (std::shared_ptr< Entity > entity, float)
template<typename I , typename... TArgs>
void backfill_empty_container (std::shared_ptr< Entity > &entity, TArgs &&... args)
void process_is_container_and_should_backfill_item (std::shared_ptr< Entity > entity, float)
void process_is_container_and_should_update_item (std::shared_ptr< Entity > entity, float)
void handle_autodrop_furniture_when_exiting_planning (const std::shared_ptr< Entity > &entity)
void delete_held_items_when_leaving_inround (const std::shared_ptr< Entity > &entity)
void refetch_dynamic_model_names (const std::shared_ptr< Entity > &entity, float)
void count_max_trigger_area_entrants (const std::shared_ptr< Entity > &entity, float)
void count_trigger_area_entrants (const std::shared_ptr< Entity > &entity, float)
void update_trigger_area_percent (const std::shared_ptr< Entity > &entity, float dt)
void trigger_cb_on_full_progress (const std::shared_ptr< Entity > &entity, float)
void process_trigger_area (const std::shared_ptr< Entity > &entity, float dt)
void process_spawner (const std::shared_ptr< Entity > &entity, float dt)
void run_timer (const std::shared_ptr< Entity > &entity, float dt)
void sophie (const std::shared_ptr< Entity > &entity, float)
template<typename I >
void backfill_empty_container (std::shared_ptr< Entity > entity)
Detailed Description
probably needed by map and not included in there
Function Documentation
backfill_empty_container() [1/2]
template<typename I , typename... TArgs>
void system_manager::backfill_empty_container (std::shared_ptr< Entity > & entity, TArgs &&... args)
References ItemHelper::addItem(), Item::FURNITURE, CanHoldItem::item(), and CanHoldItem::update().
backfill_empty_container() [2/2]
template<typename I >
void system_manager::backfill_empty_container (std::shared_ptr< Entity > entity)
count_max_trigger_area_entrants()
void system_manager::count_max_trigger_area_entrants (const std::shared_ptr< Entity > & entity, float)
References DebugName::name().
Referenced by process_trigger_area().
count_trigger_area_entrants()
void system_manager::count_trigger_area_entrants (const std::shared_ptr< Entity > & entity, float)
References Transform::bounds(), Transform::expanded_bounds(), and DebugName::name().
Referenced by process_trigger_area().
delete_held_items_when_leaving_inround()
void system_manager::delete_held_items_when_leaving_inround (const std::shared_ptr< Entity > & entity)
References CanHoldItem::empty(), CanHoldItem::item(), and CanHoldItem::update().
Referenced by SystemManager::process_state_change().
handle_autodrop_furniture_when_exiting_planning()
void system_manager::handle_autodrop_furniture_when_exiting_planning (const std::shared_ptr< Entity > & entity)
References system_manager::input_process_manager::planning::drop_held_furniture(), and CanHoldFurniture::empty().
Referenced by SystemManager::process_state_change().
highlight_facing_furniture()
void system_manager::highlight_facing_furniture (std::shared_ptr< Entity > entity, float)
References EntityHelper::getClosestMatchingFurniture(), and CanHighlightOthers::reach().
Referenced by SystemManager::always_update().
move_entity_based_on_push_force()
void system_manager::move_entity_based_on_push_force (std::shared_ptr< Entity > entity, float , vec3 & new_pos_x, vec3 & new_pos_z)
References CanBePushed::pushed_force(), CanBePushed::update_x(), and CanBePushed::update_z().
person_update_given_new_pos()
void system_manager::person_update_given_new_pos (int id, Transform & transform, std::shared_ptr< Entity > person, float , vec3 new_pos_x, vec3 new_pos_z) [inline]
References Transform::BACK, EntityHelper::Break, EntityHelper::Continue, EntityHelper::forEachEntity(), Transform::FORWARD, get_bounds(), GlobalValueRegister::get_or_default(), GLOBALS, is_collidable(), Transform::LEFT, EntityHelper::NormalFlow, CanBePushed::pushed_force(), randSign(), Transform::raw(), Transform::RIGHT, Transform::size(), TILESIZE, CanBePushed::update(), Transform::update_face_direction(), Transform::update_x(), and Transform::update_z().
Referenced by system_manager::input_process_manager::process_player_movement_input().
process_conveyer_items()
void system_manager::process_conveyer_items (std::shared_ptr< Entity > entity, float dt)
References CanHoldItem::empty(), Item::FURNITURE, EntityHelper::getClosestMatchingFurniture(), CanHoldItem::item(), ConveysHeldItem::ITEM_END, ConveysHeldItem::ITEM_START, ConveysHeldItem::relative_item_pos, and CanHoldItem::update().
Referenced by SystemManager::in_round_update().
process_grabber_items()
void system_manager::process_grabber_items (std::shared_ptr< Entity > entity, float)
References Transform::as2(), Transform::face_direction(), Item::FURNITURE, CanHoldItem::is_holding_item(), CanHoldItem::item(), ConveysHeldItem::ITEM_START, log_warn, DebugName::name(), Transform::offsetFaceDirection(), ConveysHeldItem::relative_item_pos, and CanHoldItem::update().
Referenced by SystemManager::in_round_update().
process_is_container_and_should_backfill_item()
void system_manager::process_is_container_and_should_backfill_item (std::shared_ptr< Entity > entity, float)
References CanHoldItem::is_holding_item(), and Indexer::value().
Referenced by SystemManager::in_round_update().
process_is_container_and_should_update_item()
void system_manager::process_is_container_and_should_update_item (std::shared_ptr< Entity > entity, float)
References CanHoldItem::is_holding_item(), CanHoldItem::item(), and CanHoldItem::update().
Referenced by SystemManager::in_round_update().
process_spawner()
void system_manager::process_spawner (const std::shared_ptr< Entity > & entity, float dt)
References EntityHelper::addEntity(), and Entity::get().
Referenced by SystemManager::in_round_update().
process_trigger_area()
void system_manager::process_trigger_area (const std::shared_ptr< Entity > & entity, float dt)
References count_max_trigger_area_entrants(), count_trigger_area_entrants(), trigger_cb_on_full_progress(), and update_trigger_area_percent().
Referenced by SystemManager::always_update().
refetch_dynamic_model_names()
void system_manager::refetch_dynamic_model_names (const std::shared_ptr< Entity > & entity, float)
References HasDynamicModelName::fetch(), and ModelRenderer::update_model_name().
Referenced by SystemManager::process_state_change().
reset_highlighted()
void system_manager::reset_highlighted (std::shared_ptr< Entity > entity, float)
References CanBeHighlighted::update().
Referenced by SystemManager::always_update().
run_timer()
void system_manager::run_timer (const std::shared_ptr< Entity > & entity, float dt)
References HasTimer::reset_if_complete().
Referenced by SystemManager::always_update().
sophie()
void system_manager::sophie (const std::shared_ptr< Entity > & entity, float)
References Transform::as2(), HasTimer::CustomersInStore, vec::distance(), GATHER_SPOT, EntityHelper::getAllWithName(), HasTimer::HoldingFurniture, CanHoldFurniture::is_holding_furniture(), and TILESIZE.
Referenced by SystemManager::always_update(), and system_manager::job_system::ensure_has_job().
transform_snapper()
void system_manager::transform_snapper (std::shared_ptr< Entity > entity, float)
References Transform::raw(), Transform::snap_position(), and Transform::update().
Referenced by SystemManager::always_update().
trigger_cb_on_full_progress()
void system_manager::trigger_cb_on_full_progress (const std::shared_ptr< Entity > & entity, float)
References IsTriggerArea::get_complete_fn(), and IsTriggerArea::progress().
Referenced by process_trigger_area().
update_held_furniture_position()
void system_manager::update_held_furniture_position (std::shared_ptr< Entity > entity, float)
References Transform::BACK, Transform::face_direction(), Transform::FORWARD, Transform::LEFT, Transform::pos(), Transform::RIGHT, and TILESIZE.
Referenced by SystemManager::planning_update().
update_held_item_position()
void system_manager::update_held_item_position (std::shared_ptr< Entity > entity, float)
References Transform::BACK, CustomHeldItemPosition::Conveyer, CustomHeldItemPosition::Default, CanHoldItem::empty(), Transform::face_direction(), Transform::FORWARD, CanHoldItem::item(), Transform::LEFT, log_warn, Transform::pos(), CustomHeldItemPosition::positioner, ConveysHeldItem::relative_item_pos, Transform::RIGHT, CustomHeldItemPosition::Table, and TILESIZE.
Referenced by SystemManager::always_update().
update_trigger_area_percent()
void system_manager::update_trigger_area_percent (const std::shared_ptr< Entity > & entity, float dt)
References IsTriggerArea::decrease_progress(), IsTriggerArea::increase_progress(), and IsTriggerArea::should_wave().
Referenced by process_trigger_area().