now Namespace Reference
Functions
long current_ms ()
Function Documentation
current_ms()
long now::current_ms () [inline]
Referenced by network::Client::client_process_message_string(), network::Server::process_ping_message(), system_manager::render_manager::render_trigger_area(), and network::Client::send_ping_packet().