HasWork Struct Reference
#include <has_work.h>
Public Member Functions
HasWork ()
virtual ~HasWork ()
bool is_work_complete () const
bool has_work () const
bool doesnt_have_work () const
bool can_show_progress_bar () const
bool dont_show_progres_bar () const
void increase_pct (float amt)
void update_pct (float pct)
void set_has_more_work ()
void reset_pct ()
int scale_length (int length)
void init (std::function< void(std::shared_ptr< Entity > owner, HasWork &, std::shared_ptr< Entity > person, float dt)> worker)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Public Attributes
std::function< void(std::shared_ptr< Entity > owner, HasWork &, std::shared_ptr< Entity > person, float dt)> do_work
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
float pct_work_complete
bool more_to_do
Constructor & Destructor Documentation
HasWork()
HasWork::HasWork () [inline]
 HasWork()
virtual HasWork::~HasWork () [inline], [virtual]
Member Function Documentation
can_show_progress_bar()
bool HasWork::can_show_progress_bar () const [inline]
References has_work(), and pct_work_complete.
Referenced by dont_show_progres_bar().
doesnt_have_work()
bool HasWork::doesnt_have_work () const [inline]
References has_work().
dont_show_progres_bar()
bool HasWork::dont_show_progres_bar () const [inline]
References can_show_progress_bar().
Referenced by system_manager::render_manager::render_progress_bar().
has_work()
bool HasWork::has_work () const [inline]
References more_to_do.
Referenced by can_show_progress_bar(), and doesnt_have_work().
increase_pct()
void HasWork::increase_pct (float amt) [inline]
References pct_work_complete.
Referenced by entities::make_character_switcher(), entities::make_pill_dispenser(), and entities::make_table().
init()
void HasWork::init (std::function< void(std::shared_ptr< Entity > owner, HasWork &, std::shared_ptr< Entity > person, float dt)> worker) [inline]
References do_work.
is_work_complete()
bool HasWork::is_work_complete () const [inline]
References pct_work_complete.
Referenced by entities::make_character_switcher(), entities::make_pill_dispenser(), and entities::make_table().
reset_pct()
void HasWork::reset_pct () [inline]
References pct_work_complete.
Referenced by entities::make_character_switcher(), entities::make_pill_dispenser(), and entities::make_table().
scale_length()
int HasWork::scale_length (int length) [inline]
References pct_work_complete.
Referenced by system_manager::render_manager::render_progress_bar().
serialize()
template<typename S >
void HasWork::serialize (S & s) [inline], [private]
References more_to_do, and pct_work_complete.
set_has_more_work()
void HasWork::set_has_more_work () [inline]
References more_to_do.
update_pct()
void HasWork::update_pct (float pct) [inline]
References pct_work_complete.
Member Data Documentation
do_work
std::function<void(std::shared_ptr<Entity> owner, HasWork&, std::shared_ptr<Entity> person, float dt)> HasWork::do_work
Referenced by init(), and system_manager::input_process_manager::inround::work_furniture().
more_to_do
bool HasWork::more_to_do [private]
Referenced by has_work(), serialize(), and set_has_more_work().
pct_work_complete
float HasWork::pct_work_complete [private]
Referenced by can_show_progress_bar(), increase_pct(), is_work_complete(), reset_pct(), scale_length(), serialize(), and update_pct().
The documentation for this struct was generated from the following file:
src/components/has_work.h