Job Struct Reference
#include <job.h>
Public Types
enum struct State {
Initialize
, HeadingToStart
, HeadingToEnd
, WorkingAtStart
,
WorkingAtEnd
, Completed
 }
Public Member Functions
bool path_empty () const
const vec2 & path_front () const
const std::deque< vec2 > & get_path () const
int p_size () const
vec2 path_index (int index) const
void path_pop_front ()
void update_path (const std::deque< vec2 > &new_path)
template<typename S >
void serialize (S &s)
void run_job_tick (const std::shared_ptr< Entity > &entity, float dt)
Job ()
Job (JobType _type, vec2 _start, vec2 _end)
virtual ~Job ()
Static Public Member Functions
static Job * create_job_of_type (vec2, vec2, JobType type)
Public Attributes
enum Job::State state = State::Initialize
JobType type
vec2 start
vec2 end
std::optional< vec2 > local
Protected Member Functions
virtual State run_state_initialize (const std::shared_ptr< Entity > &, float)
virtual State run_state_heading_to_start (const std::shared_ptr< Entity > &entity, float dt)
virtual State run_state_heading_to_end (const std::shared_ptr< Entity > &entity, float dt)
virtual State run_state_working_at_start (const std::shared_ptr< Entity > &, float)
virtual State run_state_working_at_end (const std::shared_ptr< Entity > &, float)
virtual void on_cleanup ()
virtual void before_each_job_tick (const std::shared_ptr< Entity > &, float)
bool has_local_target () const
Private Member Functions
State _run_job_tick (const std::shared_ptr< Entity > &entity, float dt)
bool is_at_position (const std::shared_ptr< Entity > &entity, vec2 position)
void travel_to_position (const std::shared_ptr< Entity > &entity, float dt, vec2 goal)
Private Attributes
int path_size = 0
std::deque< vec2 > path
Member Enumeration Documentation
State
enum struct Job::State [strong]
Enumerator
Initialize
HeadingToStart
HeadingToEnd
WorkingAtStart
WorkingAtEnd
Completed
Constructor & Destructor Documentation
Job() [1/2]
Job::Job () [inline]
Job() [2/2]
Job::Job (JobType _type, vec2 _start, vec2 _end) [inline]
 Job()
virtual Job::~Job () [inline], [virtual]
Member Function Documentation
_run_job_tick()
State Job::_run_job_tick (const std::shared_ptr< Entity > & entity, float dt) [inline], [private]
References before_each_job_tick(), Completed, HeadingToEnd, HeadingToStart, Initialize, run_state_heading_to_end(), run_state_heading_to_start(), run_state_initialize(), run_state_working_at_end(), run_state_working_at_start(), state, WorkingAtEnd, and WorkingAtStart.
Referenced by run_job_tick().
before_each_job_tick()
virtual void Job::before_each_job_tick (const std::shared_ptr< Entity > & , float) [inline], [protected], [virtual]
Reimplemented in WaitInQueueJob.
Referenced by _run_job_tick().
create_job_of_type()
Job * Job::create_job_of_type (vec2 _start, vec2 _end, JobType type) [static]
References create_wandering_job(), Leaving, log_warn, None, Wait, WaitInQueue, and Wandering.
Referenced by system_manager::job_system::ensure_has_job(), and WaitInQueueJob::run_state_working_at_end().
get_path()
const std::deque< vec2 > & Job::get_path () const [inline]
References path.
has_local_target()
bool Job::has_local_target () const [inline], [protected]
References local.
Referenced by travel_to_position().
is_at_position()
bool Job::is_at_position (const std::shared_ptr< Entity > & entity, vec2 position) [inline], [private]
References Transform::as2(), vec::distance(), and TILESIZE.
Referenced by run_state_heading_to_end(), run_state_heading_to_start(), and travel_to_position().
on_cleanup()
virtual void Job::on_cleanup () [inline], [protected], [virtual]
p_size()
int Job::p_size () const [inline]
References path.
Referenced by travel_to_position().
path_empty()
bool Job::path_empty () const [inline]
References path.
Referenced by travel_to_position().
path_front()
const vec2 & Job::path_front () const [inline]
References path.
Referenced by travel_to_position().
path_index()
vec2 Job::path_index (int index) const [inline]
References path.
path_pop_front()
void Job::path_pop_front () [inline]
References path, and path_size.
Referenced by travel_to_position().
run_job_tick()
void Job::run_job_tick (const std::shared_ptr< Entity > & entity, float dt) [inline]
References _run_job_tick(), and state.
run_state_heading_to_end()
Job::State Job::run_state_heading_to_end (const std::shared_ptr< Entity > & entity, float dt) [protected], [virtual]
References end, HeadingToEnd, is_at_position(), travel_to_position(), and WorkingAtEnd.
Referenced by _run_job_tick().
run_state_heading_to_start()
Job::State Job::run_state_heading_to_start (const std::shared_ptr< Entity > & entity, float dt) [protected], [virtual]
References HeadingToStart, is_at_position(), start, travel_to_position(), and WorkingAtStart.
Referenced by _run_job_tick().
run_state_initialize()
virtual State Job::run_state_initialize (const std::shared_ptr< Entity > & , float) [inline], [protected], [virtual]
Reimplemented in WaitInQueueJob.
References HeadingToStart.
Referenced by _run_job_tick().
run_state_working_at_end()
virtual State Job::run_state_working_at_end (const std::shared_ptr< Entity > & , float) [inline], [protected], [virtual]
Reimplemented in WaitJob, WaitInQueueJob, and LeavingJob.
References Completed.
Referenced by _run_job_tick().
run_state_working_at_start()
virtual State Job::run_state_working_at_start (const std::shared_ptr< Entity > & , float) [inline], [protected], [virtual]
Reimplemented in WaitInQueueJob.
References HeadingToEnd.
Referenced by _run_job_tick().
serialize()
template<typename S >
void Job::serialize (S & s) [inline]
References end, local, path, path_size, start, state, and type.
travel_to_position()
void Job::travel_to_position (const std::shared_ptr< Entity > & entity, float dt, vec2 goal) [inline], [private]
References CanHaveAilment::ailment(), system_manager::logging_manager::announce(), Transform::as2(), astar::find_path(), has_local_target(), is_at_position(), EntityHelper::isWalkable(), local, log_warn, p_size(), path_empty(), path_front(), path_pop_front(), Transform::raw(), vec::to3(), Transform::update(), update_path(), and VALIDATE.
Referenced by run_state_heading_to_end(), and run_state_heading_to_start().
update_path()
void Job::update_path (const std::deque< vec2 > & new_path) [inline]
References path, and path_size.
Referenced by travel_to_position().
Member Data Documentation
end
vec2 Job::end
Referenced by run_state_heading_to_end(), WaitInQueueJob::run_state_initialize(), and serialize().
local
std::optional<vec2> Job::local
Referenced by CanPerformJob::has_local_target(), has_local_target(), serialize(), and travel_to_position().
path
std::deque<vec2> Job::path [private]
Referenced by get_path(), p_size(), path_empty(), path_front(), path_index(), path_pop_front(), serialize(), and update_path().
path_size
int Job::path_size = 0 [private]
Referenced by path_pop_front(), serialize(), and update_path().
start
vec2 Job::start
Referenced by CanPerformJob::job_start(), run_state_heading_to_start(), WaitInQueueJob::run_state_initialize(), LeavingJob::run_state_working_at_end(), WaitInQueueJob::run_state_working_at_start(), and serialize().
state
enum Job::State Job::state = State::Initialize
Referenced by _run_job_tick(), run_job_tick(), and serialize().
type
JobType Job::type
Referenced by serialize().
The documentation for this struct was generated from the following files:
src/job.h
src/job.cpp