ui::autolayout Namespace Reference
Functions
float compute_size_for_standalone_expectation (Widget *widget, int exp_index)
float compute_size_for_parent_expectation (Widget *widget, int exp_index)
float _sum_children_axis_for_child_exp (Widget *widget, int exp_index)
float _max_child_size (Widget *widget, int exp_index)
float compute_size_for_child_expectation (Widget *widget, int exp_index)
void calculate_standalone (Widget *widget)
void calculate_those_with_parents (Widget *widget)
void calculate_those_with_children (Widget *widget)
float _get_total_child_size_for_violations (Widget *widget, int exp_index)
void _solve_error_with_optional (Widget *widget, int exp_index, float *error)
void fix_violating_children (Widget *widget, int exp_index, float error, int num_children)
void tax_refund (Widget *widget, int exp_index, float error)
int _get_total_number_children (Widget *widget)
void solve_violations (Widget *widget)
void compute_relative_positions (Widget *widget)
void compute_rect_bounds (Widget *widget)
void process_widget (Widget *widget)
Variables
const float ACCEPTABLE_ERROR = 0.5f
Function Documentation
_get_total_child_size_for_violations()
float ui::autolayout::_get_total_child_size_for_violations (Widget * widget, int exp_index)
References ui::Widget::absolute, ui::Widget::children, ui::Column, ui::Widget::computed_size, ui::Widget::growflags, and ui::Row.
Referenced by solve_violations().
_get_total_number_children()
int ui::autolayout::_get_total_number_children (Widget * widget)
References ui::Widget::absolute, and ui::Widget::children.
Referenced by solve_violations().
_max_child_size()
float ui::autolayout::_max_child_size (Widget * widget, int exp_index)
References ui::Widget::absolute, ui::Children, ui::Widget::children, ui::Widget::computed_size, M_ASSERT, ui::SizeExpectation::mode, ui::Percent, and ui::Widget::size_expected.
Referenced by compute_size_for_child_expectation().
_solve_error_with_optional()
void ui::autolayout::_solve_error_with_optional (Widget * widget, int exp_index, float * error)
References ui::Widget::absolute, ui::Widget::children, ui::Widget::computed_size, ui::Widget::size_expected, and ui::SizeExpectation::strictness.
Referenced by solve_violations().
_sum_children_axis_for_child_exp()
float ui::autolayout::_sum_children_axis_for_child_exp (Widget * widget, int exp_index)
References ui::Widget::absolute, ui::Children, ui::Widget::children, ui::Widget::computed_size, M_ASSERT, ui::SizeExpectation::mode, ui::Percent, ui::Widget::print_tree(), and ui::Widget::size_expected.
Referenced by compute_size_for_child_expectation().
calculate_standalone()
void ui::autolayout::calculate_standalone (Widget * widget)
References calculate_standalone(), ui::Widget::children, compute_size_for_standalone_expectation(), and ui::Widget::computed_size.
Referenced by calculate_standalone(), and process_widget().
calculate_those_with_children()
void ui::autolayout::calculate_those_with_children (Widget * widget)
References calculate_those_with_children(), ui::Widget::children, compute_size_for_child_expectation(), and ui::Widget::computed_size.
Referenced by calculate_those_with_children(), and process_widget().
calculate_those_with_parents()
void ui::autolayout::calculate_those_with_parents (Widget * widget)
References calculate_those_with_parents(), ui::Widget::children, compute_size_for_parent_expectation(), and ui::Widget::computed_size.
Referenced by calculate_those_with_parents(), and process_widget().
compute_rect_bounds()
void ui::autolayout::compute_rect_bounds (Widget * widget)
References ui::Widget::children, compute_rect_bounds(), ui::Widget::computed_relative_pos, ui::Widget::computed_size, log_trace, ui::Widget::parent, and ui::Widget::rect.
Referenced by compute_rect_bounds(), and process_widget().
compute_relative_positions()
void ui::autolayout::compute_relative_positions (Widget * widget)
References ui::Widget::absolute, ui::Widget::children, ui::Column, compute_relative_positions(), ui::Widget::computed_relative_pos, ui::Widget::computed_size, ui::Widget::growflags, ui::None, ui::Widget::parent, and ui::Row.
Referenced by compute_relative_positions(), and process_widget().
compute_size_for_child_expectation()
float ui::autolayout::compute_size_for_child_expectation (Widget * widget, int exp_index)
References _max_child_size(), _sum_children_axis_for_child_exp(), ui::Children, ui::Widget::children, ui::Column, ui::Widget::computed_size, ui::Widget::growflags, log_trace, ui::SizeExpectation::mode, and ui::Widget::size_expected.
Referenced by calculate_those_with_children().
compute_size_for_parent_expectation()
float ui::autolayout::compute_size_for_parent_expectation (Widget * widget, int exp_index)
References ui::Widget::absolute, ui::Widget::computed_size, M_ASSERT, ui::SizeExpectation::mode, ui::Widget::parent, ui::Percent, ui::Widget::print_tree(), ui::Widget::size_expected, and ui::SizeExpectation::value.
Referenced by calculate_those_with_parents().
compute_size_for_standalone_expectation()
float ui::autolayout::compute_size_for_standalone_expectation (Widget * widget, int exp_index)
References ui::Widget::computed_size, log_trace, ui::SizeExpectation::mode, ui::Pixels, ui::Widget::size_expected, ui::Text, and ui::SizeExpectation::value.
Referenced by calculate_standalone().
fix_violating_children()
void ui::autolayout::fix_violating_children (Widget * widget, int exp_index, float error, int num_children)
References ui::Widget::absolute, ACCEPTABLE_ERROR, ui::Widget::children, ui::Column, ui::Widget::computed_size, ui::Widget::growflags, log_warn, M_ASSERT, ui::Widget::print_tree(), ui::Row, ui::Widget::size_expected, and ui::SizeExpectation::strictness.
Referenced by solve_violations().
process_widget()
void ui::autolayout::process_widget (Widget * widget)
References calculate_standalone(), calculate_those_with_children(), calculate_those_with_parents(), compute_rect_bounds(), compute_relative_positions(), and solve_violations().
Referenced by ui::UIContext::end().
solve_violations()
void ui::autolayout::solve_violations (Widget * widget)
References _get_total_child_size_for_violations(), _get_total_number_children(), _solve_error_with_optional(), ACCEPTABLE_ERROR, ui::Widget::children, ui::Widget::computed_size, fix_violating_children(), log_trace, log_warn, solve_violations(), and tax_refund().
Referenced by process_widget(), and solve_violations().
tax_refund()
void ui::autolayout::tax_refund (Widget * widget, int exp_index, float error)
References ui::Widget::absolute, ui::Widget::children, ui::Widget::computed_size, log_trace, ui::Widget::size_expected, ui::SizeExpectation::strictness, and tax_refund().
Referenced by solve_violations(), and tax_refund().
Variable Documentation
ACCEPTABLE_ERROR
const float ui::autolayout::ACCEPTABLE_ERROR = 0.5f
Referenced by fix_violating_children(), and solve_violations().