Event Struct Reference
#include <event.h>
Public Member Functions
virtual ~Event ()
virtual EventType getEventType () const =0
virtual const char * getName () const =0
virtual int getCategoryFlags () const =0
virtual std::string toString () const
bool isInCategory (EventCategory cat) const
Public Attributes
bool handled = false
Friends
struct EventDispatcher
Constructor & Destructor Documentation
 Event()
virtual Event::~Event () [inline], [virtual]
Member Function Documentation
getCategoryFlags()
virtual int Event::getCategoryFlags () const [pure virtual]
Referenced by isInCategory().
getEventType()
virtual EventType Event::getEventType () const [pure virtual]
Referenced by EventDispatcher::dispatch().
getName()
virtual const char * Event::getName () const [pure virtual]
Referenced by toString().
isInCategory()
bool Event::isInCategory (EventCategory cat) const [inline]
References getCategoryFlags().
toString()
virtual std::string Event::toString () const [inline], [virtual]
References getName().
Friends And Related Function Documentation
EventDispatcher
friend struct EventDispatcher [friend]
Member Data Documentation
handled
bool Event::handled = false
Referenced by App::processEvent().
The documentation for this struct was generated from the following file:
src/engine/event.h