BasePlayer Struct Reference
#include <base_player.h>
Public Member Functions
BasePlayer (vec3 p, Color face_color_in, Color base_color_in)
BasePlayer (vec2 p, Color face_color_in, Color base_color_in)
BasePlayer ()
BasePlayer (vec2 location)
virtual float base_speed () override
virtual vec3 update_xaxis_position (float dt) override=0
virtual vec3 update_zaxis_position (float dt) override=0
void highlight_facing_furniture ()
virtual void planning_update (float dt) override
Public Member Functions inherited from Person
Person (vec3 p, Color face_color_in, Color base_color_in)
Person (vec2 p, Color face_color_in, Color base_color_in)
Person (vec3 p, Color c)
Person (vec2 p, Color c)
virtual vec3 update_xaxis_position (float dt)=0
virtual vec3 update_zaxis_position (float dt)=0
virtual float base_speed ()
virtual vec3 size () const override
void select_next_character_model ()
virtual std::optional< ModelInfo > model () const override
void handle_collision (int facedir_x, vec3 new_pos_x, int facedir_z, vec3 new_pos_z)
std::tuple< int, int > get_face_direction (vec3 new_pos_x, vec3 new_pos_z)
void update_facing_direction (int facedir_x, int facedir_z)
virtual void always_update (float dt) override
Public Member Functions inherited from Entity
FrontFaceDirection offsetFaceDirection (FrontFaceDirection startingDirection, float offset) const
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
void update_name (const std::string &new_name)
virtual bool can_take_item_from () const
virtual bool collides (BoundingBox b) const
virtual BoundingBox bounds () const
virtual void update_position (const vec3 &p)
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void render () const final
virtual void update (float dt) final
Public Attributes
float player_reach = 1.25f
std::shared_ptr< Furniture > held_furniture
Public Attributes inherited from Entity
const std::map< FrontFaceDirection, float > FrontFaceDirectionMap
const std::map< int, FrontFaceDirection > DirectionToFrontFaceMap
int id
vec3 raw_position
vec3 prev_position
vec3 position
vec3 pushed_force {0.0, 0.0, 0.0}
Color face_color
Color base_color
bool cleanup = false
bool is_highlighted = false
bool is_held = false
FrontFaceDirection face_direction = FrontFaceDirection::FORWARD
std::shared_ptr< Item > held_item = nullptr
int name_length = 1
std::string name = ``
Additional Inherited Members
Public Types inherited from Entity
enum FrontFaceDirection { FORWARD = 0x1
, RIGHT = 0x2
, BACK = 0x4
, LEFT = 0x8
 }
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, FrontFaceDirection direction)
Protected Member Functions inherited from Person
Person ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual void render_debug_mode () const
virtual void render_highlighted () const
virtual void render_normal () const
virtual void render_floating_name () const
virtual std::optional< ModelInfo > model () const
vec3 snap_position () const
virtual void update_held_item_position ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void always_update (float)
virtual void planning_update (float)
virtual void in_round_update (float)
virtual bool is_snappable ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Constructor & Destructor Documentation
BasePlayer() [1/4]
BasePlayer::BasePlayer (vec3 p, Color face_color_in, Color base_color_in) [inline]
BasePlayer() [2/4]
BasePlayer::BasePlayer (vec2 p, Color face_color_in, Color base_color_in) [inline]
BasePlayer() [3/4]
BasePlayer::BasePlayer () [inline]
BasePlayer() [4/4]
BasePlayer::BasePlayer (vec2 location) [inline]
Member Function Documentation
base_speed()
virtual float BasePlayer::base_speed () [inline], [override], [virtual]
Reimplemented from Person.
Referenced by Player::get_position_after_input().
highlight_facing_furniture()
void BasePlayer::highlight_facing_furniture () [inline]
References Entity::face_direction, Entity::position, and vec::to2().
Referenced by planning_update().
planning_update()
virtual void BasePlayer::planning_update (float dt) [inline], [override], [virtual]
Reimplemented from Entity.
References Entity::BACK, Entity::face_direction, Entity::FORWARD, held_furniture, highlight_facing_furniture(), Entity::LEFT, Entity::planning_update(), Entity::position, Entity::RIGHT, and TILESIZE.
update_xaxis_position()
virtual vec3 BasePlayer::update_xaxis_position (float dt) [override], [pure virtual]
Implements Person.
Implemented in Player, and RemotePlayer.
update_zaxis_position()
virtual vec3 BasePlayer::update_zaxis_position (float dt) [override], [pure virtual]
Implements Person.
Implemented in Player, and RemotePlayer.
Member Data Documentation
held_furniture
std::shared_ptr<Furniture> BasePlayer::held_furniture
Referenced by Player::handle_in_planning_grab_or_drop(), and planning_update().
player_reach
float BasePlayer::player_reach = 1.25f
Referenced by Player::handle_in_game_grab_or_drop(), Player::handle_in_planning_grab_or_drop(), Player::rotate_furniture(), and Player::work_furniture().
The documentation for this struct was generated from the following file:
src/base_player.h