Transform Struct Reference
#include <transform.h>
Public Types
enum FrontFaceDirection { FORWARD = 0x1
, RIGHT = 0x2
, BACK = 0x4
, LEFT = 0x8
 }
Public Member Functions
int roundToNearest45 (int degrees) const
FrontFaceDirection offsetFaceDirection (FrontFaceDirection startingDirection, int offset) const
virtual ~Transform ()
void init (vec3 pos, vec3 sz)
void update (vec3 npos)
void update_x (float x)
void update_y (float y)
void update_z (float z)
void update_face_direction (FrontFaceDirection dir)
FrontFaceDirection face_direction () const
vec2 as2 () const
vec3 raw () const
vec3 pos () const
vec3 size () const
float sizex () const
float sizey () const
float sizez () const
void update_size (vec3 sze)
BoundingBox raw_bounds () const
BoundingBox expanded_bounds (vec3 inc) const
virtual BoundingBox bounds () const
vec3 snap_position () const
bool collides (BoundingBox b) const
void rotate_facing_clockwise (int angle=90)
vec2 tile_infront (int distance)
void turn_to_face_pos (const vec2 goal)
void trunc (int places)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Static Public Member Functions
static vec2 tile_infront_given_pos (vec2 tile, int distance, Transform::Transform::FrontFaceDirection direction)
Public Attributes
const std::map< FrontFaceDirection, float > FrontFaceDirectionMap
const std::map< int, FrontFaceDirection > DirectionToFrontFaceMap
Private Member Functions
vec2 get_heading () const
void sync ()
template<typename S >
void serialize (S &s)
Private Attributes
FrontFaceDirection face = FrontFaceDirection::FORWARD
vec3 _size = {TILESIZE, TILESIZE, TILESIZE}
vec3 position
vec3 raw_position
Member Enumeration Documentation
FrontFaceDirection
enum Transform::FrontFaceDirection
Enumerator
FORWARD
RIGHT
BACK
LEFT
Constructor & Destructor Documentation
 Transform()
virtual Transform::~Transform () [inline], [virtual]
Member Function Documentation
as2()
vec2 Transform::as2 () const [inline]
References position, and vec::to2().
Referenced by WaitInQueueJob::before_each_job_tick(), EntityHelper::getClosestMatchingEntity(), EntityHelper::getClosestMatchingFurniture(), EntityHelper::getClosestWithComponent(), EntityHelper::getEntitiesInRange(), EntityHelper::getMatchingEntityInFront(), Job::is_at_position(), test::p(), system_manager::process_grabber_items(), WaitInQueueJob::run_state_working_at_end(), system_manager::sophie(), Job::travel_to_position(), turn_to_face_pos(), and generation::helper::validate().
bounds()
virtual BoundingBox Transform::bounds () const [inline], [virtual]
References get_bounds(), position, and size().
Referenced by collides(), system_manager::count_trigger_area_entrants(), and system_manager::render_manager::render_bounding_box().
collides()
bool Transform::collides (BoundingBox b) const [inline]
References bounds().
expanded_bounds()
BoundingBox Transform::expanded_bounds (vec3 inc) const [inline]
References get_bounds(), raw_position, and size().
Referenced by system_manager::count_trigger_area_entrants().
face_direction()
FrontFaceDirection Transform::face_direction () const [inline]
References face.
Referenced by system_manager::render_manager::draw_valid_colored_box(), get_heading(), EntityHelper::getClosestMatchingFurniture(), system_manager::process_grabber_items(), system_manager::render_manager::render_model_highlighted(), system_manager::render_manager::render_model_normal(), rotate_facing_clockwise(), tile_infront(), system_manager::update_held_furniture_position(), and system_manager::update_held_item_position().
get_heading()
vec2 Transform::get_heading () const [inline], [private]
References util::deg2rad(), face_direction(), and FrontFaceDirectionMap.
init()
void Transform::init (vec3 pos, vec3 sz) [inline]
References _size, pos(), position, and raw_position.
offsetFaceDirection()
FrontFaceDirection Transform::offsetFaceDirection (FrontFaceDirection startingDirection, int offset) const [inline]
References DirectionToFrontFaceMap, FrontFaceDirectionMap, and roundToNearest45().
Referenced by system_manager::process_grabber_items(), and rotate_facing_clockwise().
pos()
vec3 Transform::pos () const [inline]
References position.
Referenced by system_manager::logging_manager::announce(), init(), GameLayer::onUpdate(), operator<<(), system_manager::input_process_manager::process_player_movement_input(), system_manager::ui::render_player_info(), system_manager::render_manager::render_speech_bubble(), system_manager::render_manager::render_trigger_area(), system_manager::update_held_furniture_position(), and system_manager::update_held_item_position().
raw()
vec3 Transform::raw () const [inline]
References raw_position.
Referenced by system_manager::render_manager::draw_valid_colored_box(), system_manager::person_update_given_new_pos(), system_manager::render_manager::render_bounding_box(), system_manager::render_manager::render_floating_name(), system_manager::render_manager::render_progress_bar(), system_manager::transform_snapper(), Job::travel_to_position(), and trunc().
raw_bounds()
BoundingBox Transform::raw_bounds () const [inline]
References get_bounds(), raw_position, and size().
rotate_facing_clockwise()
void Transform::rotate_facing_clockwise (int angle = 90) [inline]
References face_direction(), offsetFaceDirection(), and update_face_direction().
Referenced by turn_to_face_pos().
roundToNearest45()
int Transform::roundToNearest45 (int degrees) const [inline]
Referenced by offsetFaceDirection().
serialize()
template<typename S >
void Transform::serialize (S & s) [inline], [private]
References _size, face, position, and raw_position.
size()
vec3 Transform::size () const [inline]
References _size.
Referenced by bounds(), expanded_bounds(), operator<<(), system_manager::person_update_given_new_pos(), raw_bounds(), system_manager::render_manager::render_model_highlighted(), system_manager::render_manager::render_model_normal(), sizex(), sizey(), and sizez().
sizex()
float Transform::sizex () const [inline]
References size().
Referenced by system_manager::render_manager::draw_valid_colored_box().
sizey()
float Transform::sizey () const [inline]
References size().
Referenced by system_manager::render_manager::draw_valid_colored_box().
sizez()
float Transform::sizez () const [inline]
References size().
Referenced by system_manager::render_manager::draw_valid_colored_box().
snap_position()
vec3 Transform::snap_position () const [inline]
References raw_position, and vec::snap().
Referenced by EntityHelper::getMatchingEntityInFront(), system_manager::input_process_manager::inround::handle_drop(), tile_infront(), and system_manager::transform_snapper().
sync()
void Transform::sync () [inline], [private]
References position, and raw_position.
Referenced by update(), update_x(), update_y(), and update_z().
tile_infront()
vec2 Transform::tile_infront (int distance) [inline]
References face_direction(), snap_position(), tile_infront_given_pos(), and vec::to2().
Referenced by system_manager::input_process_manager::planning::drop_held_furniture().
tile_infront_given_pos()
static vec2 Transform::tile_infront_given_pos (vec2 tile, int distance, Transform::Transform::FrontFaceDirection direction) [inline], [static]
References BACK, FORWARD, LEFT, RIGHT, and TILESIZE.
Referenced by EntityHelper::getMatchingEntityInFront(), and tile_infront().
trunc()
void Transform::trunc (int places) [inline]
References raw(), util::trunc(), and update().
Referenced by system_manager::input_process_manager::process_player_movement_input().
turn_to_face_pos()
void Transform::turn_to_face_pos (const vec2 goal) [inline]
References as2(), face, FrontFaceDirectionMap, util::rad2deg(), and rotate_facing_clockwise().
update()
void Transform::update (vec3 npos) [inline]
References raw_position, and sync().
Referenced by system_manager::transform_snapper(), Job::travel_to_position(), trunc(), and update_player_remotely().
update_face_direction()
void Transform::update_face_direction (FrontFaceDirection dir) [inline]
References face.
Referenced by system_manager::person_update_given_new_pos(), rotate_facing_clockwise(), and update_player_remotely().
update_size()
void Transform::update_size (vec3 sze) [inline]
References _size.
update_x()
void Transform::update_x (float x) [inline]
References raw_position, and sync().
Referenced by system_manager::person_update_given_new_pos().
update_y()
void Transform::update_y (float y) [inline]
References raw_position, and sync().
update_z()
void Transform::update_z (float z) [inline]
References raw_position, and sync().
Referenced by system_manager::person_update_given_new_pos().
Member Data Documentation
_size
vec3 Transform::_size = {TILESIZE, TILESIZE, TILESIZE} [private]
Referenced by init(), serialize(), size(), and update_size().
DirectionToFrontFaceMap
const std::map<int, FrontFaceDirection> Transform::DirectionToFrontFaceMap
Initial value:
{
        {0, FORWARD}, {45, FORWARD | RIGHT}, {90, RIGHT},
        {135, BACK | RIGHT}, {180, BACK}, {225, BACK | LEFT},
        {270, LEFT}, {315, FORWARD | LEFT}}
Referenced by offsetFaceDirection().
face
FrontFaceDirection Transform::face = FrontFaceDirection::FORWARD [private]
Referenced by face_direction(), serialize(), turn_to_face_pos(), and update_face_direction().
FrontFaceDirectionMap
const std::map<FrontFaceDirection, float> Transform::FrontFaceDirectionMap
Initial value:
{
        {FORWARD, 0.0f}, {FORWARD | RIGHT, 45.0f}, {RIGHT, 90.0f},
        {BACK | RIGHT, 135.0f}, {BACK, 180.0f}, {BACK | LEFT, 225.0f},
        {LEFT, 270.0f}, {FORWARD | LEFT, 315.0f}}
Referenced by system_manager::render_manager::draw_valid_colored_box(), get_heading(), offsetFaceDirection(), system_manager::render_manager::render_model_highlighted(), system_manager::render_manager::render_model_normal(), and turn_to_face_pos().
position
vec3 Transform::position [private]
Referenced by as2(), bounds(), init(), pos(), serialize(), and sync().
raw_position
vec3 Transform::raw_position [private]
Referenced by expanded_bounds(), init(), raw(), raw_bounds(), serialize(), snap_position(), sync(), update(), update_x(), update_y(), and update_z().
The documentation for this struct was generated from the following file:
src/components/transform.h