AIPerson Struct Reference
#include <aiperson.h>
Public Member Functions
AIPerson ()
AIPerson (vec3 p, Color face_color_in, Color base_color_in)
AIPerson (vec2 p, Color face_color_in, Color base_color_in)
AIPerson (vec3 p, Color c)
AIPerson (vec2 p, Color c)
virtual float base_speed () override
virtual float stagger_mult ()
virtual void render_debug_mode () const override
virtual vec3 update_xaxis_position (float dt) override
virtual vec3 update_zaxis_position (float dt) override
virtual Job * get_wandering_job ()
void travel_on_path (vec2 me)
bool navigate_to (vec2 goal)
virtual void wandering ()
virtual void get_starting_job ()
virtual void get_idle_job ()
virtual void find_new_job ()
virtual void process_job (float)
virtual void in_round_update (float dt) override
virtual void announce (std::string text)
virtual bool is_snappable () override
Public Member Functions inherited from Person
Person (vec3 p, Color face_color_in, Color base_color_in)
Person (vec2 p, Color face_color_in, Color base_color_in)
Person (vec3 p, Color c)
Person (vec2 p, Color c)
virtual vec3 update_xaxis_position (float dt)=0
virtual vec3 update_zaxis_position (float dt)=0
virtual float base_speed ()
virtual vec3 size () const override
void select_next_character_model ()
virtual std::optional< ModelInfo > model () const override
void handle_collision (int facedir_x, vec3 new_pos_x, int facedir_z, vec3 new_pos_z)
std::tuple< int, int > get_face_direction (vec3 new_pos_x, vec3 new_pos_z)
void update_facing_direction (int facedir_x, int facedir_z)
virtual void always_update (float dt) override
Public Member Functions inherited from Entity
FrontFaceDirection offsetFaceDirection (FrontFaceDirection startingDirection, float offset) const
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
void update_name (const std::string &new_name)
virtual bool can_take_item_from () const
virtual bool collides (BoundingBox b) const
virtual BoundingBox bounds () const
virtual void update_position (const vec3 &p)
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void render () const final
virtual void update (float dt) final
Public Attributes
std::stack< std::shared_ptr< Job > > personal_queue
std::shared_ptr< Job > job
Public Attributes inherited from Entity
const std::map< FrontFaceDirection, float > FrontFaceDirectionMap
const std::map< int, FrontFaceDirection > DirectionToFrontFaceMap
int id
vec3 raw_position
vec3 prev_position
vec3 position
vec3 pushed_force {0.0, 0.0, 0.0}
Color face_color
Color base_color
bool cleanup = false
bool is_highlighted = false
bool is_held = false
FrontFaceDirection face_direction = FrontFaceDirection::FORWARD
std::shared_ptr< Item > held_item = nullptr
int name_length = 1
std::string name = ``
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Public Types inherited from Entity
enum FrontFaceDirection { FORWARD = 0x1
, RIGHT = 0x2
, BACK = 0x4
, LEFT = 0x8
 }
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, FrontFaceDirection direction)
Protected Member Functions inherited from Person
Person ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual void render_debug_mode () const
virtual void render_highlighted () const
virtual void render_normal () const
virtual void render_floating_name () const
virtual std::optional< ModelInfo > model () const
vec3 snap_position () const
virtual void update_held_item_position ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void always_update (float)
virtual void planning_update (float)
virtual void in_round_update (float)
virtual bool is_snappable ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Constructor & Destructor Documentation
AIPerson() [1/5]
AIPerson::AIPerson () [inline]
AIPerson() [2/5]
AIPerson::AIPerson (vec3 p, Color face_color_in, Color base_color_in) [inline]
AIPerson() [3/5]
AIPerson::AIPerson (vec2 p, Color face_color_in, Color base_color_in) [inline]
AIPerson() [4/5]
AIPerson::AIPerson (vec3 p, Color c) [inline]
AIPerson() [5/5]
AIPerson::AIPerson (vec2 p, Color c) [inline]
Member Function Documentation
announce()
virtual void AIPerson::announce (std::string text) [inline], [virtual]
Referenced by Customer::wait(), Customer::wait_in_queue(), and wandering().
base_speed()
virtual float AIPerson::base_speed () [inline], [override], [virtual]
Reimplemented from Person.
Reimplemented in Customer.
Referenced by update_xaxis_position(), and update_zaxis_position().
find_new_job()
virtual void AIPerson::find_new_job () [inline], [virtual]
References get_idle_job(), job, and personal_queue.
Referenced by in_round_update().
get_idle_job()
virtual void AIPerson::get_idle_job () [inline], [virtual]
References get_wandering_job(), and job.
Referenced by find_new_job().
get_starting_job()
virtual void AIPerson::get_starting_job () [inline], [virtual]
Reimplemented in Customer.
References get_wandering_job(), and job.
Referenced by in_round_update().
get_wandering_job()
virtual Job * AIPerson::get_wandering_job () [inline], [virtual]
References EntityHelper::isWalkable(), Entity::position, vec::to2(), and Wandering.
Referenced by get_idle_job(), and get_starting_job().
in_round_update()
virtual void AIPerson::in_round_update (float dt) [inline], [override], [virtual]
Reimplemented from Entity.
Reimplemented in Customer.
References Job::Completed, find_new_job(), get_starting_job(), Entity::in_round_update(), job, process_job(), and Entity::pushed_force.
Referenced by Customer::in_round_update().
is_snappable()
virtual bool AIPerson::is_snappable () [inline], [override], [virtual]
Reimplemented from Entity.
navigate_to()
bool AIPerson::navigate_to (vec2 goal) [inline]
References EntityHelper::isWalkable(), job, Entity::position, vec::to2(), and travel_on_path().
Referenced by Customer::wait(), Customer::wait_in_queue(), and wandering().
process_job()
virtual void AIPerson::process_job (float) [inline], [virtual]
Reimplemented in Customer.
References job, wandering(), and Wandering.
Referenced by in_round_update().
render_debug_mode()
virtual void AIPerson::render_debug_mode () const [inline], [override], [virtual]
Reimplemented from Entity.
References job, Entity::render_debug_mode(), TILESIZE, and vec::to3().
serialize()
template<typename S >
void AIPerson::serialize (S & s) [inline], [private]
stagger_mult()
virtual float AIPerson::stagger_mult () [inline], [virtual]
Reimplemented in Customer.
Referenced by update_xaxis_position(), and update_zaxis_position().
travel_on_path()
void AIPerson::travel_on_path (vec2 me) [inline]
References job.
Referenced by navigate_to().
update_xaxis_position()
virtual vec3 AIPerson::update_xaxis_position (float dt) [inline], [override], [virtual]
Implements Person.
References base_speed(), job, Entity::raw_position, and stagger_mult().
update_zaxis_position()
virtual vec3 AIPerson::update_zaxis_position (float dt) [inline], [override], [virtual]
Implements Person.
References base_speed(), job, Entity::raw_position, and stagger_mult().
wandering()
virtual void AIPerson::wandering () [inline], [virtual]
References announce(), Job::Completed, Job::HeadingToEnd, Job::HeadingToStart, Job::Initialize, job, navigate_to(), personal_queue, Wandering, Job::WorkingAtEnd, and Job::WorkingAtStart.
Referenced by Customer::process_job(), and process_job().
Member Data Documentation
job
std::shared_ptr<Job> AIPerson::job
Referenced by find_new_job(), get_idle_job(), get_starting_job(), Customer::get_starting_job(), in_round_update(), navigate_to(), Customer::process_job(), process_job(), render_debug_mode(), travel_on_path(), update_xaxis_position(), update_zaxis_position(), Customer::wait(), Customer::wait_in_queue(), and wandering().
personal_queue
std::stack<std::shared_ptr<Job> > AIPerson::personal_queue
Referenced by find_new_job(), Customer::wait_in_queue(), and wandering().
The documentation for this struct was generated from the following file:
src/aiperson.h