EntityHelper Struct Reference
#include <entityhelper.h>
Public Types
enum ForEachFlow { NormalFlow = 0
, Continue = 1
, Break = 2
 }
Static Public Member Functions
static Entities & get_entities ()
static void addEntity (std::shared_ptr< Entity > e)
static void removeEntity (std::shared_ptr< Entity > e)
static void cleanup ()
static void forEachEntity (std::function< ForEachFlow(std::shared_ptr< Entity > &)> cb)
template<typename T >
static constexpr std::shared_ptr< T > getFirstMatching (std::function< bool(std::shared_ptr< T >)> filter)
template<typename T >
static constexpr std::vector< std::shared_ptr< T > > getEntitiesInRange (vec2 pos, float range)
template<typename T >
static std::shared_ptr< T > getMatchingEntityInFront (vec2 pos, float range, Transform::FrontFaceDirection direction, std::function< bool(std::shared_ptr< T >)> filter)
template<typename T >
static constexpr std::shared_ptr< T > getClosestMatchingEntity (vec2 pos, float range, std::function< bool(std::shared_ptr< T >)> filter)
static std::shared_ptr< Entity > getClosestMatchingFurniture (const Transform &transform, float range, std::function< bool(std::shared_ptr< Furniture >)> filter)
template<typename T >
static std::shared_ptr< Entity > getClosestWithComponent (const std::shared_ptr< Entity > &entity, float range)
template<typename T >
static std::vector< std::shared_ptr< Entity > > getAllWithComponent ()
static std::vector< std::shared_ptr< Entity > > getAllWithName (const std::string name)
static void invalidatePathCacheLocation (vec2 pos)
static void invalidatePathCache ()
static bool isWalkable (vec2 pos)
static bool isWalkableRawEntities (const vec2 &pos)
Member Enumeration Documentation
ForEachFlow
enum EntityHelper::ForEachFlow
Enumerator
NormalFlow
Continue
Break
Member Function Documentation
addEntity()
static void EntityHelper::addEntity (std::shared_ptr< Entity > e) [inline], [static]
References get_entities().
Referenced by generation::helper::generate(), generate_and_insert_walls(), LobbyMapInfo::generate_map(), system_manager::process_spawner(), and CustomerSpawner::spawn().
cleanup()
static void EntityHelper::cleanup () [inline], [static]
References get_entities().
Referenced by LevelInfo::grab_things().
forEachEntity()
static void EntityHelper::forEachEntity (std::function< ForEachFlow(std::shared_ptr< Entity > &)> cb) [inline], [static]
References get_entities(), and TRACY_ZONE_SCOPED.
Referenced by isWalkableRawEntities(), and system_manager::person_update_given_new_pos().
get_entities()
static Entities & EntityHelper::get_entities () [inline], [static]
References client_entities_DO_NOT_USE, is_server(), and server_entities_DO_NOT_USE.
Referenced by addEntity(), cleanup(), forEachEntity(), getAllWithComponent(), getAllWithName(), getClosestMatchingEntity(), getEntitiesInRange(), getFirstMatching(), getMatchingEntityInFront(), LevelInfo::grab_things(), removeEntity(), and SystemManager::update_all_entities().
getAllWithComponent()
template<typename T >
static std::vector< std::shared_ptr< Entity > > EntityHelper::getAllWithComponent () [inline], [static]
References get_entities().
getAllWithName()
static std::vector< std::shared_ptr< Entity > > EntityHelper::getAllWithName (const std::string name) [inline], [static]
References get_entities(), and DebugName::name().
Referenced by system_manager::job_system::ensure_has_job(), and system_manager::sophie().
getClosestMatchingEntity()
template<typename T >
static constexpr std::shared_ptr< T > EntityHelper::getClosestMatchingEntity (vec2 pos, float range, std::function< bool(std::shared_ptr< T >)> filter) [inline], [static], [constexpr]
References Transform::as2(), vec::distance(), and get_entities().
getClosestMatchingFurniture()
static std::shared_ptr< Entity > EntityHelper::getClosestMatchingFurniture (const Transform & transform, float range, std::function< bool(std::shared_ptr< Furniture >)> filter) [inline], [static]
References Transform::as2(), and Transform::face_direction().
Referenced by system_manager::input_process_manager::inround::handle_drop(), system_manager::input_process_manager::inround::handle_grab(), system_manager::input_process_manager::planning::handle_grab_or_drop(), system_manager::highlight_facing_furniture(), system_manager::process_conveyer_items(), system_manager::input_process_manager::planning::rotate_furniture(), and system_manager::input_process_manager::inround::work_furniture().
getClosestWithComponent()
template<typename T >
static std::shared_ptr< Entity > EntityHelper::getClosestWithComponent (const std::shared_ptr< Entity > & entity, float range) [inline], [static]
References Transform::as2().
getEntitiesInRange()
template<typename T >
static constexpr std::vector< std::shared_ptr< T > > EntityHelper::getEntitiesInRange (vec2 pos, float range) [inline], [static], [constexpr]
References Transform::as2(), vec::distance(), and get_entities().
getFirstMatching()
template<typename T >
static constexpr std::shared_ptr< T > EntityHelper::getFirstMatching (std::function< bool(std::shared_ptr< T >)> filter) [inline], [static], [constexpr]
References get_entities().
getMatchingEntityInFront()
template<typename T >
static std::shared_ptr< T > EntityHelper::getMatchingEntityInFront (vec2 pos, float range, Transform::FrontFaceDirection direction, std::function< bool(std::shared_ptr< T >)> filter) [inline], [static]
References Transform::as2(), vec::distance(), get_entities(), log_warn, vec::snap(), Transform::snap_position(), Transform::tile_infront_given_pos(), vec::to2(), TRACY_ZONE_SCOPED, and VALIDATE.
invalidatePathCache()
static void EntityHelper::invalidatePathCache () [inline], [static]
References cache_is_walkable.
Referenced by GameMapInfo::generate_map(), GameDebugLayer::onKeyPressed(), GameDebugLayer::toggle_to_inround(), and GameDebugLayer::toggle_to_planning().
invalidatePathCacheLocation()
static void EntityHelper::invalidatePathCacheLocation (vec2 pos) [inline], [static]
References cache_is_walkable.
isWalkable()
static bool EntityHelper::isWalkable (vec2 pos) [inline], [static]
References cache_is_walkable, isWalkableRawEntities(), and TRACY_ZONE_SCOPED.
Referenced by create_wandering_job(), GameMapInfo::get_rand_walkable(), GameMapInfo::get_rand_walkable_register(), Job::travel_to_position(), and generation::helper::validate().
isWalkableRawEntities()
static bool EntityHelper::isWalkableRawEntities (const vec2 & pos) [inline], [static]
References Continue, vec::distance(), forEachEntity(), is_collidable(), TILESIZE, and TRACY_ZONE_SCOPED.
Referenced by isWalkable().
removeEntity()
static void EntityHelper::removeEntity (std::shared_ptr< Entity > e) [inline], [static]
References get_entities().
The documentation for this struct was generated from the following file:
src/entityhelper.h