Conveyer Struct Reference
#include <conveyer.h>
Public Member Functions
void add_static_components ()
Conveyer ()
Conveyer (vec2 pos, Color c=BLUE)
void update_model ()
bool can_take_item_from () const
virtual void in_round_update (float dt) override
Public Member Functions inherited from Furniture
Furniture (vec3 pos, Color)
Furniture (vec2 pos, Color)
virtual bool add_to_navmesh () override
virtual bool can_rotate () const
virtual bool can_be_picked_up ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr) override
virtual bool has_held_item () const
Public Member Functions inherited from Entity
template<typename T >
bool has () const
template<typename T , typename... TArgs>
T & addComponent (TArgs &&... args)
template<typename T >
T & get () const
Entity (vec3 p)
Entity (vec2 p)
virtual ~Entity ()
virtual void announce (std::string text)
virtual bool collides (BoundingBox b) const
virtual BoundingBox raw_bounds () const
virtual BoundingBox bounds () const
vec3 snap_position () const
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void update (float dt) final
Public Attributes
float relative_item_pos = Conveyer::ITEM_START
float SPEED = 0.5f
bool can_take_from = false
Public Attributes inherited from Entity
int id
ComponentBitSet componentSet
ComponentArray componentArray
bool cleanup = false
bool is_held = false
Static Public Attributes
static constexpr float ITEM_START = -0.5f
static constexpr float ITEM_END = 0.5f
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, Transform::Transform::FrontFaceDirection direction)
static Entity * create_entity (vec3 pos, Color face_color, Color base_color)
static Entity * create_person (vec3 pos, Color face_color, Color base_color)
static Entity * create_aiperson (vec3 pos, Color face_color, Color base_color)
static Entity * create_customer (vec2 pos, Color base_color)
Protected Member Functions inherited from Furniture
Furniture ()
void add_static_components ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void in_round_update (float)
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Constructor & Destructor Documentation
Conveyer() [1/2]
Conveyer::Conveyer () [inline]
Conveyer() [2/2]
Conveyer::Conveyer (vec2 pos, Color c = BLUE) [inline]
References add_static_components(), and update_model().
Member Function Documentation
add_static_components()
void Conveyer::add_static_components () [inline]
References Transform::BACK, Transform::face_direction, Transform::FORWARD, Transform::LEFT, Transform::position, Transform::RIGHT, and TILESIZE.
Referenced by Conveyer().
can_take_item_from()
bool Conveyer::can_take_item_from () const [inline]
References can_take_from.
Referenced by Grabber::in_round_update().
in_round_update()
virtual void Conveyer::in_round_update (float dt) [inline], [override], [virtual]
Reimplemented from Entity.
Reimplemented in Grabber.
References Transform::as2(), can_take_from, Transform::face_direction, Item::FURNITURE, Entity::in_round_update(), CanHoldItem::item(), ITEM_END, ITEM_START, relative_item_pos, and SPEED.
Referenced by Grabber::in_round_update().
serialize()
template<typename S >
void Conveyer::serialize (S & s) [inline], [private]
References relative_item_pos.
update_model()
void Conveyer::update_model () [inline]
References ModelInfo::model_name.
Referenced by Conveyer().
Member Data Documentation
can_take_from
bool Conveyer::can_take_from = false
Referenced by can_take_item_from(), and in_round_update().
ITEM_END
constexpr float Conveyer::ITEM_END = 0.5f [static], [constexpr]
Referenced by in_round_update().
ITEM_START
constexpr float Conveyer::ITEM_START = -0.5f [static], [constexpr]
Referenced by in_round_update(), and Grabber::in_round_update().
relative_item_pos
float Conveyer::relative_item_pos = Conveyer::ITEM_START
Referenced by in_round_update(), Grabber::in_round_update(), and serialize().
SPEED
float Conveyer::SPEED = 0.5f
Referenced by in_round_update().
The documentation for this struct was generated from the following file:
src/furniture/conveyer.h