src/engine/trie.h File Reference
#include <map>
#include <optional>
#include <string>
#include <vector>
#include `../util.h`
#include `assert.h`
Classes
struct Trie
struct Trie::Node
Functions
std::ostream & operator<< (std::ostream &os, const Trie::Node &obj)
std::ostream & operator<< (std::ostream &os, const Trie &obj)
void test_trie_insert_once ()
void test_trie_insert_once_and_found ()
void test_trie_insert_once_missing ()
void test_trie_insert_once_and_dump ()
void test_trie_insert_ten ()
void test_trie_insert_ten_and_found ()
void test_trie_insert_ten_and_dump ()
void test_trie_insert_ten_similar_and_dump_prefix ()
void test_trie ()
Function Documentation
operator<<() [1/2]
std::ostream & operator<< (std::ostream & os, const Trie & obj) [inline]
References Trie::root.
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const Trie::Node & obj) [inline]
References Trie::Node::children, and Trie::Node::letter.
test_trie()
void test_trie () [inline]
References test_trie_insert_once(), test_trie_insert_once_and_dump(), test_trie_insert_once_and_found(), test_trie_insert_once_missing(), test_trie_insert_ten(), test_trie_insert_ten_and_dump(), test_trie_insert_ten_and_found(), and test_trie_insert_ten_similar_and_dump_prefix().
test_trie_insert_once()
void test_trie_insert_once () [inline]
References Trie::add().
Referenced by test_trie().
test_trie_insert_once_and_dump()
void test_trie_insert_once_and_dump () [inline]
References Trie::add(), Trie::dump(), and M_ASSERT.
Referenced by test_trie().
test_trie_insert_once_and_found()
void test_trie_insert_once_and_found () [inline]
References Trie::add(), Trie::contains(), and M_ASSERT.
Referenced by test_trie().
test_trie_insert_once_missing()
void test_trie_insert_once_missing () [inline]
References Trie::add(), Trie::contains(), and M_ASSERT.
Referenced by test_trie().
test_trie_insert_ten()
void test_trie_insert_ten () [inline]
References Trie::add(), and util::split_re().
Referenced by test_trie().
test_trie_insert_ten_and_dump()
void test_trie_insert_ten_and_dump () [inline]
References Trie::add(), Trie::dump(), M_ASSERT, and util::split_re().
Referenced by test_trie().
test_trie_insert_ten_and_found()
void test_trie_insert_ten_and_found () [inline]
References Trie::add(), Trie::contains(), M_ASSERT, and util::split_re().
Referenced by test_trie().
test_trie_insert_ten_similar_and_dump_prefix()
void test_trie_insert_ten_similar_and_dump_prefix () [inline]
References Trie::add(), Trie::dump(), M_ASSERT, and util::split_re().
Referenced by test_trie().