ui::IUIContextRenderTextures Struct Reference
#include <ui_context.h>
Public Member Functions
int get_new_render_texture ()
void turn_on_render_texture (int rt_index)
void turn_off_texture_mode ()
void draw_texture (int rt_id, Rectangle source, vec2 position)
void unload_all_render_textures ()
Public Attributes
std::vector< raylib::RenderTexture2D > render_textures
Member Function Documentation
draw_texture()
void ui::IUIContextRenderTextures::draw_texture (int rt_id, Rectangle source, vec2 position) [inline]
References render_textures.
Referenced by ui::UIContext::schedule_render_texture(), and ui::scroll_view().
get_new_render_texture()
int ui::IUIContextRenderTextures::get_new_render_texture () [inline]
References render_textures, WIN_H(), and WIN_W().
Referenced by ui::scroll_view().
turn_off_texture_mode()
void ui::IUIContextRenderTextures::turn_off_texture_mode () [inline]
Referenced by ui::scroll_view().
turn_on_render_texture()
void ui::IUIContextRenderTextures::turn_on_render_texture (int rt_index) [inline]
References render_textures.
Referenced by ui::scroll_view().
unload_all_render_textures()
void ui::IUIContextRenderTextures::unload_all_render_textures () [inline]
References render_textures.
Referenced by ui::UIContext::begin().
Member Data Documentation
render_textures
std::vector<raylib::RenderTexture2D> ui::IUIContextRenderTextures::render_textures
Referenced by draw_texture(), get_new_render_texture(), turn_on_render_texture(), and unload_all_render_textures().
The documentation for this struct was generated from the following file:
src/engine/ui_context.h