ui::UIContext Struct Reference
#include <ui_context.h>
Public Member Functions
UIContext ()
std::shared_ptr< Widget > own (const Widget &widget)
virtual void init () override
virtual void begin (float dt) override
void end (Widget *tree_root)
bool matching_id_in_tree (uuid &id, Widget *tree_root)
void reset_tabbing_if_not_visible (Widget *tree_root)
void cleanup () override
template<typename T >
std::shared_ptr< T > widget_init (const uuid id)
template<typename T >
std::shared_ptr< T > get_widget_state (const uuid id)
void render_all ()
void schedule_render_call (std::function< void()> cb)
void _draw_text (Rectangle rect, const std::string &content, theme::Usage color_usage)
void draw_text (Widget *widget, const std::string &content, theme::Usage color_usage)
void schedule_draw_text (Widget *widget, const std::string &content, theme::Usage color_usage)
void draw_widget_rect (Rectangle rect, theme::Usage usage)
void draw_widget (Widget widget, theme::Usage usage)
vec2 widget_center (vec2 position, vec2 size) const
std::shared_ptr< Widget > make_temp_widget (Widget *widget)
void schedule_render_texture (int rt_id, Rectangle source, vec2 position)
Public Member Functions inherited from ui::IUIContextInputManager
virtual ~IUIContextInputManager ()
virtual void init ()
virtual void begin (float dt)
virtual void cleanup ()
bool is_mouse_inside (const Rectangle &rect) const
bool process_char_press_event (CharPressedEvent event)
bool process_keyevent (KeyPressedEvent event)
bool process_gamepad_button_event (GamepadButtonPressedEvent event)
bool process_gamepad_axis_event (GamepadAxisMovedEvent event)
bool _pressedButtonWithoutEat (GamepadButton butt) const
bool pressedButtonWithoutEat (const InputName &name) const
void eatButton ()
bool pressed (const InputName &name)
void handleBadGamepadAxis (const KeyMapInputRequestError &, menu::State, const InputName)
void eatAxis ()
bool _pressedWithoutEat (int code) const
bool pressedWithoutEat (const InputName &name) const
void eatKey ()
bool is_held_down_debounced (const InputName &name)
bool is_held_down (const InputName &name)
Public Member Functions inherited from ui::IUIContextLastFrame
LastFrame get_last_frame (uuid id) const
void write_last_frame (const uuid &id, LastFrame f)
void reset_last_frame ()
Public Member Functions inherited from ui::IUIContextRenderTextures
int get_new_render_texture ()
void turn_on_render_texture (int rt_index)
void turn_off_texture_mode ()
void draw_texture (int rt_id, Rectangle source, vec2 position)
void unload_all_render_textures ()
Public Member Functions inherited from ui::IUIContextTheming
virtual void init ()
void push_theme (UITheme theme)
void pop_theme ()
UITheme active_theme () const
Public Member Functions inherited from ui::IUIContextParentStacking
void push_parent (Widget *widget)
void pop_parent ()
Widget * active_parent ()
void push_parent (std::shared_ptr< Widget > widget)
void add_child (Widget *child)
Public Member Functions inherited from FontSizeCache
virtual void init ()
void set_font (raylib::Font f)
float get_font_size_impl (const std::string &content, float width, float height, float spacing) const
float get_font_size (const std::string &content, float width, float height, float spacing)
Static Public Member Functions
static UIContext * create ()
static UIContext & get ()
Public Attributes
StateManager statemanager
std::vector< std::shared_ptr< Widget > > internal_roots
std::vector< std::shared_ptr< Widget > > owned_widgets
uuid hot_id
uuid active_id
uuid kb_focus_id
uuid last_processed
bool began_and_not_ended = false
std::vector< std::function< void()> > queued_render_calls
Public Attributes inherited from ui::IUIContextInputManager
MouseInfo mouse_info
int key = -1
int mod = -1
GamepadButton button
GamepadAxisWithDir axis_info
int keychar = -1
int modchar = -1
float yscrolled
float keyHeldDownTimer = 0.f
float prevKeyHeldDownTimer = 0.f
float keyHeldDownTimerReset = 0.15f
float lastDt
Public Attributes inherited from ui::IUIContextLastFrame
std::map< uuid, LastFrame > last_frame
Public Attributes inherited from ui::IUIContextRenderTextures
std::vector< raylib::RenderTexture2D > render_textures
Public Attributes inherited from ui::IUIContextTheming
std::stack< UITheme > themestack
Public Attributes inherited from ui::IUIContextParentStacking
std::stack< Widget * > parentstack
Public Attributes inherited from FontSizeCache
raylib::Font font
std::unordered_map< size_t, float > _font_size_memo
Private Attributes
std::vector< std::shared_ptr< Widget > > temp_widgets
Constructor & Destructor Documentation
UIContext()
ui::UIContext::UIContext () [inline]
References init().
Referenced by create().
Member Function Documentation
_draw_text()
void ui::UIContext::_draw_text (Rectangle rect, const std::string & content, theme::Usage color_usage) [inline]
References ui::IUIContextTheming::active_theme(), FontSizeCache::get_font_size(), and log_trace.
Referenced by ui::button(), draw_text(), and ui::textfield().
begin()
virtual void ui::UIContext::begin (float dt) [inline], [override], [virtual]
Reimplemented from ui::IUIContextInputManager.
References began_and_not_ended, ui::IUIContextInputManager::begin(), ui::globalContext, hot_id, ui::ROOT_ID, ui::IUIContextRenderTextures::unload_all_render_textures(), and VALIDATE.
cleanup()
void ui::UIContext::cleanup () [inline], [override], [virtual]
Reimplemented from ui::IUIContextInputManager.
References active_id, began_and_not_ended, ui::IUIContextInputManager::cleanup(), ui::FAKE_ID, ui::globalContext, MouseInfo::leftDown, ui::IUIContextInputManager::mouse_info, owned_widgets, ui::IUIContextLastFrame::reset_last_frame(), ui::ROOT_ID, and temp_widgets.
Referenced by end().
create()
static UIContext * ui::UIContext::create () [inline], [static]
References UIContext().
Referenced by get().
draw_text()
void ui::UIContext::draw_text (Widget * widget, const std::string & content, theme::Usage color_usage) [inline]
References _draw_text(), and ui::Widget::rect.
Referenced by schedule_draw_text().
draw_widget()
void ui::UIContext::draw_widget (Widget widget, theme::Usage usage) [inline]
References draw_widget_rect(), and ui::Widget::rect.
Referenced by ui::slider(), and ui::textfield().
draw_widget_rect()
void ui::UIContext::draw_widget_rect (Rectangle rect, theme::Usage usage) [inline]
References ui::IUIContextTheming::active_theme().
Referenced by ui::button(), draw_widget(), and ui::slider().
end()
void ui::UIContext::end (Widget * tree_root) [inline]
References cleanup(), ui::autolayout::process_widget(), render_all(), and reset_tabbing_if_not_visible().
get()
static UIContext & ui::UIContext::get () [inline], [static]
References ui::_uicontext, create(), and ui::globalContext.
Referenced by ui::get(), schedule_draw_text(), and schedule_render_texture().
get_widget_state()
template<typename T >
std::shared_ptr< T > ui::UIContext::get_widget_state (const uuid id) [inline]
References ui::StateManager::get_as(), and statemanager.
Referenced by ui::slider(), and ui::textfield().
init()
virtual void ui::UIContext::init () [inline], [override], [virtual]
Reimplemented from FontSizeCache.
References active_id, began_and_not_ended, hot_id, FontSizeCache::init(), ui::IUIContextInputManager::init(), ui::IUIContextTheming::init(), kb_focus_id, and ui::ROOT_ID.
Referenced by UIContext().
make_temp_widget()
std::shared_ptr< Widget > ui::UIContext::make_temp_widget (Widget * widget) [inline]
References temp_widgets.
Referenced by ui::button_list(), and ui::dropdown().
matching_id_in_tree()
bool ui::UIContext::matching_id_in_tree (uuid & id, Widget * tree_root) [inline]
References ui::Widget::children, ui::Widget::id, and matching_id_in_tree().
Referenced by matching_id_in_tree(), and reset_tabbing_if_not_visible().
own()
std::shared_ptr< Widget > ui::UIContext::own (const Widget & widget) [inline]
References owned_widgets.
Referenced by ui::components::mk_but_pad(), ui::components::mk_button(), ui::components::mk_column(), ui::components::mk_icon_button(), ui::components::mk_padding(), ui::components::mk_root(), ui::components::mk_row(), ui::components::mk_text(), and ui::components::mk_text_id().
render_all()
void ui::UIContext::render_all () [inline]
References queued_render_calls.
Referenced by end().
reset_tabbing_if_not_visible()
void ui::UIContext::reset_tabbing_if_not_visible (Widget * tree_root) [inline]
References kb_focus_id, matching_id_in_tree(), and ui::ROOT_ID.
Referenced by end().
schedule_draw_text()
void ui::UIContext::schedule_draw_text (Widget * widget, const std::string & content, theme::Usage color_usage) [inline]
References draw_text(), get(), and schedule_render_call().
Referenced by ui::text().
schedule_render_call()
void ui::UIContext::schedule_render_call (std::function< void()> cb) [inline]
References queued_render_calls.
Referenced by ui::init_widget(), schedule_draw_text(), and schedule_render_texture().
schedule_render_texture()
void ui::UIContext::schedule_render_texture (int rt_id, Rectangle source, vec2 position) [inline]
References ui::IUIContextRenderTextures::draw_texture(), get(), and schedule_render_call().
widget_center()
vec2 ui::UIContext::widget_center (vec2 position, vec2 size) const [inline]
widget_init()
template<typename T >
std::shared_ptr< T > ui::UIContext::widget_init (const uuid id) [inline]
References ui::StateManager::getAndCreateIfNone(), log_error, and statemanager.
Referenced by ui::button_list(), ui::checkbox(), ui::dropdown(), ui::scroll_view(), ui::slider(), and ui::textfield().
Member Data Documentation
active_id
uuid ui::UIContext::active_id
Referenced by ui::active_if_mouse_inside(), cleanup(), init(), and ui::slider().
began_and_not_ended
bool ui::UIContext::began_and_not_ended = false
Referenced by begin(), cleanup(), and init().
hot_id
uuid ui::UIContext::hot_id
Referenced by ui::active_if_mouse_inside(), begin(), and init().
internal_roots
std::vector<std::shared_ptr<Widget> > ui::UIContext::internal_roots
kb_focus_id
uuid ui::UIContext::kb_focus_id
Referenced by ui::button(), ui::button_list(), ui::dropdown(), ui::handle_tabbing(), init(), reset_tabbing_if_not_visible(), ui::slider(), ui::textfield(), and ui::try_to_grab_kb().
last_processed
uuid ui::UIContext::last_processed
Referenced by ui::handle_tabbing().
owned_widgets
std::vector<std::shared_ptr<Widget> > ui::UIContext::owned_widgets
Referenced by cleanup(), and own().
queued_render_calls
std::vector<std::function<void()> > ui::UIContext::queued_render_calls
Referenced by render_all(), and schedule_render_call().
statemanager
StateManager ui::UIContext::statemanager
Referenced by get_widget_state(), and widget_init().
temp_widgets
std::vector<std::shared_ptr<Widget> > ui::UIContext::temp_widgets [private]
Referenced by cleanup(), and make_temp_widget().
The documentation for this struct was generated from the following file:
src/engine/ui_context.h