src/vec_util.h File Reference
#include `external_include.h`
#include `globals.h`
Namespaces
namespace vec
Macros
#define EPSILON 0.000001f
Functions
static void forEachNeighbor (int i, int j, std::function< void(const vec2 &)> cb, int step=1)
static std::vector< vec2 > get_neighbors (int i, int j, int step=1)
float comp_max (const vec2 &a)
constexpr BoundingBox get_bounds (vec3 position, vec3 size)
float constexpr vec::newton_raphson (float x, float cur, float prev)
float constexpr vec::ce_sqrtf (float x)
constexpr float vec::distance (vec2 a, vec2 b)
float vec::dot2 (const vec2 &a, const vec2 &b)
vec2 vec::norm (const vec2 &a)
constexpr vec3 vec::to3 (vec2 position)
constexpr vec2 vec::to2 (vec3 position)
vec2 vec::snap (vec2 position)
vec3 vec::snap (vec3 position)
Variables
static constexpr int neigh_x [8] = {-1, -1, -1, 0, 0, 1, 1, 1}
static constexpr int neigh_y [8] = {-1, 0, 1, -1, 1, -1, 0, 1}
Macro Definition Documentation
EPSILON
#define EPSILON 0.000001f
Function Documentation
comp_max()
float comp_max (const vec2 & a) [inline]
forEachNeighbor()
static void forEachNeighbor (int i, int j, std::function< void(const vec2 &)> cb, int step = 1) [static]
References neigh_x, and neigh_y.
Referenced by get_neighbors(), and astar::get_neighbors().
get_bounds()
constexpr BoundingBox get_bounds (vec3 position, vec3 size) [constexpr]
Referenced by Transform::bounds(), Entity::bounds(), Item::bounds(), Person::handle_collision(), EntityHelper::isWalkableRawEntities(), Transform::raw_bounds(), Entity::raw_bounds(), and Item::raw_bounds().
get_neighbors()
static std::vector< vec2 > get_neighbors (int i, int j, int step = 1) [static]
References forEachNeighbor().
Referenced by astar::find_path_impl().
Variable Documentation
neigh_x
constexpr int neigh_x[8] = {-1, -1, -1, 0, 0, 1, 1, 1} [static], [constexpr]
Referenced by forEachNeighbor().
neigh_y
constexpr int neigh_y[8] = {-1, 0, 1, -1, 1, -1, 0, 1} [static], [constexpr]
Referenced by forEachNeighbor().