Map Struct Reference
#include <map.h>
Public Member Functions
Map (const std::string &_seed=`default_seed`)
void update_seed (const std::string &s)
Items items () const
Entities entities () const
void onUpdate (float dt)
void onDraw (float dt) const
void onDrawUI (float dt)
bool in_lobby_state () const
void ensure_generated_map ()
void grab_things ()
Public Attributes
LobbyMapInfo lobby_info
GameMapInfo game_info
std::vector< std::shared_ptr< RemotePlayer > > remote_players_NOT_SERIALIZED
std::string seed
Private Member Functions
template<typename S >
void serialize (S &s)
Constructor & Destructor Documentation
Map()
Map::Map (const std::string & _seed = `default_seed`) [inline]
References seed, and update_seed().
Member Function Documentation
ensure_generated_map()
void Map::ensure_generated_map () [inline]
entities()
Entities Map::entities () const [inline]
References LevelInfo::entities, game_info, in_lobby_state(), and lobby_info.
Referenced by network::Client::client_process_message_string().
grab_things()
void Map::grab_things () [inline]
References game_info, LevelInfo::grab_things(), in_lobby_state(), and lobby_info.
Referenced by GameLayer::onUpdate().
in_lobby_state()
bool Map::in_lobby_state () const [inline]
References game::Lobby.
Referenced by entities(), grab_things(), items(), onDraw(), onDrawUI(), and onUpdate().
items()
Items Map::items () const [inline]
References game_info, in_lobby_state(), LevelInfo::items, and lobby_info.
Referenced by network::Client::client_process_message_string().
onDraw()
void Map::onDraw (float dt) const [inline]
References game_info, in_lobby_state(), lobby_info, log_warn, LevelInfo::onDraw(), LobbyMapInfo::onDraw(), remote_players_NOT_SERIALIZED, system_manager::render_normal(), and TRACY_ZONE_SCOPED.
onDrawUI()
void Map::onDrawUI (float dt) [inline]
References game_info, in_lobby_state(), lobby_info, LevelInfo::onDrawUI(), GameMapInfo::onDrawUI(), and TRACY_ZONE_SCOPED.
onUpdate()
void Map::onUpdate (float dt) [inline]
References LevelInfo::ensure_generated_map(), game_info, in_lobby_state(), lobby_info, LevelInfo::onUpdate(), GameMapInfo::onUpdate(), remote_players_NOT_SERIALIZED, seed, and TRACY_ZONE_SCOPED.
serialize()
template<typename S >
void Map::serialize (S & s) [inline], [private]
References game_info, and lobby_info.
update_seed()
void Map::update_seed (const std::string & s) [inline]
References game_info, and GameMapInfo::update_seed().
Referenced by Map().
Member Data Documentation
game_info
GameMapInfo Map::game_info
Referenced by entities(), grab_things(), items(), onDraw(), onDrawUI(), onUpdate(), serialize(), and update_seed().
lobby_info
LobbyMapInfo Map::lobby_info
Referenced by entities(), grab_things(), items(), onDraw(), onDrawUI(), onUpdate(), and serialize().
remote_players_NOT_SERIALIZED
std::vector<std::shared_ptr<RemotePlayer> > Map::remote_players_NOT_SERIALIZED
Referenced by onDraw(), and onUpdate().
seed
std::string Map::seed
Referenced by Map(), and onUpdate().
The documentation for this struct was generated from the following file:
src/map.h