SoundLibrary Struct Reference
#include <sound_library.h>
Classes
struct SoundLibraryImpl
Public Member Functions
raylib::Sound & get (const std::string &name)
const raylib::Sound & get (const std::string &name) const
void load (const char *filename, const char *name)
void play (const char *name)
void play_random_match (const std::string &prefix)
void unload_all ()
Private Attributes
SoundLibrary::SoundLibraryImpl impl
Member Function Documentation
get() [1/2]
raylib::Sound & SoundLibrary::get (const std::string & name) [inline]
Referenced by system_manager::job_system::handle_job_holder_pushed(), Preload::load_sounds(), and Preload::~Preload().
get() [2/2]
const raylib::Sound & SoundLibrary::get (const std::string & name) const [inline]
load()
void SoundLibrary::load (const char * filename, const char * name) [inline]
play()
void SoundLibrary::play (const char * name) [inline]
play_random_match()
void SoundLibrary::play_random_match (const std::string & prefix) [inline]
unload_all()
void SoundLibrary::unload_all () [inline]
Member Data Documentation
impl
SoundLibrary::SoundLibraryImpl SoundLibrary::impl [private]
The documentation for this struct was generated from the following file:
src/engine/sound_library.h