src/job.cpp File Reference
#include `job.h`
#include `components/can_perform_job.h`
#include `components/has_speech_bubble.h`
#include `components/has_waiting_queue.h`
#include `engine/assert.h`
#include `entity.h`
#include `entityhelper.h`
#include `globals.h`
#include `system/logging_system.h`
Functions
Job * create_wandering_job (vec2 _start)
void WIQ_wait_and_return (const std::shared_ptr< Entity > &entity)
vec2 WIQ_add_to_queue_and_get_position (const std::shared_ptr< Entity > &reg, const std::shared_ptr< Entity > &customer)
int WIQ_position_in_line (const std::shared_ptr< Entity > &reg, const std::shared_ptr< Entity > &customer)
void WIQ_leave_line (const std::shared_ptr< Entity > &reg, const std::shared_ptr< Entity > &customer)
bool WIQ_can_move_up (const std::shared_ptr< Entity > &reg, const std::shared_ptr< Entity > &customer)
Function Documentation
create_wandering_job()
Job * create_wandering_job (vec2 _start) [inline]
References EntityHelper::isWalkable(), and randIn().
Referenced by Job::create_job_of_type().
WIQ_add_to_queue_and_get_position()
vec2 WIQ_add_to_queue_and_get_position (const std::shared_ptr< Entity > & reg, const std::shared_ptr< Entity > & customer) [inline]
References HasWaitingQueue::get_next_pos(), and VALIDATE.
Referenced by WaitInQueueJob::run_state_initialize().
WIQ_can_move_up()
bool WIQ_can_move_up (const std::shared_ptr< Entity > & reg, const std::shared_ptr< Entity > & customer) [inline]
References VALIDATE.
Referenced by WaitInQueueJob::run_state_working_at_start().
WIQ_leave_line()
void WIQ_leave_line (const std::shared_ptr< Entity > & reg, const std::shared_ptr< Entity > & customer) [inline]
References VALIDATE, and WIQ_position_in_line().
Referenced by WaitInQueueJob::run_state_working_at_end().
WIQ_position_in_line()
int WIQ_position_in_line (const std::shared_ptr< Entity > & reg, const std::shared_ptr< Entity > & customer) [inline]
References HasWaitingQueue::has_matching_person(), and VALIDATE.
Referenced by WaitInQueueJob::run_state_initialize(), WaitInQueueJob::run_state_working_at_start(), and WIQ_leave_line().
WIQ_wait_and_return()
void WIQ_wait_and_return (const std::shared_ptr< Entity > & entity) [inline]
References CanPerformJob::job_start(), and CanPerformJob::push_and_reset().
Referenced by WaitInQueueJob::run_state_initialize(), WaitInQueueJob::run_state_working_at_end(), and WaitInQueueJob::run_state_working_at_start().