CanHaveAilment Struct Reference
#include <can_have_ailment.h>
Public Member Functions
virtual ~CanHaveAilment ()
std::shared_ptr< Ailment > ailment () const
bool has_ailment () const
void update (Ailment *new_ailment)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
std::shared_ptr< Ailment > my_ailment
Constructor & Destructor Documentation
 CanHaveAilment()
virtual CanHaveAilment::~CanHaveAilment () [inline], [virtual]
Member Function Documentation
ailment()
std::shared_ptr< Ailment > CanHaveAilment::ailment () const [inline]
References my_ailment.
Referenced by has_ailment(), system_manager::render_manager::render_speech_bubble(), and Job::travel_to_position().
has_ailment()
bool CanHaveAilment::has_ailment () const [inline]
References ailment().
serialize()
template<typename S >
void CanHaveAilment::serialize (S & s) [inline], [private]
References my_ailment.
update()
void CanHaveAilment::update (Ailment * new_ailment) [inline]
References my_ailment.
Member Data Documentation
my_ailment
std::shared_ptr<Ailment> CanHaveAilment::my_ailment [private]
Referenced by ailment(), serialize(), and update().
The documentation for this struct was generated from the following file:
src/components/can_have_ailment.h