system_manager::input_process_manager::planning Namespace Reference
Functions
void rotate_furniture (const std::shared_ptr< Entity > player)
void drop_held_furniture (const std::shared_ptr< Entity > &player)
void handle_grab_or_drop (const std::shared_ptr< Entity > &player)
Function Documentation
drop_held_furniture()
void system_manager::input_process_manager::planning::drop_held_furniture (const std::shared_ptr< Entity > & player) [inline]
References CanHoldFurniture::furniture(), log_info, vec::snap(), Transform::tile_infront(), vec::to3(), and CanHoldFurniture::update().
Referenced by system_manager::handle_autodrop_furniture_when_exiting_planning(), and handle_grab_or_drop().
handle_grab_or_drop()
void system_manager::input_process_manager::planning::handle_grab_or_drop (const std::shared_ptr< Entity > & player) [inline]
References drop_held_furniture(), EntityHelper::getClosestMatchingFurniture(), and CanHighlightOthers::reach().
Referenced by system_manager::input_process_manager::process_input().
rotate_furniture()
void system_manager::input_process_manager::planning::rotate_furniture (const std::shared_ptr< Entity > player) [inline]
References EntityHelper::getClosestMatchingFurniture(), game::Planning, and CanHighlightOthers::reach().
Referenced by system_manager::input_process_manager::process_input().