Person Struct Reference
#include <person.h>
Public Member Functions
Person (vec3 p, Color face_color_in, Color base_color_in)
Person (vec2 p, Color face_color_in, Color base_color_in)
Person (vec3 p, Color c)
Person (vec2 p, Color c)
virtual vec3 update_xaxis_position (float dt)=0
virtual vec3 update_zaxis_position (float dt)=0
virtual float base_speed ()
virtual vec3 size () const override
void select_next_character_model ()
virtual std::optional< ModelInfo > model () const override
void handle_collision (int facedir_x, vec3 new_pos_x, int facedir_z, vec3 new_pos_z)
std::tuple< int, int > get_face_direction (vec3 new_pos_x, vec3 new_pos_z)
void update_facing_direction (int facedir_x, int facedir_z)
virtual void always_update (float dt) override
Public Member Functions inherited from Entity
FrontFaceDirection offsetFaceDirection (FrontFaceDirection startingDirection, float offset) const
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
void update_name (const std::string &new_name)
virtual bool can_take_item_from () const
virtual bool collides (BoundingBox b) const
virtual BoundingBox bounds () const
virtual void update_position (const vec3 &p)
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void render () const final
virtual void update (float dt) final
Protected Member Functions
Person ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual void render_debug_mode () const
virtual void render_highlighted () const
virtual void render_normal () const
virtual void render_floating_name () const
virtual std::optional< ModelInfo > model () const
vec3 snap_position () const
virtual void update_held_item_position ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void always_update (float)
virtual void planning_update (float)
virtual void in_round_update (float)
virtual bool is_snappable ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
std::array< std::string, 3 > character_models
int model_index = 0
Additional Inherited Members
Public Types inherited from Entity
enum FrontFaceDirection { FORWARD = 0x1
, RIGHT = 0x2
, BACK = 0x4
, LEFT = 0x8
 }
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, FrontFaceDirection direction)
Public Attributes inherited from Entity
const std::map< FrontFaceDirection, float > FrontFaceDirectionMap
const std::map< int, FrontFaceDirection > DirectionToFrontFaceMap
int id
vec3 raw_position
vec3 prev_position
vec3 position
vec3 pushed_force {0.0, 0.0, 0.0}
Color face_color
Color base_color
bool cleanup = false
bool is_highlighted = false
bool is_held = false
FrontFaceDirection face_direction = FrontFaceDirection::FORWARD
std::shared_ptr< Item > held_item = nullptr
int name_length = 1
std::string name = ``
Constructor & Destructor Documentation
Person() [1/5]
Person::Person () [inline], [protected]
Person() [2/5]
Person::Person (vec3 p, Color face_color_in, Color base_color_in) [inline]
Person() [3/5]
Person::Person (vec2 p, Color face_color_in, Color base_color_in) [inline]
Person() [4/5]
Person::Person (vec3 p, Color c) [inline]
Person() [5/5]
Person::Person (vec2 p, Color c) [inline]
Member Function Documentation
always_update()
virtual void Person::always_update (float dt) [inline], [override], [virtual]
Reimplemented from Entity.
Reimplemented in Player.
References Entity::always_update(), get_face_direction(), handle_collision(), Entity::pushed_force, update_facing_direction(), update_xaxis_position(), and update_zaxis_position().
base_speed()
virtual float Person::base_speed () [inline], [virtual]
Reimplemented in AIPerson, BasePlayer, and Customer.
get_face_direction()
std::tuple< int, int > Person::get_face_direction (vec3 new_pos_x, vec3 new_pos_z) [inline]
References Entity::BACK, Entity::FORWARD, Entity::LEFT, Entity::raw_position, and Entity::RIGHT.
Referenced by always_update(), and Player::get_position_after_input().
handle_collision()
void Person::handle_collision (int facedir_x, vec3 new_pos_x, int facedir_z, vec3 new_pos_z) [inline]
References Entity::BACK, EntityHelper::Break, EntityHelper::Continue, EntityHelper::forEachEntity(), Entity::FORWARD, get_bounds(), Entity::is_collidable(), Entity::LEFT, EntityHelper::None, Entity::raw_position, Entity::RIGHT, size(), and TILESIZE.
Referenced by always_update(), and Player::get_position_after_input().
model()
virtual std::optional< ModelInfo > Person::model () const [inline], [override], [virtual]
Reimplemented from Entity.
References character_models, and model_index.
select_next_character_model()
void Person::select_next_character_model () [inline]
References character_models, and model_index.
serialize()
template<typename S >
void Person::serialize (S & s) [inline], [private]
References model_index.
size()
virtual vec3 Person::size () const [inline], [override], [virtual]
Reimplemented from Entity.
References TILESIZE.
Referenced by handle_collision().
update_facing_direction()
void Person::update_facing_direction (int facedir_x, int facedir_z) [inline]
References Entity::face_direction.
Referenced by always_update(), and Player::get_position_after_input().
update_xaxis_position()
virtual vec3 Person::update_xaxis_position (float dt) [pure virtual]
Implemented in AIPerson, Player, TargetCube, BasePlayer, and RemotePlayer.
Referenced by always_update().
update_zaxis_position()
virtual vec3 Person::update_zaxis_position (float dt) [pure virtual]
Implemented in AIPerson, Player, TargetCube, BasePlayer, and RemotePlayer.
Referenced by always_update().
Member Data Documentation
character_models
std::array<std::string, 3> Person::character_models [private]
Initial value:
= {
        "character_duck",
        "character_dog",
        "character_bear",
    }
Referenced by model(), and select_next_character_model().
model_index
int Person::model_index = 0 [private]
Referenced by model(), select_next_character_model(), and serialize().
The documentation for this struct was generated from the following file:
src/person.h