GameState Struct Reference
#include <statemanager.h>
Public Member Functions
virtual game::State default_value () const override
game::State pause ()
bool in_round () const
bool is_paused () const
bool is_paused_in (game::State s) const
bool is_lobby_like ()
game::State toggle_planning ()
Public Member Functions inherited from StateManager2< game::State >
game::State read () const
game::State previous () const
game::State go_back ()
void clear_history ()
bool is (game::State s) const
bool is_not (game::State s) const
const std::string_view tostring () const
void register_on_change (const std::function< void(game::State, game::State)> &nfunc)
void set (game::State ns)
virtual game::State default_value () const=0
void reset ()
virtual ~StateManager2 ()
Static Public Member Functions
static game::State s_pause ()
static bool s_in_round ()
static bool s_is_paused ()
static bool is_update_state (game::State s)
static bool s_should_update ()
static bool s_should_prev_update ()
static bool s_should_draw ()
static bool s_is_lobby_like ()
static game::State s_toggle_planning ()
static void s_toggle_to_planning ()
static void s_toggle_to_inround ()
Member Function Documentation
default_value()
virtual game::State GameState::default_value () const [inline], [override], [virtual]
Implements StateManager2< game::State >.
References game::InMenu.
in_round()
bool GameState::in_round () const [inline]
References game::InRound.
is_lobby_like()
bool GameState::is_lobby_like () [inline]
References game::Lobby.
is_paused()
bool GameState::is_paused () const [inline]
References game::Paused.
is_paused_in()
bool GameState::is_paused_in (game::State s) const [inline]
References game::Paused.
is_update_state()
static bool GameState::is_update_state (game::State s) [inline], [static]
References game::InRound, game::Lobby, and game::Planning.
pause()
game::State GameState::pause () [inline]
References game::Paused.
s_in_round()
static bool GameState::s_in_round () [inline], [static]
Referenced by system_manager::input_process_manager::process_input(), system_manager::ui::render_timer(), HasTimer::store_is_closed(), and SystemManager::update().
s_is_lobby_like()
static bool GameState::s_is_lobby_like () [inline], [static]
s_is_paused()
static bool GameState::s_is_paused () [inline], [static]
s_pause()
static game::State GameState::s_pause () [inline], [static]
Referenced by GameLayer::onGamepadButtonPressed(), and GameLayer::onKeyPressed().
s_should_draw()
static bool GameState::s_should_draw () [inline], [static]
s_should_prev_update()
static bool GameState::s_should_prev_update () [inline], [static]
References game::Paused.
s_should_update()
static bool GameState::s_should_update () [inline], [static]
Referenced by GameLayer::onUpdate().
s_toggle_planning()
static game::State GameState::s_toggle_planning () [inline], [static]
s_toggle_to_inround()
static void GameState::s_toggle_to_inround () [inline], [static]
References game::InRound.
Referenced by GameDebugLayer::toggle_to_inround().
s_toggle_to_planning()
static void GameState::s_toggle_to_planning () [inline], [static]
References game::Planning.
Referenced by entities::make_trigger_area(), and GameDebugLayer::toggle_to_planning().
toggle_planning()
game::State GameState::toggle_planning () [inline]
References game::InRound, and game::Planning.
The documentation for this struct was generated from the following file:
src/engine/statemanager.h