Polygon Struct Reference
#include <polygon.h>
Classes
struct CompareVec
Public Member Functions
Polygon ()
Polygon (Rectangle rect)
std::vector< vec3 > as_3d ()
int orientation (vec2 a, vec2 b, vec2 c) const
float sqDist (vec2 p1, vec2 p2) const
vec2 centroid () const
float maxradius () const
bool inside (vec2 p) const
void add (vec2 p)
float cross (vec2 o, vec2 a, vec2 b) const
void remove (vec2 p)
void andrew_chain ()
void grahamScan (vec2 p)
Public Attributes
std::vector< vec2 > points
std::vector< vec2 > hull
Constructor & Destructor Documentation
Polygon() [1/2]
Polygon::Polygon () [inline]
Polygon() [2/2]
Polygon::Polygon (Rectangle rect) [inline]
References add().
Member Function Documentation
add()
void Polygon::add (vec2 p) [inline]
References andrew_chain(), hull, and points.
Referenced by Polygon().
andrew_chain()
void Polygon::andrew_chain () [inline]
References cross(), hull, and points.
Referenced by add(), and remove().
as_3d()
std::vector< vec3 > Polygon::as_3d () [inline]
References hull, and vec::to3().
centroid()
vec2 Polygon::centroid () const [inline]
References hull.
Referenced by maxradius().
cross()
float Polygon::cross (vec2 o, vec2 a, vec2 b) const [inline]
Referenced by andrew_chain().
grahamScan()
void Polygon::grahamScan (vec2 p) [inline]
References hull, inside(), orientation(), and sqDist().
inside()
bool Polygon::inside (vec2 p) const [inline]
References hull.
Referenced by grahamScan(), NavMesh::overlap(), and remove().
maxradius()
float Polygon::maxradius () const [inline]
References centroid(), hull, and sqDist().
orientation()
int Polygon::orientation (vec2 a, vec2 b, vec2 c) const [inline]
Referenced by grahamScan().
remove()
void Polygon::remove (vec2 p) [inline]
References andrew_chain(), inside(), log_trace, log_warn, and points.
sqDist()
float Polygon::sqDist (vec2 p1, vec2 p2) const [inline]
Referenced by grahamScan(), and maxradius().
Member Data Documentation
hull
std::vector<vec2> Polygon::hull
Referenced by add(), andrew_chain(), as_3d(), centroid(), grahamScan(), inside(), and maxradius().
points
std::vector<vec2> Polygon::points
Referenced by add(), andrew_chain(), NavMesh::overlap(), and remove().
The documentation for this struct was generated from the following file:
src/engine/polygon.h