LevelInfo Struct Reference
#include <level_info.h>
Public Member Functions
virtual void onUpdate (float dt)
virtual void onDraw (float dt) const
virtual void onDrawUI (float)
void grab_things ()
void ensure_generated_map (const std::string &new_seed)
virtual void generate_map ()=0
Public Attributes
bool was_generated = false
SystemManager system_manager
Entities entities
Entities::size_type num_entities
Items items
Items::size_type num_items
std::string seed
Private Member Functions
template<typename S >
void serialize (S &s)
Member Function Documentation
ensure_generated_map()
void LevelInfo::ensure_generated_map (const std::string & new_seed) [inline]
References generate_map(), seed, and was_generated.
Referenced by Map::onUpdate().
generate_map()
virtual void LevelInfo::generate_map () [pure virtual]
Implemented in LobbyMapInfo, and GameMapInfo.
Referenced by ensure_generated_map().
grab_things()
void LevelInfo::grab_things () [inline]
References EntityHelper::cleanup(), entities, EntityHelper::get_entities(), ItemHelper::get_items(), items, num_entities, and num_items.
Referenced by Map::grab_things().
onDraw()
virtual void LevelInfo::onDraw (float dt) const [inline], [virtual]
Reimplemented in LobbyMapInfo.
References entities, items, log_warn, and TRACY_ZONE_SCOPED.
Referenced by Map::onDraw(), and LobbyMapInfo::onDraw().
onDrawUI()
virtual void LevelInfo::onDrawUI (float) [inline], [virtual]
Reimplemented in GameMapInfo.
Referenced by Map::onDrawUI().
onUpdate()
virtual void LevelInfo::onUpdate (float dt) [inline], [virtual]
Reimplemented in GameMapInfo.
References TRACY_ZONE_SCOPED.
Referenced by Map::onUpdate(), and GameMapInfo::onUpdate().
serialize()
template<typename S >
void LevelInfo::serialize (S & s) [inline], [private]
References entities, items, MAX_SEED_LENGTH, num_entities, num_items, seed, and was_generated.
Member Data Documentation
entities
Entities LevelInfo::entities
Referenced by Map::entities(), grab_things(), onDraw(), and serialize().
items
Items LevelInfo::items
Referenced by grab_things(), Map::items(), onDraw(), and serialize().
num_entities
Entities::size_type LevelInfo::num_entities
Referenced by grab_things(), and serialize().
num_items
Items::size_type LevelInfo::num_items
Referenced by grab_things(), and serialize().
seed
std::string LevelInfo::seed
Referenced by ensure_generated_map(), GameMapInfo::generate_map(), serialize(), and GameMapInfo::update_seed().
system_manager
SystemManager LevelInfo::system_manager
was_generated
bool LevelInfo::was_generated = false
Referenced by ensure_generated_map(), and serialize().
The documentation for this struct was generated from the following file:
src/level_info.h