ext Namespace Reference
Functions
void draw_fps (int x, int y)
void clear_background (raylib::Color col)
void init_audio_device ()
void close_audio_device ()
void set_clipboard_text (const char *text)
auto get_clipboard_text ()
vec2 get_mouse_position ()
bool is_key_pressed (int keycode)
bool is_key_down (int keycode)
float get_gamepad_axis_movement (int gamepad, raylib::GamepadAxis axis)
float get_mouse_wheel_move ()
void set_gamepad_mappings (const char *mappings)
Function Documentation
clear_background()
void ext::clear_background (raylib::Color col) [inline]
Referenced by AboutLayer::onDraw(), GameLayer::onDraw(), MenuLayer::onDraw(), and SettingsLayer::onDraw().
close_audio_device()
void ext::close_audio_device () [inline]
Referenced by Preload::~Preload().
draw_fps()
void ext::draw_fps (int x, int y) [inline]
Referenced by FPSLayer::onDraw().
get_clipboard_text()
auto ext::get_clipboard_text () [inline]
Referenced by ui::textfield().
get_gamepad_axis_movement()
float ext::get_gamepad_axis_movement (int gamepad, raylib::GamepadAxis axis) [inline]
Referenced by KeyMap::visit_axis().
get_mouse_position()
vec2 ext::get_mouse_position () [inline]
Referenced by get_mouse_info().
get_mouse_wheel_move()
float ext::get_mouse_wheel_move () [inline]
Referenced by ui::IUIContextInputManager::begin(), operator<<(), and GameCam::updateCamera().
init_audio_device()
void ext::init_audio_device () [inline]
Referenced by Preload::Preload().
is_key_down()
bool ext::is_key_down (int keycode) [inline]
Referenced by KeyMap::visit_key_down().
is_key_pressed()
bool ext::is_key_pressed (int keycode) [inline]
Referenced by KeyMap::visit_key().
set_clipboard_text()
void ext::set_clipboard_text (const char * text) [inline]
Referenced by NetworkLayer::draw_connected_screen().
set_gamepad_mappings()
void ext::set_gamepad_mappings (const char * mappings) [inline]
Referenced by KeyMap::load_controller_db().