entities Namespace Reference
Functions
static Entity * make_furniture (const DebugOptions &options, vec2 pos, Color face, Color base, bool is_static=false)
static Entity * make_table (vec2 pos)
static Entity * make_character_switcher (vec2 pos)
static Entity * make_wall (vec2 pos, Color c=ui::color::brown)
static Entity * make_conveyer (vec2 pos)
static Entity * make_grabber (vec2 pos)
static Entity * make_register (vec2 pos)
template<typename I >
static Entity * make_itemcontainer (vec2 pos)
static Entity * make_bagbox (vec2 pos)
static Entity * make_medicine_cabinet (vec2 pos)
static Entity * make_pill_dispenser (vec2 pos)
static Entity * make_trigger_area (vec3 pos, float width, float height, std::string title=`DEFAULT TRIGGER`)
static Entity * make_customer_spawner (vec3 pos)
static Entity * make_sophie (vec3 pos)
Function Documentation
make_bagbox()
static Entity * entities::make_bagbox (vec2 pos) [static]
References Entity::addComponent(), ENABLE_MODELS, Entity::get(), ModelInfo::model_name, HasDynamicModelName::OpenClosed, and TILESIZE.
Referenced by generation::helper::generate_entity_from_character().
make_character_switcher()
static Entity * entities::make_character_switcher (vec2 pos) [static]
References Entity::addComponent(), ui::color::green, HasWork::increase_pct(), UsesCharacterModel::increment(), HasWork::is_work_complete(), make_furniture(), DebugOptions::name, HasWork::reset_pct(), and ui::color::yellow.
Referenced by LobbyMapInfo::generate_map().
make_conveyer()
static Entity * entities::make_conveyer (vec2 pos) [static]
References Entity::addComponent(), ui::color::blue, CustomHeldItemPosition::Conveyer, ENABLE_MODELS, Entity::get(), make_furniture(), ModelInfo::model_name, and DebugOptions::name.
make_customer_spawner()
static Entity * entities::make_customer_spawner (vec3 pos) [static]
References Entity::addComponent(), make_customer(), make_entity(), and IsSpawner::set_total().
Referenced by generation::helper::generate_entity_from_character().
make_furniture()
static Entity * entities::make_furniture (const DebugOptions & options, vec2 pos, Color face, Color base, bool is_static = false) [static]
References Entity::addComponent(), CustomHeldItemPosition::Default, ENABLE_MODELS, Entity::get(), make_entity(), and TILESIZE.
Referenced by make_character_switcher(), make_conveyer(), make_grabber(), make_itemcontainer(), make_register(), make_table(), and make_wall().
make_grabber()
static Entity * entities::make_grabber (vec2 pos) [static]
References Entity::addComponent(), CustomHeldItemPosition::Conveyer, ENABLE_MODELS, Entity::get(), make_furniture(), ModelInfo::model_name, DebugOptions::name, and ui::color::yellow.
Referenced by generation::helper::generate_entity_from_character().
make_itemcontainer()
template<typename I >
static Entity * entities::make_itemcontainer (vec2 pos) [static]
References Entity::addComponent(), make_furniture(), DebugOptions::name, and ui::color::white.
make_medicine_cabinet()
static Entity * entities::make_medicine_cabinet (vec2 pos) [static]
References ENABLE_MODELS, Entity::get(), ModelInfo::model_name, and TILESIZE.
Referenced by generation::helper::generate_entity_from_character().
make_pill_dispenser()
static Entity * entities::make_pill_dispenser (vec2 pos) [static]
References Entity::addComponent(), ENABLE_MODELS, Entity::get(), HasWork::increase_pct(), HasWork::is_work_complete(), ModelInfo::model_name, HasWork::reset_pct(), CustomHeldItemPosition::Table, and TILESIZE.
Referenced by generation::helper::generate_entity_from_character().
make_register()
static Entity * entities::make_register (vec2 pos) [static]
References Entity::addComponent(), ENABLE_MODELS, Entity::get(), ui::color::grey, make_furniture(), ModelInfo::model_name, DebugOptions::name, and TILESIZE.
Referenced by generation::helper::generate_entity_from_character().
make_sophie()
static Entity * entities::make_sophie (vec3 pos) [static]
References make_entity(), and HasTimer::Round.
Referenced by generation::helper::generate_entity_from_character().
make_table()
static Entity * entities::make_table (vec2 pos) [static]
References Entity::addComponent(), ui::color::brown, Entity::get(), HasWork::increase_pct(), HasWork::is_work_complete(), make_furniture(), DebugOptions::name, HasWork::reset_pct(), and CustomHeldItemPosition::Table.
Referenced by generation::helper::generate_entity_from_character().
make_trigger_area()
static Entity * entities::make_trigger_area (vec3 pos, float width, float height, std::string title = `DEFAULT TRIGGER`) [static]
References Entity::addComponent(), Entity::get(), make_entity(), GameState::s_toggle_to_planning(), TILESIZE, and IsTriggerArea::update_max_entrants().
Referenced by LobbyMapInfo::generate_map(), and validate_trigger_area_serialized().
make_wall()
static Entity * entities::make_wall (vec2 pos, Color c = ui::color::brown) [static]
References make_furniture(), and DebugOptions::name.
Referenced by generate_and_insert_walls(), generation::helper::generate_entity_from_character(), and validate_wall_color_serialized().