toasts Namespace Reference
Functions
static void remove_complete ()
static void update (float dt)
Function Documentation
remove_complete()
static void toasts::remove_complete () [inline], [static]
References TOASTS.
Referenced by update().
update()
static void toasts::update (float dt) [inline], [static]
References remove_complete(), and TOASTS.
Referenced by ToastLayer::onUpdate().