SimpleColoredBoxRenderer Struct Reference
#include <simple_colored_box_renderer.h>
Public Member Functions
virtual ~SimpleColoredBoxRenderer ()
void update (Color face, Color base)
void update_face (Color face)
void update_base (Color base)
Color face () const
Color base () const
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
Color face_color = PINK
Color base_color = PINK
Constructor & Destructor Documentation
 SimpleColoredBoxRenderer()
virtual SimpleColoredBoxRenderer::~SimpleColoredBoxRenderer () [inline], [virtual]
Member Function Documentation
base()
Color SimpleColoredBoxRenderer::base () const [inline]
References base_color.
Referenced by system_manager::render_manager::draw_valid_colored_box(), update(), update_base(), and validate_wall_color_serialized().
face()
Color SimpleColoredBoxRenderer::face () const [inline]
References face_color.
Referenced by system_manager::render_manager::draw_valid_colored_box(), update(), update_face(), and validate_wall_color_serialized().
serialize()
template<typename S >
void SimpleColoredBoxRenderer::serialize (S & s) [inline], [private]
References base_color, and face_color.
update()
void SimpleColoredBoxRenderer::update (Color face, Color base) [inline]
References base(), base_color, face(), and face_color.
update_base()
void SimpleColoredBoxRenderer::update_base (Color base) [inline]
References base(), and base_color.
update_face()
void SimpleColoredBoxRenderer::update_face (Color face) [inline]
References face(), and face_color.
Member Data Documentation
base_color
Color SimpleColoredBoxRenderer::base_color = PINK [private]
Referenced by base(), serialize(), update(), and update_base().
face_color
Color SimpleColoredBoxRenderer::face_color = PINK [private]
Referenced by face(), serialize(), update(), and update_face().
The documentation for this struct was generated from the following file:
src/components/simple_colored_box_renderer.h