Register Struct Reference
#include <register.h>
Public Member Functions
Register ()
Register (vec2 pos)
void update_model ()
int position_in_line (AIPerson *entity)
bool can_move_up (AIPerson *entity)
void leave_line (AIPerson *entity)
bool is_in_line (AIPerson *entity)
bool has_space_in_queue ()
vec2 get_next_queue_position (AIPerson *entity)
Public Member Functions inherited from Furniture
Furniture (vec2 pos, Color face_color_in)
Furniture (vec3 pos, Color face_color_in)
Furniture (vec2 pos, Color face_color_in, Color base_color_in)
virtual bool add_to_navmesh () override
virtual bool can_rotate () const
virtual bool can_be_picked_up ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr) override
virtual bool has_held_item () const
Public Member Functions inherited from Entity
template<typename T >
bool has () const
template<typename T , typename... TArgs>
T & addComponent (TArgs &&... args)
template<typename T >
T & get () const
void add_static_components ()
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
virtual void announce (std::string text)
virtual bool is_snappable ()
virtual bool collides (BoundingBox b) const
virtual BoundingBox raw_bounds () const
virtual BoundingBox bounds () const
vec3 snap_position () const
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void update (float dt) final
Public Attributes
std::deque< AIPerson * > ppl_in_line
int max_queue_size = 3
int next_line_position = 0
Public Attributes inherited from Entity
int id
ComponentBitSet componentSet
ComponentArray componentArray
bool cleanup = false
bool is_held = false
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, Transform::Transform::FrontFaceDirection direction)
Protected Member Functions inherited from Furniture
Furniture ()
void add_static_components ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec3 size () const
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void in_round_update (float)
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Constructor & Destructor Documentation
Register() [1/2]
Register::Register () [inline]
Register() [2/2]
Register::Register (vec2 pos) [inline], [explicit]
References update_model().
Member Function Documentation
can_move_up()
bool Register::can_move_up (AIPerson * entity) [inline]
References Entity::id, and ppl_in_line.
Referenced by system_manager::job_system::update_job_information().
get_next_queue_position()
vec2 Register::get_next_queue_position (AIPerson * entity) [inline]
References M_ASSERT, next_line_position, ppl_in_line, and Entity::tile_infront().
has_space_in_queue()
bool Register::has_space_in_queue () [inline]
References max_queue_size, and next_line_position.
is_in_line()
bool Register::is_in_line (AIPerson * entity) [inline]
References position_in_line().
leave_line()
void Register::leave_line (AIPerson * entity) [inline]
References position_in_line(), and ppl_in_line.
Referenced by system_manager::job_system::update_job_information().
position_in_line()
int Register::position_in_line (AIPerson * entity) [inline]
References Entity::id, log_warn, and ppl_in_line.
Referenced by is_in_line(), leave_line(), and system_manager::job_system::update_job_information().
serialize()
template<typename S >
void Register::serialize (S & s) [inline], [private]
update_model()
void Register::update_model () [inline]
References ModelInfo::model_name, and TILESIZE.
Referenced by Register().
Member Data Documentation
max_queue_size
int Register::max_queue_size = 3
Referenced by has_space_in_queue().
next_line_position
int Register::next_line_position = 0
Referenced by get_next_queue_position(), and has_space_in_queue().
ppl_in_line
std::deque<AIPerson*> Register::ppl_in_line
Referenced by can_move_up(), get_next_queue_position(), leave_line(), and position_in_line().
The documentation for this struct was generated from the following file:
src/furniture/register.h