Pill Struct Reference
#include <item.h>
Public Types
enum struct PillType { Red
, RedLong
, Blue
, BlueLong
 }
Public Types inherited from Item
enum HeldBy {
NONE
, ITEM
, PLAYER
, FURNITURE
,
CUSTOMER
 }
Public Member Functions
Pill ()
Pill (vec3 p, Color c)
Pill (vec2 p, Color c)
void init ()
virtual vec3 model_scale () const override
virtual std::optional< raylib::Model > model () const override
Public Member Functions inherited from Item
Item (vec3 p, Color c)
Item (vec2 p, Color c)
virtual ~Item ()
vec3 snap_position () const
virtual bool is_collidable ()
virtual vec3 model_scale () const
virtual void render (bool render_held_item=true) const
virtual void update_position (const vec3 &p)
virtual BoundingBox bounds () const
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual bool collides (BoundingBox b) const
virtual std::optional< raylib::Model > model () const
virtual bool eat (std::shared_ptr< Item > item)
virtual bool can_eat (std::shared_ptr< Item > item)
virtual bool has_holding_ability () const
virtual bool empty () const
Public Attributes
enum Pill::PillType type
Public Attributes inherited from Item
int id
float item_size = TILESIZE / 2
Color color
vec3 raw_position
vec3 position
bool cleanup = false
HeldBy held_by = NONE
std::shared_ptr< Item > held_item
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Protected Member Functions inherited from Item
Item ()
Member Enumeration Documentation
PillType
enum struct Pill::PillType [strong]
Enumerator
Red
RedLong
Blue
BlueLong
Constructor & Destructor Documentation
Pill() [1/3]
Pill::Pill () [inline]
References init().
Pill() [2/3]
Pill::Pill (vec3 p, Color c) [inline]
References init().
Pill() [3/3]
Pill::Pill (vec2 p, Color c) [inline]
References init().
Member Function Documentation
init()
void Pill::init () [inline]
References randIn(), and type.
Referenced by Pill().
model()
virtual std::optional< raylib::Model > Pill::model () const [inline], [override], [virtual]
Reimplemented from Item.
References Blue, BlueLong, ModelLibrary::get(), log_warn, Red, RedLong, and type.
model_scale()
virtual vec3 Pill::model_scale () const [inline], [override], [virtual]
Reimplemented from Item.
serialize()
template<typename S >
void Pill::serialize (S & s) [inline], [private]
References type.
Member Data Documentation
type
enum Pill::PillType Pill::type
Referenced by init(), model(), and serialize().
The documentation for this struct was generated from the following file:
src/item.h