system_manager::ui Namespace Reference
Functions
void render_timer (std::shared_ptr< Entity > entity, float)
void render_block_state_change_reason (std::shared_ptr< Entity > entity, float)
void render_player_info ()
void render_debug (const Entities &, float)
void render_normal (const Entities &entities, float dt)
Function Documentation
render_block_state_change_reason()
void system_manager::ui::render_block_state_change_reason (std::shared_ptr< Entity > entity, float) [inline]
References ui::DEFAULT_THEME, ui::theme::Font, ui::UITheme::from_usage(), util::trunc(), and HasTimer::WaitingReasonLast.
Referenced by render_normal().
render_debug()
void system_manager::ui::render_debug (const Entities & , float) [inline]
References render_player_info().
Referenced by SystemManager::render_ui().
render_normal()
void system_manager::ui::render_normal (const Entities & entities, float dt) [inline]
References render_block_state_change_reason(), and render_timer().
Referenced by SystemManager::render_ui().
render_player_info()
void system_manager::ui::render_player_info () [inline]
References global_player, CanHoldFurniture::is_holding_furniture(), CanHoldItem::is_holding_item(), and Transform::pos().
Referenced by render_debug().
render_timer()
void system_manager::ui::render_timer (std::shared_ptr< Entity > entity, float) [inline]
References ui::theme::Background, ui::DEFAULT_THEME, util::deg2rad(), ui::theme::Font, ui::UITheme::from_usage(), util::lerp(), log_warn, ui::theme::Primary, HasTimer::Round, and GameState::s_in_round().
Referenced by render_normal().