IsTriggerArea Struct Reference
#include <is_trigger_area.h>
Public Member Functions
virtual ~IsTriggerArea ()
const std::string & title () const
bool should_wave () const
int max_entrants () const
int active_entrants () const
bool has_matching_entrants () const
bool has_min_matching_entrants () const
float progress () const
void increase_progress (float dt)
void decrease_progress (float dt)
auto & update_progress_max (float amt)
auto & update_title (const std::string &nt)
auto & update_entrants (int ne)
auto & update_max_entrants (int ne)
auto & on_complete (std::function< void()> cb)
auto get_complete_fn ()
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
int wanted_entrants = 1
int current_entrants = 0
std::string _title
int max_title_length = 20
float completion_time_max = 0.f
float completion_time_passed = 0.f
std::function< void()> complete_fn
Constructor & Destructor Documentation
 IsTriggerArea()
virtual IsTriggerArea::~IsTriggerArea () [inline], [virtual]
Member Function Documentation
active_entrants()
int IsTriggerArea::active_entrants () const [inline]
References current_entrants.
Referenced by system_manager::render_manager::render_trigger_area().
decrease_progress()
void IsTriggerArea::decrease_progress (float dt) [inline]
References completion_time_passed.
Referenced by system_manager::update_trigger_area_percent().
get_complete_fn()
auto IsTriggerArea::get_complete_fn () [inline]
References complete_fn.
Referenced by system_manager::trigger_cb_on_full_progress().
has_matching_entrants()
bool IsTriggerArea::has_matching_entrants () const [inline]
References current_entrants, and wanted_entrants.
has_min_matching_entrants()
bool IsTriggerArea::has_min_matching_entrants () const [inline]
References current_entrants, and wanted_entrants.
Referenced by should_wave().
increase_progress()
void IsTriggerArea::increase_progress (float dt) [inline]
References completion_time_max, and completion_time_passed.
Referenced by system_manager::update_trigger_area_percent().
max_entrants()
int IsTriggerArea::max_entrants () const [inline]
References wanted_entrants.
Referenced by system_manager::render_manager::render_trigger_area().
on_complete()
auto & IsTriggerArea::on_complete (std::function< void()> cb) [inline]
References complete_fn.
progress()
float IsTriggerArea::progress () const [inline]
References completion_time_max, and completion_time_passed.
Referenced by system_manager::render_manager::render_trigger_area(), and system_manager::trigger_cb_on_full_progress().
serialize()
template<typename S >
void IsTriggerArea::serialize (S & s) [inline], [private]
References _title, completion_time_max, completion_time_passed, current_entrants, max_title_length, and wanted_entrants.
should_wave()
bool IsTriggerArea::should_wave () const [inline]
References has_min_matching_entrants().
Referenced by system_manager::render_manager::render_trigger_area(), and system_manager::update_trigger_area_percent().
title()
const std::string & IsTriggerArea::title () const [inline]
References _title.
Referenced by validate_trigger_area_serialized().
update_entrants()
auto & IsTriggerArea::update_entrants (int ne) [inline]
References current_entrants.
update_max_entrants()
auto & IsTriggerArea::update_max_entrants (int ne) [inline]
References wanted_entrants.
Referenced by entities::make_trigger_area().
update_progress_max()
auto & IsTriggerArea::update_progress_max (float amt) [inline]
References completion_time_max.
update_title()
auto & IsTriggerArea::update_title (const std::string & nt) [inline]
References _title, log_warn, and max_title_length.
Member Data Documentation
_title
std::string IsTriggerArea::_title [private]
Referenced by serialize(), title(), and update_title().
complete_fn
std::function<void()> IsTriggerArea::complete_fn [private]
Referenced by get_complete_fn(), and on_complete().
completion_time_max
float IsTriggerArea::completion_time_max = 0.f [private]
Referenced by increase_progress(), progress(), serialize(), and update_progress_max().
completion_time_passed
float IsTriggerArea::completion_time_passed = 0.f [private]
Referenced by decrease_progress(), increase_progress(), progress(), and serialize().
current_entrants
int IsTriggerArea::current_entrants = 0 [private]
Referenced by active_entrants(), has_matching_entrants(), has_min_matching_entrants(), serialize(), and update_entrants().
max_title_length
int IsTriggerArea::max_title_length = 20 [private]
Referenced by serialize(), and update_title().
wanted_entrants
int IsTriggerArea::wanted_entrants = 1 [private]
Referenced by has_matching_entrants(), has_min_matching_entrants(), max_entrants(), serialize(), and update_max_entrants().
The documentation for this struct was generated from the following file:
src/components/is_trigger_area.h