SystemManager Struct Reference
#include <system_manager.h>
Public Member Functions
SystemManager ()
void on_game_state_change (game::State new_state, game::State old_state)
void update (const Entities &entities, float dt)
void update_all_entities (const Entities &players, float dt)
void process_inputs (const Entities &entities, const UserInputs &inputs)
void render_entities (const Entities &entities, float dt) const
void render_ui (const Entities &entities, float dt) const
void render_items (Items items, float) const
Public Attributes
Entities oldAll
bool state_transitioned_round_to_planning = false
bool state_transitioned_planning_to_round = false
Private Member Functions
void process_state_change (const std::vector< std::shared_ptr< Entity > > &entities, float dt)
void always_update (const std::vector< std::shared_ptr< Entity > > &entity_list, float dt)
void in_round_update (const std::vector< std::shared_ptr< Entity > > &entity_list, float dt)
void planning_update (const std::vector< std::shared_ptr< Entity > > &entity_list, float dt)
void render_normal (const std::vector< std::shared_ptr< Entity > > &entity_list, float dt) const
void render_debug (const std::vector< std::shared_ptr< Entity > > &entity_list, float dt) const
Constructor & Destructor Documentation
SystemManager()
SystemManager::SystemManager () [inline]
References on_game_state_change().
Member Function Documentation
always_update()
void SystemManager::always_update (const std::vector< std::shared_ptr< Entity > > & entity_list, float dt) [inline], [private]
References system_manager::input_process_manager::collect_user_input(), system_manager::highlight_facing_furniture(), DebugName::name(), system_manager::process_trigger_area(), system_manager::reset_highlighted(), system_manager::run_timer(), system_manager::sophie(), system_manager::transform_snapper(), system_manager::render_manager::update_character_model_from_index(), and system_manager::update_held_item_position().
in_round_update()
void SystemManager::in_round_update (const std::vector< std::shared_ptr< Entity > > & entity_list, float dt) [inline], [private]
References system_manager::job_system::in_round_update(), system_manager::process_conveyer_items(), system_manager::process_grabber_items(), system_manager::process_is_container_and_should_backfill_item(), system_manager::process_is_container_and_should_update_item(), and system_manager::process_spawner().
on_game_state_change()
void SystemManager::on_game_state_change (game::State new_state, game::State old_state) [inline]
References game::InRound, and game::Planning.
Referenced by SystemManager().
planning_update()
void SystemManager::planning_update (const std::vector< std::shared_ptr< Entity > > & entity_list, float dt) [inline], [private]
References system_manager::update_held_furniture_position().
process_inputs()
void SystemManager::process_inputs (const Entities & entities, const UserInputs & inputs) [inline]
References system_manager::input_process_manager::process_input().
process_state_change()
void SystemManager::process_state_change (const std::vector< std::shared_ptr< Entity > > & entities, float dt) [inline], [private]
References system_manager::delete_held_items_when_leaving_inround(), system_manager::handle_autodrop_furniture_when_exiting_planning(), and system_manager::refetch_dynamic_model_names().
render_debug()
void SystemManager::render_debug (const std::vector< std::shared_ptr< Entity > > & entity_list, float dt) const [inline], [private]
References system_manager::render_manager::render_debug().
render_entities()
void SystemManager::render_entities (const Entities & entities, float dt) const [inline]
References GlobalValueRegister::get_or_default(), and GLOBALS.
render_items()
void SystemManager::render_items (Items items, float) const [inline]
References log_warn.
render_normal()
void SystemManager::render_normal (const std::vector< std::shared_ptr< Entity > > & entity_list, float dt) const [inline], [private]
References system_manager::render_manager::render_floating_name(), system_manager::render_manager::render_normal(), and system_manager::render_manager::render_progress_bar().
render_ui()
void SystemManager::render_ui (const Entities & entities, float dt) const [inline]
References GlobalValueRegister::get_or_default(), GLOBALS, system_manager::ui::render_debug(), and system_manager::ui::render_normal().
update()
void SystemManager::update (const Entities & entities, float dt) [inline]
References GameState::s_in_round().
update_all_entities()
void SystemManager::update_all_entities (const Entities & players, float dt) [inline]
References EntityHelper::get_entities().
Member Data Documentation
oldAll
Entities SystemManager::oldAll
state_transitioned_planning_to_round
bool SystemManager::state_transitioned_planning_to_round = false
state_transitioned_round_to_planning
bool SystemManager::state_transitioned_round_to_planning = false
The documentation for this struct was generated from the following file:
src/system/system_manager.h