Layer Struct Reference
#include <layer.h>
Public Member Functions
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
void onEvent (Event &event)
virtual bool onKeyPressed (KeyPressedEvent &)
virtual bool onGamepadButtonPressed (GamepadButtonPressedEvent &)
virtual bool onGamepadAxisMoved (GamepadAxisMovedEvent &)
virtual bool onCharPressedEvent (CharPressedEvent &)
const std::string & getname () const
Public Attributes
int id
std::string name
Constructor & Destructor Documentation
Layer()
Layer::Layer (const std::string & n = `layer`) [inline]
 Layer()
virtual Layer::~Layer () [inline], [virtual]
Member Function Documentation
getname()
const std::string & Layer::getname () const [inline]
References name.
onAttach()
virtual void Layer::onAttach () [inline], [virtual]
onCharPressedEvent()
virtual bool Layer::onCharPressedEvent (CharPressedEvent &) [inline], [virtual]
Reimplemented in NetworkLayer.
Referenced by onEvent().
onDetach()
virtual void Layer::onDetach () [inline], [virtual]
onDraw()
virtual void Layer::onDraw (float elapsed) [pure virtual]
Implemented in AboutLayer, GameDebugLayer, GameLayer, MenuLayer, NetworkLayer, BasePauseLayer, SettingsLayer, FPSLayer, MenuStateLayer, StreamerSafeLayer, ToastLayer, and VersionLayer.
onEvent()
void Layer::onEvent (Event & event) [inline]
References EventDispatcher::dispatch(), onCharPressedEvent(), onGamepadAxisMoved(), onGamepadButtonPressed(), and onKeyPressed().
onGamepadAxisMoved()
virtual bool Layer::onGamepadAxisMoved (GamepadAxisMovedEvent &) [inline], [virtual]
Reimplemented in GameDebugLayer, GameLayer, MenuLayer, and NetworkLayer.
Referenced by onEvent().
onGamepadButtonPressed()
virtual bool Layer::onGamepadButtonPressed (GamepadButtonPressedEvent &) [inline], [virtual]
Reimplemented in GameDebugLayer, GameLayer, MenuLayer, NetworkLayer, BasePauseLayer, and SettingsLayer.
Referenced by onEvent().
onKeyPressed()
virtual bool Layer::onKeyPressed (KeyPressedEvent &) [inline], [virtual]
Reimplemented in AboutLayer, GameDebugLayer, GameLayer, MenuLayer, NetworkLayer, BasePauseLayer, and SettingsLayer.
Referenced by onEvent().
onUpdate()
virtual void Layer::onUpdate (float elapsed) [pure virtual]
Implemented in GameLayer, NetworkLayer, ToastLayer, AboutLayer, FPSLayer, GameDebugLayer, MenuLayer, MenuStateLayer, BasePauseLayer, SettingsLayer, StreamerSafeLayer, and VersionLayer.
Member Data Documentation
id
int Layer::id
name
std::string Layer::name
Referenced by getname().
The documentation for this struct was generated from the following file:
src/engine/layer.h