CanBeTakenFrom Struct Reference
#include <can_be_taken_from.h>
Public Member Functions
virtual ~CanBeTakenFrom ()
bool can_take_from () const
bool cannot_take_from () const
void update (bool g)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
bool allowed = false
Constructor & Destructor Documentation
 CanBeTakenFrom()
virtual CanBeTakenFrom::~CanBeTakenFrom () [inline], [virtual]
Member Function Documentation
can_take_from()
bool CanBeTakenFrom::can_take_from () const [inline]
References allowed.
Referenced by cannot_take_from().
cannot_take_from()
bool CanBeTakenFrom::cannot_take_from () const [inline]
References can_take_from().
serialize()
template<typename S >
void CanBeTakenFrom::serialize (S & s) [inline], [private]
References allowed.
update()
void CanBeTakenFrom::update (bool g) [inline]
References allowed.
Referenced by system_manager::process_conveyer_items().
Member Data Documentation
allowed
bool CanBeTakenFrom::allowed = false [private]
Referenced by can_take_from(), serialize(), and update().
The documentation for this struct was generated from the following file:
src/components/can_be_taken_from.h