system_manager::logging_manager Namespace Reference
Functions
void announce (std::shared_ptr< Entity > entity, const std::string &text)
Function Documentation
announce()
void system_manager::logging_manager::announce (std::shared_ptr< Entity > entity, const std::string & text) [inline]
References is_server(), log_info, and Transform::pos().
Referenced by WaitJob::run_state_working_at_end(), WaitInQueueJob::run_state_working_at_end(), WaitInQueueJob::run_state_working_at_start(), and Job::travel_to_position().