MenuState Struct Reference
#include <statemanager.h>
Public Member Functions
virtual menu::State default_value () const override
bool is_in_menu () const
bool in_game () const
Public Member Functions inherited from StateManager2< menu::State >
menu::State read () const
menu::State previous () const
menu::State go_back ()
void clear_history ()
bool is (menu::State s) const
bool is_not (menu::State s) const
const std::string_view tostring () const
void register_on_change (const std::function< void(menu::State, menu::State)> &nfunc)
void set (menu::State ns)
virtual menu::State default_value () const=0
void reset ()
virtual ~StateManager2 ()
Static Public Member Functions
static bool s_in_game ()
static bool s_is_game (menu::State ms)
Member Function Documentation
default_value()
virtual menu::State MenuState::default_value () const [inline], [override], [virtual]
Implements StateManager2< menu::State >.
References menu::Root.
in_game()
bool MenuState::in_game () const [inline]
References menu::Game.
is_in_menu()
bool MenuState::is_in_menu () const [inline]
References menu::Game.
s_in_game()
static bool MenuState::s_in_game () [inline], [static]
Referenced by GameDebugLayer::onDraw(), GameLayer::onDraw(), BasePauseLayer::onDraw(), GameDebugLayer::onGamepadButtonPressed(), GameLayer::onGamepadButtonPressed(), GameDebugLayer::onKeyPressed(), GameLayer::onKeyPressed(), GameLayer::onUpdate(), and GameDebugLayer::onUpdate().
s_is_game()
static bool MenuState::s_is_game (menu::State ms) [inline], [static]
References menu::Game.
Referenced by network::Server::tick().
The documentation for this struct was generated from the following file:
src/engine/statemanager.h