test Namespace Reference
Namespaces
namespace neighbors
Functions
bool canvisit (const vec2 &pos)
auto p (vec2 a, vec2 b)
auto p (Entity *a, vec2 b)
std::pair< vec2, vec2 > setup (const std::string map)
void teardown ()
void test_no_obstacles ()
void test_one_obstacle ()
void test_surround_no_path ()
void test_surround_one_exit ()
void test_clear_path_surround_exit ()
void test_clear_path_surround_one_exit ()
void test_maze_path_exists ()
void test_maze_path_doesnt_exist ()
Variables
static std::vector< Entity * > ents
Function Documentation
canvisit()
bool test::canvisit (const vec2 & pos) [inline]
References vec::distance(), ents, is_collidable(), and TILESIZE.
Referenced by p().
p() [1/2]
auto test::p (Entity * a, vec2 b) [inline]
References Transform::as2(), Entity::get(), and p().
p() [2/2]
auto test::p (vec2 a, vec2 b) [inline]
References canvisit(), and astar::find_path().
Referenced by test::neighbors::is_valid(), p(), test_clear_path_surround_exit(), test_clear_path_surround_one_exit(), test_maze_path_doesnt_exist(), test_maze_path_exists(), test_no_obstacles(), test_one_obstacle(), test_surround_no_path(), and test_surround_one_exit().
setup()
std::pair< vec2, vec2 > test::setup (const std::string map) [inline]
References ents, generation::helper::generate(), util::split_string(), generation::helper::x, and generation::helper::z.
Referenced by test_clear_path_surround_exit(), test_clear_path_surround_one_exit(), test_maze_path_doesnt_exist(), test_maze_path_exists(), test_no_obstacles(), test_one_obstacle(), test_surround_no_path(), and test_surround_one_exit().
teardown()
void test::teardown () [inline]
References ents.
Referenced by test_clear_path_surround_exit(), test_clear_path_surround_one_exit(), test_maze_path_doesnt_exist(), test_maze_path_exists(), test_no_obstacles(), test_one_obstacle(), test_surround_no_path(), and test_surround_one_exit().
test_clear_path_surround_exit()
void test::test_clear_path_surround_exit () [inline]
References p(), setup(), teardown(), and VALIDATE.
test_clear_path_surround_one_exit()
void test::test_clear_path_surround_one_exit () [inline]
References p(), setup(), teardown(), and VALIDATE.
test_maze_path_doesnt_exist()
void test::test_maze_path_doesnt_exist () [inline]
References p(), setup(), teardown(), and VALIDATE.
test_maze_path_exists()
void test::test_maze_path_exists () [inline]
References p(), setup(), teardown(), and VALIDATE.
test_no_obstacles()
void test::test_no_obstacles () [inline]
References p(), setup(), teardown(), and VALIDATE.
test_one_obstacle()
void test::test_one_obstacle () [inline]
References p(), setup(), teardown(), and VALIDATE.
test_surround_no_path()
void test::test_surround_no_path () [inline]
References p(), setup(), teardown(), and VALIDATE.
test_surround_one_exit()
void test::test_surround_one_exit () [inline]
References p(), setup(), teardown(), and VALIDATE.
Variable Documentation
ents
std::vector<Entity*> test::ents [static]
Referenced by canvisit(), setup(), and teardown().