LobbyMapInfo Struct Reference
#include <level_info.h>
Public Member Functions
virtual void generate_map () override
virtual void onDraw (float dt) const override
Public Member Functions inherited from LevelInfo
virtual void onUpdate (float dt)
virtual void onDraw (float) const
virtual void onDrawUI (float)
void grab_things ()
void ensure_generated_map (const std::string &new_seed)
virtual void generate_map ()=0
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Public Attributes inherited from LevelInfo
bool was_generated = false
Entities entities
Entities::size_type num_entities
Items items
Items::size_type num_items
std::string seed
Member Function Documentation
generate_map()
virtual void LobbyMapInfo::generate_map () [inline], [override], [virtual]
Implements LevelInfo.
References EntityHelper::addEntity().
onDraw()
virtual void LobbyMapInfo::onDraw (float dt) const [inline], [override], [virtual]
Reimplemented from LevelInfo.
References LevelInfo::onDraw(), and TILESIZE.
Referenced by Map::onDraw().
serialize()
template<typename S >
void LobbyMapInfo::serialize (S & s) [inline], [private]
The documentation for this struct was generated from the following file:
src/level_info.h