NetworkLayer Struct Reference
#include <networklayer.h>
Public Member Functions
NetworkLayer ()
virtual ~NetworkLayer ()
virtual void onEvent (Event &event) override
bool onCharPressedEvent (CharPressedEvent &event)
bool onGamepadAxisMoved (GamepadAxisMovedEvent &event)
bool onKeyPressed (KeyPressedEvent &event)
bool onGamepadButtonPressed (GamepadButtonPressedEvent &event)
virtual void onUpdate (float dt) override
void draw_username ()
void draw_base_screen ()
void draw_ip_input_screen ()
void draw_connected_screen ()
void draw_username_picker ()
void draw_screen_selector_logic ()
void handle_announcements ()
virtual void onDraw (float dt) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
virtual void onEvent (Event &)=0
const std::string & getname () const
Public Attributes
std::shared_ptr< ui::UIContext > ui_context
std::shared_ptr< network::Info > network_info
std::string my_ip_address
bool should_show_host_ip = false
Public Attributes inherited from Layer
int id
std::string name
Constructor & Destructor Documentation
NetworkLayer()
NetworkLayer::NetworkLayer () [inline]
References network::get_remote_ip_address(), network::Info::init_connections(), my_ip_address, network_info, and ui_context.
 NetworkLayer()
virtual NetworkLayer::~NetworkLayer () [inline], [virtual]
References network::Info::shutdown_connections().
Member Function Documentation
draw_base_screen()
void NetworkLayer::draw_base_screen () [inline]
References ui::button(), ui::div(), draw_username(), ui::components::mk_but_pad(), ui::components::mk_button(), ui::components::mk_column(), ui::components::mk_row(), MK_UUID, network_info, ui::padding(), menu::Root, ui::ROOT_ID, network::Info::s_Client, network::Info::s_Host, and ui_context.
draw_connected_screen()
void NetworkLayer::draw_connected_screen () [inline]
References ui::button(), ui::checkbox(), ui::Children, ui::div(), menu::Game, game::Lobby, ui::components::mk_but_pad(), ui::components::mk_button(), ui::components::mk_icon_button(), ui::components::mk_text(), MK_UUID, MK_UUID_LOOP, HasName::name, ui::padding(), ui::ROOT_ID, ui::Row, ext::set_clipboard_text(), Size_Px, and ui::text().
draw_ip_input_screen()
void NetworkLayer::draw_ip_input_screen () [inline]
References draw_username(), ui::components::mk_text(), MK_UUID, network_info, ui::ROOT_ID, Size_Px, ui::text(), ui::textfield(), ui_context, and validate_ip().
draw_screen_selector_logic()
void NetworkLayer::draw_screen_selector_logic () [inline]
draw_username()
void NetworkLayer::draw_username () [inline]
References ui::button(), ui::div(), ui::components::mk_icon_button(), ui::components::mk_row(), ui::components::mk_text(), MK_UUID, network_info, ui::ROOT_ID, ui::text(), and ui_context.
Referenced by draw_base_screen(), and draw_ip_input_screen().
draw_username_picker()
void NetworkLayer::draw_username_picker () [inline]
References MK_UUID, ui::Pixels, ui::ROOT_ID, Size_Px, ui::text(), and ui::textfield().
handle_announcements()
void NetworkLayer::handle_announcements () [inline]
References log_info, and TOASTS.
onCharPressedEvent()
bool NetworkLayer::onCharPressedEvent (CharPressedEvent & event) [inline]
References menu::Network, and ui_context.
Referenced by onEvent().
onDraw()
virtual void NetworkLayer::onDraw (float dt) [inline], [override], [virtual]
Implements Layer.
References ui::Children, ui::Column, ui::div(), ui::components::mk_root(), menu::Network, ui::padding(), ui::Percent, Size_Pct, Size_Px, and WIN_HF().
onEvent()
virtual void NetworkLayer::onEvent (Event & event) [inline], [override], [virtual]
Implements Layer.
References EventDispatcher::dispatch(), onCharPressedEvent(), onGamepadAxisMoved(), onGamepadButtonPressed(), and onKeyPressed().
onGamepadAxisMoved()
bool NetworkLayer::onGamepadAxisMoved (GamepadAxisMovedEvent & event) [inline]
References menu::Network, and ui_context.
Referenced by onEvent().
onGamepadButtonPressed()
bool NetworkLayer::onGamepadButtonPressed (GamepadButtonPressedEvent & event) [inline]
References menu::Network, and ui_context.
Referenced by onEvent().
onKeyPressed()
bool NetworkLayer::onKeyPressed (KeyPressedEvent & event) [inline]
References menu::Network, and ui_context.
Referenced by onEvent().
onUpdate()
virtual void NetworkLayer::onUpdate (float dt) [inline], [override], [virtual]
Implements Layer.
References menu::Network, and network_info.
Member Data Documentation
my_ip_address
std::string NetworkLayer::my_ip_address
Referenced by NetworkLayer().
network_info
std::shared_ptr<network::Info> NetworkLayer::network_info
Referenced by draw_base_screen(), draw_ip_input_screen(), draw_username(), NetworkLayer(), and onUpdate().
should_show_host_ip
bool NetworkLayer::should_show_host_ip = false
ui_context
std::shared_ptr<ui::UIContext> NetworkLayer::ui_context
Referenced by draw_base_screen(), draw_ip_input_screen(), draw_username(), NetworkLayer(), onCharPressedEvent(), onGamepadAxisMoved(), onGamepadButtonPressed(), and onKeyPressed().
The documentation for this struct was generated from the following file:
src/networklayer.h