CanHoldItem Struct Reference
#include <can_hold_item.h>
Public Member Functions
virtual ~CanHoldItem ()
bool empty () const
bool is_holding_item () const
template<typename T >
std::shared_ptr< T > asT () const
void update (std::shared_ptr< Item > item, Item::HeldBy newHB=Item::HeldBy::NONE)
std::shared_ptr< Item > & item ()
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
std::shared_ptr< Item > held_item = nullptr
Constructor & Destructor Documentation
 CanHoldItem()
virtual CanHoldItem::~CanHoldItem () [inline], [virtual]
Member Function Documentation
asT()
template<typename T >
std::shared_ptr< T > CanHoldItem::asT () const [inline]
References held_item.
empty()
bool CanHoldItem::empty () const [inline]
References held_item.
Referenced by system_manager::delete_held_items_when_leaving_inround(), system_manager::input_process_manager::inround::handle_drop(), is_holding_item(), system_manager::process_conveyer_items(), WaitInQueueJob::run_state_working_at_end(), and system_manager::update_held_item_position().
is_holding_item()
bool CanHoldItem::is_holding_item () const [inline]
References empty().
Referenced by system_manager::process_grabber_items(), system_manager::process_is_container_and_should_backfill_item(), system_manager::process_is_container_and_should_update_item(), and system_manager::ui::render_player_info().
item()
std::shared_ptr< Item > & CanHoldItem::item () [inline]
References held_item.
Referenced by system_manager::backfill_empty_container(), system_manager::delete_held_items_when_leaving_inround(), system_manager::input_process_manager::inround::handle_drop(), system_manager::input_process_manager::inround::handle_grab(), system_manager::process_conveyer_items(), system_manager::process_grabber_items(), system_manager::process_is_container_and_should_update_item(), WaitInQueueJob::run_state_working_at_end(), update(), system_manager::update_held_item_position(), and validate_held_item_serialized().
serialize()
template<typename S >
void CanHoldItem::serialize (S & s) [inline], [private]
References held_item.
update()
void CanHoldItem::update (std::shared_ptr< Item > item, Item::HeldBy newHB = Item::HeldBy::NONE) [inline]
References held_item, item(), and log_warn.
Referenced by system_manager::backfill_empty_container(), system_manager::delete_held_items_when_leaving_inround(), system_manager::process_conveyer_items(), system_manager::process_grabber_items(), system_manager::process_is_container_and_should_update_item(), and WaitInQueueJob::run_state_working_at_end().
Member Data Documentation
held_item
std::shared_ptr<Item> CanHoldItem::held_item = nullptr [private]
Referenced by asT(), empty(), item(), serialize(), and update().
The documentation for this struct was generated from the following file:
src/components/can_hold_item.h