Preload Struct Reference
#include <preload.h>
Public Member Functions
Preload ()
~Preload ()
void load_fonts ()
void load_textures ()
void load_models ()
void load_sounds ()
void load_music ()
void load_shaders ()
Public Attributes
raylib::Font font
Constructor & Destructor Documentation
Preload()
Preload::Preload () [inline]
References ENABLE_MODELS, ENABLE_SOUND, and ext::init_audio_device().
 Preload()
Preload::~Preload () [inline]
References ext::close_audio_device(), ShaderLibrary::get(), SoundLibrary::get(), TextureLibrary::get(), ModelLibrary::get(), and MusicLibrary::get().
Member Function Documentation
load_fonts()
void Preload::load_fonts () [inline]
References load_karmina_regular().
load_models()
void Preload::load_models () [inline]
References ModelLibrary::ModelLoadingInfo::folder, and ModelLibrary::get().
load_music()
void Preload::load_music () [inline]
References MusicLibrary::get().
load_shaders()
void Preload::load_shaders () [inline]
References ShaderLibrary::get().
load_sounds()
void Preload::load_sounds () [inline]
References SoundLibrary::get().
load_textures()
void Preload::load_textures () [inline]
References TextureLibrary::get().
Member Data Documentation
font
raylib::Font Preload::font
The documentation for this struct was generated from the following file:
src/preload.h