ui::IUIContextTheming Struct Reference
#include <ui_context.h>
Public Member Functions
virtual void init ()
void push_theme (UITheme theme)
void pop_theme ()
UITheme active_theme () const
Public Attributes
std::stack< UITheme > themestack
Member Function Documentation
active_theme()
UITheme ui::IUIContextTheming::active_theme () const [inline]
References ui::DEFAULT_THEME, and themestack.
Referenced by ui::UIContext::_draw_text(), and ui::UIContext::draw_widget_rect().
init()
virtual void ui::IUIContextTheming::init () [inline], [virtual]
Reimplemented in ui::UIContext.
References ui::DEFAULT_THEME, and push_theme().
Referenced by ui::UIContext::init().
pop_theme()
void ui::IUIContextTheming::pop_theme () [inline]
References themestack.
push_theme()
void ui::IUIContextTheming::push_theme (UITheme theme) [inline]
References themestack.
Referenced by init().
Member Data Documentation
themestack
std::stack<UITheme> ui::IUIContextTheming::themestack
Referenced by active_theme(), pop_theme(), and push_theme().
The documentation for this struct was generated from the following file:
src/engine/ui_context.h