UsesCharacterModel Struct Reference
#include <uses_character_model.h>
Public Member Functions
UsesCharacterModel ()
virtual ~UsesCharacterModel ()
void increment ()
const std::string & fetch_model_name () const
bool value_same_as_last_render () const
bool value_changed_since_last_render () const
void mark_change_completed ()
int index_server_only () const
void update_index_CLIENT_ONLY (int newind)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
std::array< std::string, 4 > character_models
int index
bool changed
Constructor & Destructor Documentation
UsesCharacterModel()
UsesCharacterModel::UsesCharacterModel () [inline]
 UsesCharacterModel()
virtual UsesCharacterModel::~UsesCharacterModel () [inline], [virtual]
Member Function Documentation
fetch_model_name()
const std::string & UsesCharacterModel::fetch_model_name () const [inline]
References character_models, and index.
Referenced by system_manager::render_manager::update_character_model_from_index(), and update_player_rare_remotely().
increment()
void UsesCharacterModel::increment () [inline]
References changed, character_models, and index.
Referenced by entities::make_character_switcher().
index_server_only()
int UsesCharacterModel::index_server_only () const [inline]
References index.
mark_change_completed()
void UsesCharacterModel::mark_change_completed () [inline]
References changed.
Referenced by system_manager::render_manager::update_character_model_from_index().
serialize()
template<typename S >
void UsesCharacterModel::serialize (S & s) [inline], [private]
References changed, and index.
update_index_CLIENT_ONLY()
void UsesCharacterModel::update_index_CLIENT_ONLY (int newind) [inline]
References changed, character_models, and index.
Referenced by update_player_rare_remotely().
value_changed_since_last_render()
bool UsesCharacterModel::value_changed_since_last_render () const [inline]
References changed.
Referenced by value_same_as_last_render().
value_same_as_last_render()
bool UsesCharacterModel::value_same_as_last_render () const [inline]
References value_changed_since_last_render().
Referenced by system_manager::render_manager::update_character_model_from_index().
Member Data Documentation
changed
bool UsesCharacterModel::changed [private]
Referenced by increment(), mark_change_completed(), serialize(), update_index_CLIENT_ONLY(), and value_changed_since_last_render().
character_models
std::array<std::string, 4> UsesCharacterModel::character_models [private]
Initial value:
= {
        "character_duck",
        "character_dog",
        "character_bear",
        "character_rogue",
    }
Referenced by fetch_model_name(), increment(), and update_index_CLIENT_ONLY().
index
int UsesCharacterModel::index [private]
Referenced by fetch_model_name(), increment(), index_server_only(), serialize(), and update_index_CLIENT_ONLY().
The documentation for this struct was generated from the following file:
src/components/uses_character_model.h