test::neighbors Namespace Reference
Functions
bool is_valid (std::vector< vec2 > v, vec2 p)
void test_all_neighbors ()
Function Documentation
is_valid()
bool test::neighbors::is_valid (std::vector< vec2 > v, vec2 p) [inline]
References test::p().
Referenced by test_all_neighbors().
test_all_neighbors()
void test::neighbors::test_all_neighbors () [inline]
References astar::get_neighbors(), is_valid(), and VALIDATE.