system_manager::render_manager Namespace Reference
Functions
void draw_valid_colored_box (const Transform &transform, const SimpleColoredBoxRenderer &renderer, bool is_highlighted)
void update_character_model_from_index (std::shared_ptr< Entity > entity, float)
bool render_simple_highlighted (std::shared_ptr< Entity > entity, float)
bool render_simple_normal (std::shared_ptr< Entity > entity, float)
bool render_bounding_box (std::shared_ptr< Entity > entity, float)
bool render_debug (std::shared_ptr< Entity > entity, float dt)
bool render_model_highlighted (std::shared_ptr< Entity > entity, float)
bool render_model_normal (std::shared_ptr< Entity > entity, float)
void render_trigger_area (std::shared_ptr< Entity > entity, float dt)
void render_speech_bubble (std::shared_ptr< Entity > entity, float)
void render_normal (std::shared_ptr< Entity > entity, float dt)
void render_floating_name (std::shared_ptr< Entity > entity, float)
void render_progress_bar (std::shared_ptr< Entity > entity, float)
Function Documentation
draw_valid_colored_box()
void system_manager::render_manager::draw_valid_colored_box (const Transform & transform, const SimpleColoredBoxRenderer & renderer, bool is_highlighted) [inline]
References SimpleColoredBoxRenderer::base(), SimpleColoredBoxRenderer::face(), Transform::face_direction(), Transform::FrontFaceDirectionMap, ui::color::getHighlighted(), ui::color::is_empty(), log_warn, Transform::raw(), Transform::sizex(), Transform::sizey(), and Transform::sizez().
Referenced by render_simple_highlighted(), and render_simple_normal().
render_bounding_box()
bool system_manager::render_manager::render_bounding_box (std::shared_ptr< Entity > entity, float) [inline]
References Transform::bounds(), and Transform::raw().
Referenced by render_debug().
render_debug()
bool system_manager::render_manager::render_debug (std::shared_ptr< Entity > entity, float dt) [inline]
References CanBeGhostPlayer::is_ghost(), render_bounding_box(), system_manager::job_system::render_job_visual(), and render_simple_normal().
Referenced by SystemManager::render_debug().
render_floating_name()
void system_manager::render_manager::render_floating_name (std::shared_ptr< Entity > entity, float) [inline]
References raylib::DrawFloatingText(), HasName::name(), and Transform::raw().
Referenced by SystemManager::render_normal().
render_model_highlighted()
bool system_manager::render_manager::render_model_highlighted (std::shared_ptr< Entity > entity, float) [inline]
References Transform::face_direction(), Transform::FrontFaceDirectionMap, ModelRenderer::has_model(), ModelRenderer::model(), ModelRenderer::model_info(), and Transform::size().
Referenced by render_normal().
render_model_normal()
bool system_manager::render_manager::render_model_normal (std::shared_ptr< Entity > entity, float) [inline]
References ENABLE_MODELS, Transform::face_direction(), Transform::FrontFaceDirectionMap, ModelRenderer::has_model(), ModelRenderer::model(), ModelRenderer::model_info(), and Transform::size().
Referenced by render_normal().
render_normal()
void system_manager::render_manager::render_normal (std::shared_ptr< Entity > entity, float dt) [inline]
References CanBeGhostPlayer::is_ghost(), CanBeHighlighted::is_highlighted(), render_model_highlighted(), render_model_normal(), render_simple_highlighted(), render_simple_normal(), render_speech_bubble(), and render_trigger_area().
Referenced by SystemManager::render_normal().
render_progress_bar()
void system_manager::render_manager::render_progress_bar (std::shared_ptr< Entity > entity, float) [inline]
References HasWork::dont_show_progres_bar(), Transform::raw(), HasWork::scale_length(), and TILESIZE.
Referenced by SystemManager::render_normal().
render_simple_highlighted()
bool system_manager::render_manager::render_simple_highlighted (std::shared_ptr< Entity > entity, float) [inline]
References draw_valid_colored_box().
Referenced by render_normal().
render_simple_normal()
bool system_manager::render_manager::render_simple_normal (std::shared_ptr< Entity > entity, float) [inline]
References draw_valid_colored_box().
Referenced by render_debug(), render_normal(), and render_trigger_area().
render_speech_bubble()
void system_manager::render_manager::render_speech_bubble (std::shared_ptr< Entity > entity, float) [inline]
References CanHaveAilment::ailment(), GameCam::camera, HasSpeechBubble::disabled(), TextureLibrary::get(), GlobalValueRegister::get(), GLOBALS, Transform::pos(), and TILESIZE.
Referenced by render_normal().
render_trigger_area()
void system_manager::render_manager::render_trigger_area (std::shared_ptr< Entity > entity, float dt) [inline]
References IsTriggerArea::active_entrants(), now::current_ms(), raylib::DrawText3D(), raylib::DrawTextWave3D(), log_ifx, IsTriggerArea::max_entrants(), Transform::pos(), IsTriggerArea::progress(), render_simple_normal(), IsTriggerArea::should_wave(), TILESIZE, and raylib::WaveTextConfig::waveRange.
Referenced by render_normal().
update_character_model_from_index()
void system_manager::render_manager::update_character_model_from_index (std::shared_ptr< Entity > entity, float) [inline]
References UsesCharacterModel::fetch_model_name(), UsesCharacterModel::mark_change_completed(), ModelInfo::model_name, ModelRenderer::update(), and UsesCharacterModel::value_same_as_last_render().
Referenced by SystemManager::always_update().