CanPerformJob Struct Reference
#include <can_perform_job.h>
Public Member Functions
virtual ~CanPerformJob ()
bool has_job () const
bool needs_job () const
std::stack< std::shared_ptr< Job > > & job_queue ()
void update (JobType starting_jt, JobType idle_jt)
void update (Job *job)
JobType get_next_job_type ()
void push_and_reset (Job *job)
void push_onto_queue (std::shared_ptr< Job > job)
bool has_local_target () const
vec2 local_target () const
void update_job_state (Job::State new_state)
void cleanup_if_completed ()
void run_tick (const std::shared_ptr< Entity > &entity, float dt)
void for_each_path_location (std::function< void(vec2)> cb)
vec2 job_start ()
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
const Job & job () const
template<typename S >
void serialize (S &s)
Private Attributes
JobType starting_job_type
JobType idle_job_type
bool worked_before = false
std::stack< std::shared_ptr< Job > > personal_queue
std::shared_ptr< Job > current_job
Constructor & Destructor Documentation
 CanPerformJob()
virtual CanPerformJob::~CanPerformJob () [inline], [virtual]
Member Function Documentation
cleanup_if_completed()
void CanPerformJob::cleanup_if_completed () [inline]
References Job::Completed, current_job, needs_job(), and personal_queue.
for_each_path_location()
void CanPerformJob::for_each_path_location (std::function< void(vec2)> cb) [inline]
References job(), and needs_job().
get_next_job_type()
JobType CanPerformJob::get_next_job_type () [inline]
References idle_job_type, starting_job_type, and worked_before.
Referenced by system_manager::job_system::ensure_has_job().
has_job()
bool CanPerformJob::has_job () const [inline]
References current_job.
Referenced by system_manager::job_system::ensure_has_job(), has_local_target(), and needs_job().
has_local_target()
bool CanPerformJob::has_local_target () const [inline]
References has_job(), job(), and Job::local.
job()
const Job & CanPerformJob::job () const [inline], [private]
References current_job.
Referenced by for_each_path_location(), has_local_target(), job_start(), push_and_reset(), push_onto_queue(), and update().
job_queue()
std::stack< std::shared_ptr< Job > > & CanPerformJob::job_queue () [inline]
References personal_queue.
Referenced by system_manager::job_system::ensure_has_job().
job_start()
vec2 CanPerformJob::job_start () [inline]
References job(), needs_job(), and Job::start.
Referenced by WIQ_wait_and_return().
local_target()
vec2 CanPerformJob::local_target () const [inline]
References current_job.
needs_job()
bool CanPerformJob::needs_job () const [inline]
References has_job().
Referenced by cleanup_if_completed(), for_each_path_location(), job_start(), and run_tick().
push_and_reset()
void CanPerformJob::push_and_reset (Job * job) [inline]
References current_job, job(), and personal_queue.
Referenced by WIQ_wait_and_return().
push_onto_queue()
void CanPerformJob::push_onto_queue (std::shared_ptr< Job > job) [inline]
References job(), and personal_queue.
run_tick()
void CanPerformJob::run_tick (const std::shared_ptr< Entity > & entity, float dt) [inline]
References current_job, and needs_job().
serialize()
template<typename S >
void CanPerformJob::serialize (S & s) [inline], [private]
References current_job.
update() [1/2]
void CanPerformJob::update (Job * job) [inline]
References current_job, and job().
update() [2/2]
void CanPerformJob::update (JobType starting_jt, JobType idle_jt) [inline]
References idle_job_type, and starting_job_type.
Referenced by system_manager::job_system::ensure_has_job().
update_job_state()
void CanPerformJob::update_job_state (Job::State new_state) [inline]
References current_job.
Member Data Documentation
current_job
std::shared_ptr<Job> CanPerformJob::current_job [private]
Referenced by cleanup_if_completed(), has_job(), job(), local_target(), push_and_reset(), run_tick(), serialize(), update(), and update_job_state().
idle_job_type
JobType CanPerformJob::idle_job_type [private]
Referenced by get_next_job_type(), and update().
personal_queue
std::stack<std::shared_ptr<Job> > CanPerformJob::personal_queue [private]
Referenced by cleanup_if_completed(), job_queue(), push_and_reset(), and push_onto_queue().
starting_job_type
JobType CanPerformJob::starting_job_type [private]
Referenced by get_next_job_type(), and update().
worked_before
bool CanPerformJob::worked_before = false [private]
Referenced by get_next_job_type().
The documentation for this struct was generated from the following file:
src/components/can_perform_job.h