ModelLibrary Struct Reference
#include <model_library.h>
Classes
struct ModelLibraryImpl
struct ModelLoadingInfo
Public Member Functions
const raylib::Model & get (const std::string &name) const
raylib::Model & get (const std::string &name)
void load (ModelLoadingInfo mli)
void unload_all ()
Private Attributes
ModelLibrary::ModelLibraryImpl impl
Member Function Documentation
get() [1/2]
raylib::Model & ModelLibrary::get (const std::string & name) [inline]
get() [2/2]
const raylib::Model & ModelLibrary::get (const std::string & name) const [inline]
Referenced by Preload::load_models(), ModelRenderer::model(), Pill::model(), PillBottle::model(), Bag::model(), and Preload::~Preload().
load()
void ModelLibrary::load (ModelLoadingInfo mli) [inline]
References ModelLibrary::ModelLoadingInfo::filename, ModelLibrary::ModelLoadingInfo::folder, and ModelLibrary::ModelLoadingInfo::libraryname.
unload_all()
void ModelLibrary::unload_all () [inline]
Member Data Documentation
impl
ModelLibrary::ModelLibraryImpl ModelLibrary::impl [private]
The documentation for this struct was generated from the following file:
src/engine/model_library.h