Settings Struct Reference
#include <settings.h>
Public Member Functions
Settings ()
~Settings ()
void update_resolution_from_index (int index)
void update_window_size (rez::ResolutionInfo rez)
void update_last_used_ip_address (const std::string &ip)
void update_master_volume (float nv)
void update_music_volume (float nv)
void update_streamer_safe_box (bool sssb)
void update_post_processing_enabled (bool pp_enabled)
int get_current_resolution_index () const
std::vector< std::string > resolution_options () const
std::string last_used_ip () const
bool load_save_file ()
bool write_save_file ()
void refresh_settings ()
Public Attributes
settings::Data data
Constructor & Destructor Documentation
Settings()
Settings::Settings () [inline]
 Settings()
Settings::~Settings () [inline]
Member Function Documentation
get_current_resolution_index()
int Settings::get_current_resolution_index () const [inline]
last_used_ip()
std::string Settings::last_used_ip () const [inline]
load_save_file()
bool Settings::load_save_file () [inline]
References log_info, log_trace, and log_warn.
refresh_settings()
void Settings::refresh_settings () [inline]
resolution_options()
std::vector< std::string > Settings::resolution_options () const [inline]
update_last_used_ip_address()
void Settings::update_last_used_ip_address (const std::string & ip) [inline]
update_master_volume()
void Settings::update_master_volume (float nv) [inline]
References util::clamp(), MusicLibrary::get(), and log_info.
update_music_volume()
void Settings::update_music_volume (float nv) [inline]
References util::clamp(), and MusicLibrary::get().
update_post_processing_enabled()
void Settings::update_post_processing_enabled (bool pp_enabled) [inline]
update_resolution_from_index()
void Settings::update_resolution_from_index (int index) [inline]
update_streamer_safe_box()
void Settings::update_streamer_safe_box (bool sssb) [inline]
update_window_size()
void Settings::update_window_size (rez::ResolutionInfo rez) [inline]
References __WIN_H, and __WIN_W.
write_save_file()
bool Settings::write_save_file () [inline]
References log_info, and log_warn.
Member Data Documentation
data
settings::Data Settings::data
The documentation for this struct was generated from the following file:
src/engine/settings.h