network Namespace Reference
Namespaces
namespace internal
namespace mp_test
Classes
struct Client
struct ClientPacket
struct Info
struct Server
Typedefs
using Buffer = std::string
using OutputAdapter = bitsery::OutputBufferAdapter< Buffer >
using InputAdapter = bitsery::InputBufferAdapter< Buffer >
using TContext = std::tuple< bitsery::ext::PointerLinkingContext, bitsery::ext::PolymorphicContext< bitsery::ext::StandardRTTI > >
using BitserySerializer = bitsery::Serializer< OutputAdapter, TContext >
using BitseryDeserializer = bitsery::Deserializer< InputAdapter, TContext >
Enumerations
enum struct NetworkRequestError { UNKNOWN_ERROR = 0
 }
Functions
tl::expected< std::string, NetworkRequestError > get_remote_ip_address ()
static void log_debug (ESteamNetworkingSocketsDebugOutputType eType, const char *pszMsg)
std::ostream & operator<< (std::ostream &os, const ClientPacket::Msg &msgtype)
std::ostream & operator<< (std::ostream &os, const ClientPacket::MsgType &msgtype)
std::ostream & operator<< (std::ostream &os, const ClientPacket &packet)
template<typename S >
void serialize (S &s, ClientPacket &packet)
static Buffer serialize_to_entity (Entity *entity)
static void deserialize_to_entity (Entity *entity, const std::string &msg)
static ClientPacket deserialize_to_packet (const std::string &msg)
static Buffer serialize_to_buffer (ClientPacket packet)
Variables
constexpr int MAX_NAME_LENGTH = 25
static long total_ping = 0
static long there_ping = 0
static long return_ping = 0
constexpr int DEFAULT_PORT = 770
constexpr int MAX_CLIENTS = 4
constexpr int MAX_ANNOUNCEMENT_LENGTH = 200
constexpr int SERVER_CLIENT_ID = -1
constexpr int MAX_INPUTS = 100
static SteamNetworkingMicroseconds START_TIME
static std::shared_ptr< Server > g_server
Typedef Documentation
BitseryDeserializer
using network::BitseryDeserializer = typedef bitsery::Deserializer<InputAdapter, TContext>
BitserySerializer
using network::BitserySerializer = typedef bitsery::Serializer<OutputAdapter, TContext>
Buffer
using network::Buffer = typedef std::string
InputAdapter
using network::InputAdapter = typedef bitsery::InputBufferAdapter<Buffer>
OutputAdapter
using network::OutputAdapter = typedef bitsery::OutputBufferAdapter<Buffer>
TContext
using network::TContext = typedef std::tuple<bitsery::ext::PointerLinkingContext, bitsery::ext::PolymorphicContext<bitsery::ext::StandardRTTI> >
Enumeration Type Documentation
NetworkRequestError
enum struct network::NetworkRequestError [strong]
Enumerator
UNKNOWN_ERROR
Function Documentation
deserialize_to_entity()
static void network::deserialize_to_entity (Entity * entity, const std::string & msg) [static]
References deserialize_to_entity(), and log_error.
Referenced by deserialize_to_entity(), entity_components(), test_adding_single_component_serialdeserial(), validate_custom_hold_position_persisits(), validate_held_item_serialized(), validate_name_change_persisits(), validate_trigger_area_serialized(), and validate_wall_color_serialized().
deserialize_to_packet()
static ClientPacket network::deserialize_to_packet (const std::string & msg) [static]
References deserialize_to_packet().
Referenced by deserialize_to_packet(), and network::Server::server_process_message_string().
get_remote_ip_address()
tl::expected< std::string, NetworkRequestError > network::get_remote_ip_address ()
References log_warn, and UNKNOWN_ERROR.
Referenced by NetworkLayer::NetworkLayer().
log_debug()
static void network::log_debug (ESteamNetworkingSocketsDebugOutputType eType, const char * pszMsg) [static]
References START_TIME.
Referenced by network::Info::init_connections().
operator<<() [1/3]
std::ostream & network::operator<< (std::ostream & os, const ClientPacket & packet)
References network::ClientPacket::client_id, network::ClientPacket::msg, and network::ClientPacket::msg_type.
operator<<() [2/3]
std::ostream & network::operator<< (std::ostream & os, const ClientPacket::Msg & msgtype)
operator<<() [3/3]
std::ostream & network::operator<< (std::ostream & os, const ClientPacket::MsgType & msgtype)
serialize()
template<typename S >
void network::serialize (S & s, ClientPacket & packet)
References network::ClientPacket::channel, network::ClientPacket::client_id, network::ClientPacket::msg, and network::ClientPacket::msg_type.
serialize_to_buffer()
static Buffer network::serialize_to_buffer (ClientPacket packet) [static]
References serialize_to_buffer().
Referenced by network::Server::send_client_packet_to_all(), network::Server::send_client_packet_to_client(), and serialize_to_buffer().
serialize_to_entity()
static Buffer network::serialize_to_entity (Entity * entity) [static]
References serialize_to_entity().
Referenced by entity_components(), serialize_to_entity(), test_adding_single_component_serialdeserial(), validate_custom_hold_position_persisits(), validate_held_item_serialized(), validate_name_change_persisits(), validate_trigger_area_serialized(), and validate_wall_color_serialized().
Variable Documentation
DEFAULT_PORT
constexpr int network::DEFAULT_PORT = 770 [constexpr]
Referenced by network::internal::Client::set_address(), and network::Info::set_role().
g_server
std::shared_ptr<Server> network::g_server [static]
Referenced by network::Server::queue_packet(), network::Server::start(), and network::Server::stop().
MAX_ANNOUNCEMENT_LENGTH
constexpr int network::MAX_ANNOUNCEMENT_LENGTH = 200 [constexpr]
MAX_CLIENTS
constexpr int network::MAX_CLIENTS = 4 [constexpr]
MAX_INPUTS
constexpr int network::MAX_INPUTS = 100 [constexpr]
MAX_NAME_LENGTH
constexpr int network::MAX_NAME_LENGTH = 25 [constexpr]
Referenced by settings::Data::serialize().
return_ping
long network::return_ping = 0 [static]
Referenced by network::Client::client_process_message_string(), and FPSLayer::onDraw().
SERVER_CLIENT_ID
constexpr int network::SERVER_CLIENT_ID = -1 [constexpr]
Referenced by network::Server::process_ping_message(), network::Server::process_player_join_packet(), network::Server::process_player_leave(), network::Server::send_announcement(), network::Info::send_current_menu_state(), and network::Server::send_map_state().
START_TIME
SteamNetworkingMicroseconds network::START_TIME [static]
Referenced by network::Info::init_connections(), and log_debug().
there_ping
long network::there_ping = 0 [static]
Referenced by network::Client::client_process_message_string(), and FPSLayer::onDraw().
total_ping
long network::total_ping = 0 [static]
Referenced by network::Client::client_process_message_string(), and FPSLayer::onDraw().