network::Info Struct Reference
#include <network.h>
Public Types
enum Role { s_None = 1 << 0
, s_Host = 1 << 1
, s_Client = 1 << 2
 }
Public Member Functions
bool is_host ()
bool is_client ()
bool has_role ()
bool missing_role ()
void set_role (Role role)
void lock_in_username ()
void unlock_username ()
std::string & host_ip_address ()
void lock_in_ip ()
bool has_set_ip ()
bool has_not_set_ip ()
bool has_username ()
bool missing_username ()
Info ()
~Info ()
void cleanup_server ()
void send_current_menu_state (float dt)
void tick (float dt)
Static Public Member Functions
static void init_connections ()
static void shutdown_connections ()
Public Attributes
enum network::Info::Role desired_role = s_None
std::thread::id client_thread_id
std::thread::id server_thread_id
std::shared_ptr< Client > client
std::thread server_thread
bool username_set = false
TriggerOnDt menu_state_tick_trigger = TriggerOnDt(0.1f)
Member Enumeration Documentation
Role
enum network::Info::Role
Enumerator
s_None
s_Host
s_Client
Constructor & Destructor Documentation
Info()
network::Info::Info () [inline]
 Info()
network::Info::~Info () [inline]
References client, desired_role, and s_None.
Member Function Documentation
cleanup_server()
void network::Info::cleanup_server () [inline]
References server_thread, server_thread_id, and network::Server::stop().
has_not_set_ip()
bool network::Info::has_not_set_ip () [inline]
References has_set_ip().
Referenced by tick().
has_role()
bool network::Info::has_role () [inline]
References is_client(), and is_host().
Referenced by missing_role().
has_set_ip()
bool network::Info::has_set_ip () [inline]
References client.
Referenced by has_not_set_ip().
has_username()
bool network::Info::has_username () [inline]
References username_set.
Referenced by missing_username().
host_ip_address()
std::string & network::Info::host_ip_address () [inline]
References client.
init_connections()
static void network::Info::init_connections () [inline], [static]
References network::log_debug(), log_warn, and network::START_TIME.
Referenced by NetworkLayer::NetworkLayer().
is_client()
bool network::Info::is_client () [inline]
References desired_role, and s_Client.
Referenced by has_role().
is_host()
bool network::Info::is_host () [inline]
References desired_role, and s_Host.
Referenced by has_role(), and tick().
lock_in_ip()
void network::Info::lock_in_ip () [inline]
References client.
lock_in_username()
void network::Info::lock_in_username () [inline]
References username_set.
missing_role()
bool network::Info::missing_role () [inline]
References has_role().
Referenced by tick().
missing_username()
bool network::Info::missing_username () [inline]
References has_username().
send_current_menu_state()
void network::Info::send_current_menu_state (float dt) [inline]
References network::ClientPacket::GameState, menu_state_tick_trigger, network::Server::queue_packet(), network::SERVER_CLIENT_ID, and TriggerOnDt::test().
Referenced by tick().
set_role()
void network::Info::set_role (Role role) [inline]
References client, client_thread_id, network::DEFAULT_PORT, desired_role, GLOBALS, log_info, s_Client, s_Host, server_thread, server_thread_id, GlobalValueRegister::set(), and network::Server::start().
shutdown_connections()
static void network::Info::shutdown_connections () [inline], [static]
Referenced by NetworkLayer::~NetworkLayer().
tick()
void network::Info::tick (float dt) [inline]
References client, has_not_set_ip(), is_host(), missing_role(), and send_current_menu_state().
unlock_username()
void network::Info::unlock_username () [inline]
References username_set.
Member Data Documentation
client
std::shared_ptr<Client> network::Info::client
Referenced by has_set_ip(), host_ip_address(), lock_in_ip(), set_role(), tick(), and ~Info().
client_thread_id
std::thread::id network::Info::client_thread_id
Referenced by set_role().
desired_role
enum network::Info::Role network::Info::desired_role = s_None
Referenced by is_client(), is_host(), set_role(), and ~Info().
menu_state_tick_trigger
TriggerOnDt network::Info::menu_state_tick_trigger = TriggerOnDt(0.1f)
Referenced by send_current_menu_state().
server_thread
std::thread network::Info::server_thread
Referenced by cleanup_server(), and set_role().
server_thread_id
std::thread::id network::Info::server_thread_id
Referenced by cleanup_server(), and set_role().
username_set
bool network::Info::username_set = false
Referenced by has_username(), lock_in_username(), and unlock_username().
The documentation for this struct was generated from the following file:
src/network/network.h