src/engine/is_server.h File Reference
#include <thread>
#include `globals_register.h`
Functions
static bool is_server ()
Function Documentation
is_server()
static bool is_server () [static]
References GlobalValueRegister::get_or_default(), and GLOBALS.
Referenced by system_manager::logging_manager::announce(), EntityHelper::get_entities(), and ItemHelper::get_items().