CanBeGhostPlayer Struct Reference
#include <can_be_ghost_player.h>
Public Member Functions
virtual ~CanBeGhostPlayer ()
bool is_ghost () const
bool is_not_ghost () const
void update (bool g)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
bool ghost = false
Constructor & Destructor Documentation
 CanBeGhostPlayer()
virtual CanBeGhostPlayer::~CanBeGhostPlayer () [inline], [virtual]
Member Function Documentation
is_ghost()
bool CanBeGhostPlayer::is_ghost () const [inline]
References ghost.
Referenced by is_not_ghost(), and system_manager::render_normal().
is_not_ghost()
bool CanBeGhostPlayer::is_not_ghost () const [inline]
References is_ghost().
Referenced by system_manager::render_debug().
serialize()
template<typename S >
void CanBeGhostPlayer::serialize (S & s) [inline], [private]
References ghost.
update()
void CanBeGhostPlayer::update (bool g) [inline]
References ghost.
Member Data Documentation
ghost
bool CanBeGhostPlayer::ghost = false [private]
Referenced by is_ghost(), serialize(), and update().
The documentation for this struct was generated from the following file:
src/components/can_be_ghost_player.h