CanBePushed Struct Reference
#include <can_be_pushed.h>
Public Member Functions
virtual ~CanBePushed ()
vec3 pushed_force () const
void update (vec3 f)
void update_x (float x)
void update_y (float y)
void update_z (float z)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Private Member Functions
template<typename S >
void serialize (S &s)
Private Attributes
vec3 force {0.0, 0.0, 0.0}
Constructor & Destructor Documentation
 CanBePushed()
virtual CanBePushed::~CanBePushed () [inline], [virtual]
Member Function Documentation
pushed_force()
vec3 CanBePushed::pushed_force () const [inline]
References force.
Referenced by system_manager::move_entity_based_on_push_force(), and system_manager::person_update_given_new_pos().
serialize()
template<typename S >
void CanBePushed::serialize (S & s) [inline], [private]
References force.
update()
void CanBePushed::update (vec3 f) [inline]
References force.
Referenced by system_manager::person_update_given_new_pos().
update_x()
void CanBePushed::update_x (float x) [inline]
References force.
Referenced by system_manager::move_entity_based_on_push_force().
update_y()
void CanBePushed::update_y (float y) [inline]
References force.
update_z()
void CanBePushed::update_z (float z) [inline]
References force.
Referenced by system_manager::move_entity_based_on_push_force().
Member Data Documentation
force
vec3 CanBePushed::force {0.0, 0.0, 0.0} [private]
Referenced by pushed_force(), serialize(), update(), update_x(), update_y(), and update_z().
The documentation for this struct was generated from the following file:
src/components/can_be_pushed.h