Grabber Struct Reference
#include <grabber.h>
Public Member Functions
Grabber ()
Grabber (vec2 pos)
virtual void in_round_update (float dt) override
Public Member Functions inherited from Conveyer
void add_static_components ()
Conveyer ()
Conveyer (vec2 pos)
Conveyer (vec2 pos, Color face_color, Color base_color)
void update_model ()
bool can_take_item_from () const
virtual void in_round_update (float dt) override
Public Member Functions inherited from Furniture
Furniture (vec2 pos, Color face_color_in)
Furniture (vec3 pos, Color face_color_in)
Furniture (vec2 pos, Color face_color_in, Color base_color_in)
virtual bool add_to_navmesh () override
virtual bool can_rotate () const
virtual bool can_be_picked_up ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr) override
virtual bool has_held_item () const
Public Member Functions inherited from Entity
template<typename T >
bool has () const
template<typename T , typename... TArgs>
T & addComponent (TArgs &&... args)
template<typename T >
T & get () const
void add_static_components ()
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
virtual void announce (std::string text)
virtual bool is_snappable ()
virtual bool collides (BoundingBox b) const
virtual BoundingBox raw_bounds () const
virtual BoundingBox bounds () const
vec3 snap_position () const
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void update (float dt) final
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, Transform::Transform::FrontFaceDirection direction)
Public Attributes inherited from Conveyer
float relative_item_pos = Conveyer::ITEM_START
float SPEED = 0.5f
bool can_take_from = false
Public Attributes inherited from Entity
int id
ComponentBitSet componentSet
ComponentArray componentArray
bool cleanup = false
bool is_held = false
Static Public Attributes inherited from Conveyer
static constexpr float ITEM_START = -0.5f
static constexpr float ITEM_END = 0.5f
Protected Member Functions inherited from Furniture
Furniture ()
void add_static_components ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec3 size () const
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void in_round_update (float)
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Constructor & Destructor Documentation
Grabber() [1/2]
Grabber::Grabber () [inline]
Grabber() [2/2]
Grabber::Grabber (vec2 pos) [inline], [explicit]
Member Function Documentation
in_round_update()
virtual void Grabber::in_round_update (float dt) [inline], [override], [virtual]
Reimplemented from Conveyer.
References Conveyer::can_take_item_from(), Item::FURNITURE, Conveyer::in_round_update(), CanHoldItem::item(), Conveyer::ITEM_START, Conveyer::relative_item_pos, and CanHoldItem::update().
serialize()
template<typename S >
void Grabber::serialize (S & s) [inline], [private]
The documentation for this struct was generated from the following file:
src/furniture/grabber.h