src/tests/component.h File Reference
#include `../entity.h`
#include `../engine/assert.h`
#include `../engine/defer.h`
#include `../network/shared.h`
Functions
void compare_and_validate_components (Entity *a, Entity *b)
Entity * mk_entity ()
void entity_components ()
void test_adding_single_component_serialdeserial ()
void validate_name_change_persisits ()
void validate_custom_hold_position_persisits ()
void validate_held_item_serialized ()
void validate_wall_color_serialized ()
void validate_trigger_area_serialized ()
void all_tests ()
Function Documentation
all_tests()
void all_tests ()
References entity_components(), test_adding_single_component_serialdeserial(), validate_custom_hold_position_persisits(), validate_held_item_serialized(), validate_name_change_persisits(), validate_trigger_area_serialized(), and validate_wall_color_serialized().
Referenced by tests::run_all().
compare_and_validate_components()
void compare_and_validate_components (Entity * a, Entity * b)
References Entity::componentArray, Entity::componentSet, max_num_components, and VALIDATE.
Referenced by entity_components(), test_adding_single_component_serialdeserial(), validate_custom_hold_position_persisits(), validate_held_item_serialized(), validate_name_change_persisits(), validate_trigger_area_serialized(), and validate_wall_color_serialized().
entity_components()
void entity_components ()
References compare_and_validate_components(), network::deserialize_to_entity(), mk_entity(), and network::serialize_to_entity().
Referenced by all_tests().
mk_entity()
Entity * mk_entity ()
References make_entity(), and DebugOptions::name.
Referenced by entity_components(), test_adding_single_component_serialdeserial(), validate_custom_hold_position_persisits(), validate_held_item_serialized(), validate_name_change_persisits(), validate_trigger_area_serialized(), and validate_wall_color_serialized().
test_adding_single_component_serialdeserial()
void test_adding_single_component_serialdeserial ()
References Entity::addComponent(), compare_and_validate_components(), network::deserialize_to_entity(), mk_entity(), and network::serialize_to_entity().
Referenced by all_tests().
validate_custom_hold_position_persisits()
void validate_custom_hold_position_persisits ()
References Entity::addComponent(), compare_and_validate_components(), CustomHeldItemPosition::Conveyer, network::deserialize_to_entity(), Entity::get(), M_TEST_EQ, mk_entity(), and network::serialize_to_entity().
Referenced by all_tests().
validate_held_item_serialized()
void validate_held_item_serialized ()
References Entity::addComponent(), compare_and_validate_components(), network::deserialize_to_entity(), Entity::get(), CanHoldItem::item(), M_TEST_EQ, M_TEST_NEQ, mk_entity(), and network::serialize_to_entity().
Referenced by all_tests().
validate_name_change_persisits()
void validate_name_change_persisits ()
References Entity::addComponent(), compare_and_validate_components(), network::deserialize_to_entity(), Entity::get(), M_TEST_EQ, M_TEST_NEQ, mk_entity(), and network::serialize_to_entity().
Referenced by all_tests().
validate_trigger_area_serialized()
void validate_trigger_area_serialized ()
References compare_and_validate_components(), network::deserialize_to_entity(), Entity::get(), Entity::has(), M_TEST_EQ, M_TEST_T, entities::make_trigger_area(), mk_entity(), network::serialize_to_entity(), and IsTriggerArea::title().
Referenced by all_tests().
validate_wall_color_serialized()
void validate_wall_color_serialized ()
References SimpleColoredBoxRenderer::base(), compare_and_validate_components(), network::deserialize_to_entity(), SimpleColoredBoxRenderer::face(), Entity::get(), Entity::has(), M_TEST_EQ, M_TEST_T, entities::make_wall(), mk_entity(), ui::color::saffron, and network::serialize_to_entity().
Referenced by all_tests().