TextureLibrary Struct Reference
#include <texture_library.h>
Classes
struct TextureLibraryImpl
Public Member Functions
void unload_all ()
raylib::Texture2D & get (const std::string &name)
const raylib::Texture2D & get (const std::string &name) const
void load (const char *filename, const char *name)
Private Attributes
TextureLibrary::TextureLibraryImpl impl
Member Function Documentation
get() [1/2]
raylib::Texture2D & TextureLibrary::get (const std::string & name) [inline]
Referenced by Preload::load_textures(), LobbyMapInfo::onDraw(), SpeechBubble::render(), and Preload::~Preload().
get() [2/2]
const raylib::Texture2D & TextureLibrary::get (const std::string & name) const [inline]
load()
void TextureLibrary::load (const char * filename, const char * name) [inline]
unload_all()
void TextureLibrary::unload_all () [inline]
Member Data Documentation
impl
TextureLibrary::TextureLibraryImpl TextureLibrary::impl [private]
The documentation for this struct was generated from the following file:
src/engine/texture_library.h