CollectsUserInput Struct Reference
#include <collects_user_input.h>
Public Member Functions
virtual ~CollectsUserInput ()
auto & reset ()
auto & write (InputName input)
auto & publish (float dt)
Public Member Functions inherited from BaseComponent
BaseComponent ()
BaseComponent (BaseComponent &&)=default
virtual void onAttach ()
virtual ~BaseComponent ()
Public Attributes
UserInputs inputs
InputSet pressed
Private Member Functions
template<typename S >
void serialize (S &s)
Constructor & Destructor Documentation
 CollectsUserInput()
virtual CollectsUserInput::~CollectsUserInput () [inline], [virtual]
Member Function Documentation
publish()
auto & CollectsUserInput::publish (float dt) [inline]
References inputs, pressed, and reset().
Referenced by system_manager::input_process_manager::collect_user_input().
reset()
auto & CollectsUserInput::reset () [inline]
References pressed.
Referenced by publish().
serialize()
template<typename S >
void CollectsUserInput::serialize (S & s) [inline], [private]
write()
auto & CollectsUserInput::write (InputName input) [inline]
References pressed.
Referenced by system_manager::input_process_manager::collect_user_input().
Member Data Documentation
inputs
UserInputs CollectsUserInput::inputs
Referenced by publish(), and network::Client::send_player_input_packet().
pressed
InputSet CollectsUserInput::pressed
Referenced by publish(), reset(), and write().
The documentation for this struct was generated from the following file:
src/components/collects_user_input.h