src/engine/globals.h File Reference
#include <string>
Namespaces
namespace network
Functions
template<typename Str >
constexpr size_t hashString (const Str &toHash)
int WIN_W ()
float WIN_WF ()
int WIN_H ()
float WIN_HF ()
Variables
static int __WIN_H = 720
static int __WIN_W = 1280
static int LOG_LEVEL = 2
constexpr int network::MAX_NAME_LENGTH = 25
static long network::total_ping = 0
static long network::there_ping = 0
static long network::return_ping = 0
Function Documentation
hashString()
template<typename Str >
constexpr size_t hashString (const Str & toHash) [constexpr]
Referenced by GameMapInfo::update_seed().
WIN_H()
int WIN_H () [inline]
References __WIN_H.
Referenced by ui::IUIContextRenderTextures::get_new_render_texture(), StreamerSafeLayer::onDraw(), startup(), StreamerSafeLayer::StreamerSafeLayer(), tests::test_just_root(), tests::test_single_child(), tests::test_two_children(), and tests::test_two_children_parent_size().
WIN_HF()
float WIN_HF () [inline]
References __WIN_H.
Referenced by GameDebugLayer::debug_ui(), MenuLayer::draw_menu_buttons(), MenuLayer::draw_title_section(), SettingsLayer::draw_ui(), ui::components::mk_root(), NetworkLayer::onDraw(), BasePauseLayer::onDraw(), ToastLayer::onDraw(), tests::test_just_root(), tests::test_single_child(), tests::test_two_children(), and tests::test_two_children_parent_size().
WIN_W()
int WIN_W () [inline]
References __WIN_W.
Referenced by ui::IUIContextRenderTextures::get_new_render_texture(), StreamerSafeLayer::onDraw(), startup(), tests::test_just_root(), tests::test_single_child(), and tests::test_two_children().
WIN_WF()
float WIN_WF () [inline]
References __WIN_W.
Referenced by GameDebugLayer::debug_ui(), ui::components::mk_root(), BasePauseLayer::onDraw(), ToastLayer::onDraw(), tests::test_just_root(), tests::test_single_child(), tests::test_two_children(), and tests::test_two_children_parent_size().
Variable Documentation
__WIN_H
int __WIN_H = 720 [static]
Referenced by Settings::update_window_size(), WIN_H(), and WIN_HF().
__WIN_W
int __WIN_W = 1280 [static]
Referenced by Settings::update_window_size(), WIN_W(), and WIN_WF().
LOG_LEVEL
int LOG_LEVEL = 2 [static]