Customer Struct Reference
#include <customer.h>
Public Member Functions
Customer ()
Customer (vec3 p, Color face_color_in, Color base_color_in)
Customer (vec2 p, Color face_color_in, Color base_color_in)
Customer (vec3 p, Color c)
Customer (vec2 p, Color c)
void init ()
virtual float base_speed () override
virtual float stagger_mult () override
void wait_in_queue (float)
void wait (float dt)
virtual void get_starting_job () override
virtual void process_job (float dt) override
virtual void in_round_update (float dt) override
virtual void render_normal () const override
Public Member Functions inherited from AIPerson
AIPerson ()
AIPerson (vec3 p, Color face_color_in, Color base_color_in)
AIPerson (vec2 p, Color face_color_in, Color base_color_in)
AIPerson (vec3 p, Color c)
AIPerson (vec2 p, Color c)
virtual float base_speed () override
virtual float stagger_mult ()
virtual void render_debug_mode () const override
virtual vec3 update_xaxis_position (float dt) override
virtual vec3 update_zaxis_position (float dt) override
virtual Job * get_wandering_job ()
void travel_on_path (vec2 me)
bool navigate_to (vec2 goal)
virtual void wandering ()
virtual void get_starting_job ()
virtual void get_idle_job ()
virtual void find_new_job ()
virtual void process_job (float)
virtual void in_round_update (float dt) override
virtual void announce (std::string text)
virtual bool is_snappable () override
Public Member Functions inherited from Person
Person (vec3 p, Color face_color_in, Color base_color_in)
Person (vec2 p, Color face_color_in, Color base_color_in)
Person (vec3 p, Color c)
Person (vec2 p, Color c)
virtual vec3 update_xaxis_position (float dt)=0
virtual vec3 update_zaxis_position (float dt)=0
virtual float base_speed ()
virtual vec3 size () const override
void select_next_character_model ()
virtual std::optional< ModelInfo > model () const override
void handle_collision (int facedir_x, vec3 new_pos_x, int facedir_z, vec3 new_pos_z)
std::tuple< int, int > get_face_direction (vec3 new_pos_x, vec3 new_pos_z)
void update_facing_direction (int facedir_x, int facedir_z)
virtual void always_update (float dt) override
Public Member Functions inherited from Entity
FrontFaceDirection offsetFaceDirection (FrontFaceDirection startingDirection, float offset) const
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
void update_name (const std::string &new_name)
virtual bool can_take_item_from () const
virtual bool collides (BoundingBox b) const
virtual BoundingBox bounds () const
virtual void update_position (const vec3 &p)
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void render () const final
virtual void update (float dt) final
Public Attributes
std::optional< SpeechBubble > bubble
std::shared_ptr< Ailment > ailment
Public Attributes inherited from AIPerson
std::stack< std::shared_ptr< Job > > personal_queue
std::shared_ptr< Job > job
Public Attributes inherited from Entity
const std::map< FrontFaceDirection, float > FrontFaceDirectionMap
const std::map< int, FrontFaceDirection > DirectionToFrontFaceMap
int id
vec3 raw_position
vec3 prev_position
vec3 position
vec3 pushed_force {0.0, 0.0, 0.0}
Color face_color
Color base_color
bool cleanup = false
bool is_highlighted = false
bool is_held = false
FrontFaceDirection face_direction = FrontFaceDirection::FORWARD
std::shared_ptr< Item > held_item = nullptr
int name_length = 1
std::string name = ``
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Public Types inherited from Entity
enum FrontFaceDirection { FORWARD = 0x1
, RIGHT = 0x2
, BACK = 0x4
, LEFT = 0x8
 }
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, FrontFaceDirection direction)
Protected Member Functions inherited from Person
Person ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual void render_debug_mode () const
virtual void render_highlighted () const
virtual void render_normal () const
virtual void render_floating_name () const
virtual std::optional< ModelInfo > model () const
vec3 snap_position () const
virtual void update_held_item_position ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void always_update (float)
virtual void planning_update (float)
virtual void in_round_update (float)
virtual bool is_snappable ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Constructor & Destructor Documentation
Customer() [1/5]
Customer::Customer () [inline]
References init().
Customer() [2/5]
Customer::Customer (vec3 p, Color face_color_in, Color base_color_in) [inline]
References init().
Customer() [3/5]
Customer::Customer (vec2 p, Color face_color_in, Color base_color_in) [inline]
References init().
Customer() [4/5]
Customer::Customer (vec3 p, Color c) [inline]
References init().
Customer() [5/5]
Customer::Customer (vec2 p, Color c) [inline]
References init().
Member Function Documentation
base_speed()
virtual float Customer::base_speed () [inline], [override], [virtual]
Reimplemented from AIPerson.
References ailment, and base_speed().
Referenced by base_speed().
get_starting_job()
virtual void Customer::get_starting_job () [inline], [override], [virtual]
Reimplemented from AIPerson.
References AIPerson::job, and WaitInQueue.
in_round_update()
virtual void Customer::in_round_update (float dt) [inline], [override], [virtual]
Reimplemented from AIPerson.
References bubble, AIPerson::in_round_update(), and Entity::raw_position.
init()
void Customer::init () [inline]
References get_random_name(), and Entity::update_name().
Referenced by Customer().
process_job()
virtual void Customer::process_job (float dt) [inline], [override], [virtual]
Reimplemented from AIPerson.
References AIPerson::job, wait(), Wait, wait_in_queue(), WaitInQueue, AIPerson::wandering(), and Wandering.
render_normal()
virtual void Customer::render_normal () const [inline], [override], [virtual]
Reimplemented from Entity.
References Entity::render_normal().
serialize()
template<typename S >
void Customer::serialize (S & s) [inline], [private]
stagger_mult()
virtual float Customer::stagger_mult () [inline], [override], [virtual]
Reimplemented from AIPerson.
References ailment.
wait()
void Customer::wait (float dt) [inline]
References AIPerson::announce(), Job::Completed, Job::HeadingToEnd, Job::HeadingToStart, Job::Initialize, AIPerson::job, AIPerson::navigate_to(), Job::WorkingAtEnd, and Job::WorkingAtStart.
Referenced by process_job().
wait_in_queue()
void Customer::wait_in_queue (float) [inline]
References AIPerson::announce(), Job::Completed, Job::HeadingToEnd, Job::HeadingToStart, Entity::held_item, Job::Initialize, AIPerson::job, AIPerson::navigate_to(), AIPerson::personal_queue, Entity::position, TILESIZE, vec::to2(), Wait, Job::WorkingAtEnd, and Job::WorkingAtStart.
Referenced by process_job().
Member Data Documentation
ailment
std::shared_ptr<Ailment> Customer::ailment
Referenced by base_speed(), and stagger_mult().
bubble
std::optional<SpeechBubble> Customer::bubble
Referenced by in_round_update().
The documentation for this struct was generated from the following file:
src/customer.h