MusicLibrary Struct Reference
#include <music_library.h>
Classes
struct MusicLibraryImpl
Public Member Functions
const raylib::Music & get (const std::string &name) const
raylib::Music & get (const std::string &name)
void load (const char *filename, const char *name)
void update_volume (float new_v)
void unload_all ()
Private Attributes
float current_volume = 1.f
MusicLibrary::MusicLibraryImpl impl
Member Function Documentation
get() [1/2]
raylib::Music & MusicLibrary::get (const std::string & name) [inline]
get() [2/2]
const raylib::Music & MusicLibrary::get (const std::string & name) const [inline]
Referenced by Preload::load_music(), GameLayer::play_music(), MenuLayer::play_music(), Settings::update_master_volume(), Settings::update_music_volume(), and Preload::~Preload().
load()
void MusicLibrary::load (const char * filename, const char * name) [inline]
unload_all()
void MusicLibrary::unload_all () [inline]
update_volume()
void MusicLibrary::update_volume (float new_v) [inline]
Member Data Documentation
current_volume
float MusicLibrary::current_volume = 1.f [private]
impl
MusicLibrary::MusicLibraryImpl MusicLibrary::impl [private]
The documentation for this struct was generated from the following file:
src/engine/music_library.h