MenuLayer Struct Reference
#include <menulayer.h>
Public Member Functions
MenuLayer ()
virtual ~MenuLayer ()
virtual void onEvent (Event &event) override
bool onGamepadAxisMoved (GamepadAxisMovedEvent &event)
bool onKeyPressed (KeyPressedEvent &event)
bool onGamepadButtonPressed (GamepadButtonPressedEvent &event)
void play_music ()
void draw_menu_buttons ()
void draw_title_section ()
virtual void onUpdate (float) override
virtual void onDraw (float dt) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
virtual void onEvent (Event &)=0
const std::string & getname () const
Public Attributes
std::shared_ptr< ui::UIContext > ui_context
Public Attributes inherited from Layer
int id
std::string name
Constructor & Destructor Documentation
MenuLayer()
MenuLayer::MenuLayer () [inline]
References ui_context.
 MenuLayer()
virtual MenuLayer::~MenuLayer () [inline], [virtual]
Member Function Documentation
draw_menu_buttons()
void MenuLayer::draw_menu_buttons () [inline]
References menu::About, ui::components::mk_but_pad(), ui::components::mk_button(), ui::components::mk_padding(), MK_UUID, menu::Network, menu::Settings, Size_Pct, Size_Px, ui_context, and WIN_HF().
Referenced by onDraw().
draw_title_section()
void MenuLayer::draw_title_section () [inline]
References ui::components::mk_padding(), Size_Pct, Size_Px, ui_context, and WIN_HF().
Referenced by onDraw().
onDraw()
virtual void MenuLayer::onDraw (float dt) [inline], [override], [virtual]
Implements Layer.
References ext::clear_background(), draw_menu_buttons(), draw_title_section(), ui::components::mk_root(), PROFILE, menu::Root, and ui_context.
onEvent()
virtual void MenuLayer::onEvent (Event & event) [inline], [override], [virtual]
Implements Layer.
References EventDispatcher::dispatch(), onGamepadAxisMoved(), onGamepadButtonPressed(), and onKeyPressed().
onGamepadAxisMoved()
bool MenuLayer::onGamepadAxisMoved (GamepadAxisMovedEvent & event) [inline]
References menu::Root, and ui_context.
Referenced by onEvent().
onGamepadButtonPressed()
bool MenuLayer::onGamepadButtonPressed (GamepadButtonPressedEvent & event) [inline]
References menu::Root, and ui_context.
Referenced by onEvent().
onKeyPressed()
bool MenuLayer::onKeyPressed (KeyPressedEvent & event) [inline]
References menu::Root, and ui_context.
Referenced by onEvent().
onUpdate()
virtual void MenuLayer::onUpdate (float) [inline], [override], [virtual]
Implements Layer.
References play_music(), PROFILE, and menu::Root.
play_music()
void MenuLayer::play_music () [inline]
References MusicLibrary::get().
Referenced by onUpdate().
Member Data Documentation
ui_context
std::shared_ptr<ui::UIContext> MenuLayer::ui_context
Referenced by draw_menu_buttons(), draw_title_section(), MenuLayer(), onDraw(), onGamepadAxisMoved(), onGamepadButtonPressed(), and onKeyPressed().
The documentation for this struct was generated from the following file:
src/menulayer.h