vec Namespace Reference
Functions
static void forEachNeighbor (int i, int j, std::function< void(const vec2 &)> cb, int step=1)
static std::vector< vec2 > get_neighbors (int i, int j, int step=1)
float constexpr newton_raphson (float x, float cur, float prev)
float constexpr ce_sqrtf (float x)
constexpr float distance (vec2 a, vec2 b)
float dot2 (const vec2 &a, const vec2 &b)
vec2 norm (const vec2 &a)
constexpr vec3 to3 (vec2 position)
constexpr vec2 to2 (vec3 position)
vec2 snap (vec2 position)
vec3 snap (vec3 position)
vec2 lerp (vec2 a, vec2 b, float pct)
Variables
static constexpr int neigh_x [8] = {-1, -1, -1, 0, 0, 1, 1, 1}
static constexpr int neigh_y [8] = {-1, 0, 1, -1, 1, -1, 0, 1}
Function Documentation
ce_sqrtf()
float constexpr vec::ce_sqrtf (float x) [constexpr]
References newton_raphson().
Referenced by distance().
distance()
constexpr float vec::distance (vec2 a, vec2 b) [constexpr]
References ce_sqrtf().
Referenced by test::canvisit(), astar::distance_between(), astar::find_path_impl(), EntityHelper::getClosestMatchingEntity(), EntityHelper::getEntitiesInRange(), ItemHelper::getitemsInRange(), EntityHelper::getMatchingEntityInFront(), Job::is_at_position(), EntityHelper::isWalkableRawEntities(), astar::path_estimate(), and system_manager::sophie().
dot2()
float vec::dot2 (const vec2 & a, const vec2 & b) [inline]
Referenced by norm().
forEachNeighbor()
static void vec::forEachNeighbor (int i, int j, std::function< void(const vec2 &)> cb, int step = 1) [static]
References neigh_x, and neigh_y.
Referenced by get_neighbors(), and astar::get_neighbors().
get_neighbors()
static std::vector< vec2 > vec::get_neighbors (int i, int j, int step = 1) [static]
References forEachNeighbor().
lerp()
vec2 vec::lerp (vec2 a, vec2 b, float pct) [inline]
Referenced by tests::test_half(), and tests::test_tenth().
newton_raphson()
float constexpr vec::newton_raphson (float x, float cur, float prev) [constexpr]
References newton_raphson().
Referenced by ce_sqrtf(), and newton_raphson().
norm()
vec2 vec::norm (const vec2 & a) [inline]
References dot2().
snap() [1/2]
vec2 vec::snap (vec2 position) [inline]
References TILESIZE.
Referenced by system_manager::input_process_manager::planning::drop_held_furniture(), EntityHelper::getMatchingEntityInFront(), Transform::snap_position(), and Item::snap_position().
snap() [2/2]
vec3 vec::snap (vec3 position) [inline]
References TILESIZE.
to2()
constexpr vec2 vec::to2 (vec3 position) [constexpr]
Referenced by Transform::as2(), ItemHelper::getitemsInRange(), EntityHelper::getMatchingEntityInFront(), and Transform::tile_infront().
to3()
constexpr vec3 vec::to3 (vec2 position) [constexpr]
Referenced by Polygon::as_3d(), raylib::DrawLineStrip2Din3D(), system_manager::input_process_manager::planning::drop_held_furniture(), generation::helper::generate_entity_from_character(), make_customer(), system_manager::job_system::render_job_visual(), and Job::travel_to_position().
Variable Documentation
neigh_x
constexpr int vec::neigh_x[8] = {-1, -1, -1, 0, 0, 1, 1, 1} [static], [constexpr]
Referenced by forEachNeighbor().
neigh_y
constexpr int vec::neigh_y[8] = {-1, 0, 1, -1, 1, -1, 0, 1} [static], [constexpr]
Referenced by forEachNeighbor().