generation::helper Struct Reference
#include <level_info.h>
Public Member Functions
helper (const std::vector< std::string > &l)
void generate (std::function< void(Entity *)> add_to_map=nullptr)
Entity * generate_entity_from_character (char ch, vec2 location)
vec2 find_origin ()
char get_char (int i, int j)
void validate ()
Public Attributes
std::vector< std::string > lines
vec2 x = {0, 0}
vec2 z = {0, 0}
Constructor & Destructor Documentation
helper()
generation::helper::helper (const std::vector< std::string > & l) [inline]
Member Function Documentation
find_origin()
vec2 generation::helper::find_origin () [inline]
References lines, and TILESIZE.
Referenced by generate().
generate()
void generation::helper::generate (std::function< void(Entity *)> add_to_map = nullptr) [inline]
References EntityHelper::addEntity(), find_origin(), generate_entity_from_character(), get_char(), lines, and TILESIZE.
Referenced by GameMapInfo::generate_map(), and test::setup().
generate_entity_from_character()
Entity * generation::helper::generate_entity_from_character (char ch, vec2 location) [inline]
References generation::BAGBOX, generation::CUST_SPAWNER, generation::CUSTOMER, generation::EMPTY, Entity::get(), global_player, generation::GRABBERd, generation::GRABBERl, generation::GRABBERr, generation::GRABBERu, log_warn, entities::make_bagbox(), make_customer(), entities::make_customer_spawner(), make_entity(), entities::make_grabber(), entities::make_medicine_cabinet(), entities::make_pill_dispenser(), entities::make_register(), entities::make_sophie(), entities::make_table(), entities::make_wall(), generation::MED_CAB, DebugOptions::name, generation::PILL_DISP, generation::PLAYER, generation::REGISTER, generation::SOPHIE, generation::TABLE, vec::to3(), generation::WALL, generation::WALL2, x, and z.
Referenced by generate().
get_char()
char generation::helper::get_char (int i, int j) [inline]
References lines.
Referenced by generate().
validate()
void generation::helper::validate () [inline]
References Transform::as2(), astar::find_path(), EntityHelper::isWalkable(), log_info, and VALIDATE.
Referenced by GameMapInfo::generate_map().
Member Data Documentation
lines
std::vector<std::string> generation::helper::lines
Referenced by find_origin(), generate(), and get_char().
x
vec2 generation::helper::x = {0, 0}
Referenced by generate_entity_from_character(), and test::setup().
z
vec2 generation::helper::z = {0, 0}
Referenced by generate_entity_from_character(), and test::setup().
The documentation for this struct was generated from the following file:
src/level_info.h