ShaderLibrary Struct Reference
#include <shader_library.h>
Classes
struct ShaderLibraryImpl
Public Member Functions
raylib::Shader & get (const std::string &name)
const raylib::Shader & get (const std::string &name) const
void load (const char *filename, const char *name)
void unload_all ()
Private Attributes
ShaderLibrary::ShaderLibraryImpl impl
Member Function Documentation
get() [1/2]
raylib::Shader & ShaderLibrary::get (const std::string & name) [inline]
Referenced by Preload::load_shaders(), App::start_post_processing(), and Preload::~Preload().
get() [2/2]
const raylib::Shader & ShaderLibrary::get (const std::string & name) const [inline]
load()
void ShaderLibrary::load (const char * filename, const char * name) [inline]
unload_all()
void ShaderLibrary::unload_all () [inline]
Member Data Documentation
impl
ShaderLibrary::ShaderLibraryImpl ShaderLibrary::impl [private]
The documentation for this struct was generated from the following file:
src/engine/shader_library.h