network::Server Struct Reference
#include <server.h>
Static Public Member Functions
static std::thread start (int port)
static void queue_packet (ClientPacket &p)
static void stop ()
Private Types
typedef std::pair< internal::Client_t, std::string > ClientMessage
Private Member Functions
Server (int port)
void send_map_state ()
void send_player_rare_data ()
void run ()
void tick (float dt)
void process_announcement_packet (const internal::Client_t &, const ClientPacket &packet)
void process_player_control_packet (const internal::Client_t &incoming_client, const ClientPacket &packet)
void send_announcement (HSteamNetConnection conn, const std::string &msg, internal::InternalServerAnnouncement type)
void process_player_leave (int client_id)
void process_player_leave_packet (const internal::Client_t &incoming_client, const ClientPacket &)
void process_player_join_packet (const internal::Client_t &incoming_client, const ClientPacket &orig_packet)
void process_ping_message (const internal::Client_t &incoming_client, const ClientPacket &orig_packet)
void server_enqueue_message_string (const internal::Client_t &incoming_client, const std::string &msg)
void server_process_message_string (const ClientMessage &client_message)
void send_client_packet_to_client (HSteamNetConnection conn, ClientPacket packet)
void send_client_packet_to_all (ClientPacket packet, std::function< bool(internal::Client_t &)> exclude=nullptr)
Private Attributes
AtomicQueue< ClientMessage > incoming_message_queue
AtomicQueue< ClientPacket > packet_queue
std::shared_ptr< internal::Server > server_p
std::map< int, std::shared_ptr< Entity > > players
std::shared_ptr< Map > pharmacy_map
std::atomic< bool > running
std::thread::id thread_id
menu::State current_menu_state
game::State current_game_state
float next_map_tick_reset = 50
float next_map_tick = 0
float next_player_rare_tick_reset = 100
float next_player_rare_tick = 0
TriggerOnDt next_update_timer = TriggerOnDt(5.f)
Member Typedef Documentation
ClientMessage
typedef std::pair<internal::Client_t, std::string> network::Server::ClientMessage [private]
Constructor & Destructor Documentation
Server()
network::Server::Server (int port) [inline], [explicit], [private]
References GLOBALS, pharmacy_map, players, process_player_leave(), send_announcement(), server_enqueue_message_string(), server_p, and GlobalValueRegister::set().
Member Function Documentation
process_announcement_packet()
void network::Server::process_announcement_packet (const internal::Client_t & , const ClientPacket & packet) [inline], [private]
References network::ClientPacket::msg, and send_client_packet_to_all().
Referenced by server_process_message_string().
process_ping_message()
void network::Server::process_ping_message (const internal::Client_t & incoming_client, const ClientPacket & orig_packet) [inline], [private]
References network::internal::Client_t::client_id, now::current_ms(), network::ClientPacket::msg, network::ClientPacket::Ping, network::ClientPacket::PingInfo::ping, send_client_packet_to_all(), and network::SERVER_CLIENT_ID.
Referenced by server_process_message_string().
process_player_control_packet()
void network::Server::process_player_control_packet (const internal::Client_t & incoming_client, const ClientPacket & packet) [inline], [private]
References network::internal::Client_t::client_id, network::ClientPacket::client_id, network::ClientPacket::PlayerControlInfo::inputs, network::ClientPacket::msg, network::ClientPacket::PlayerLocation, players, and send_client_packet_to_all().
Referenced by server_process_message_string().
process_player_join_packet()
void network::Server::process_player_join_packet (const internal::Client_t & incoming_client, const ClientPacket & orig_packet) [inline], [private]
References network::internal::Client_t::client_id, network::ClientPacket::client_id, HASHED_VERSION, network::ClientPacket::PlayerJoinInfo::hashed_version, log_warn, make_player(), network::ClientPacket::msg, network::ClientPacket::PlayerJoin, players, send_client_packet_to_all(), network::SERVER_CLIENT_ID, server_p, and network::ClientPacket::PlayerJoinInfo::username.
Referenced by server_process_message_string().
process_player_leave()
void network::Server::process_player_leave (int client_id) [inline], [private]
References network::internal::Client_t::client_id, log_info, log_warn, network::ClientPacket::PlayerLeave, players, send_client_packet_to_all(), network::SERVER_CLIENT_ID, and server_p.
Referenced by process_player_leave_packet(), and Server().
process_player_leave_packet()
void network::Server::process_player_leave_packet (const internal::Client_t & incoming_client, const ClientPacket &) [inline], [private]
References network::internal::Client_t::client_id, log_info, and process_player_leave().
Referenced by server_process_message_string().
queue_packet()
static void network::Server::queue_packet (ClientPacket & p) [inline], [static]
References network::g_server.
Referenced by network::Info::send_current_menu_state().
run()
void network::Server::run () [inline], [private]
References GLOBALS, running, GlobalValueRegister::set(), start(), thread_id, tick(), TRACY_ZONE_NAMED, and TRACY_ZONE_SCOPED.
Referenced by start().
send_announcement()
void network::Server::send_announcement (HSteamNetConnection conn, const std::string & msg, internal::InternalServerAnnouncement type) [inline], [private]
References network::ClientPacket::Announcement, network::internal::Error, network::internal::Info, send_client_packet_to_client(), network::SERVER_CLIENT_ID, and network::internal::Warn.
Referenced by Server().
send_client_packet_to_all()
void network::Server::send_client_packet_to_all (ClientPacket packet, std::function< bool(internal::Client_t &)> exclude = nullptr) [inline], [private]
References network::serialize_to_buffer(), and server_p.
Referenced by process_announcement_packet(), process_ping_message(), process_player_control_packet(), process_player_join_packet(), process_player_leave(), send_map_state(), send_player_rare_data(), server_process_message_string(), and tick().
send_client_packet_to_client()
void network::Server::send_client_packet_to_client (HSteamNetConnection conn, ClientPacket packet) [inline], [private]
References network::serialize_to_buffer(), and server_p.
Referenced by send_announcement().
send_map_state()
void network::Server::send_map_state () [inline], [private]
References network::ClientPacket::Map, pharmacy_map, send_client_packet_to_all(), and network::SERVER_CLIENT_ID.
Referenced by tick().
send_player_rare_data()
void network::Server::send_player_rare_data () [inline], [private]
References network::ClientPacket::PlayerRare, players, and send_client_packet_to_all().
Referenced by tick().
server_enqueue_message_string()
void network::Server::server_enqueue_message_string (const internal::Client_t & incoming_client, const std::string & msg) [inline], [private]
References incoming_message_queue, and AtomicQueue< T >::push_back().
Referenced by Server().
server_process_message_string()
void network::Server::server_process_message_string (const ClientMessage & client_message) [inline], [private]
References network::ClientPacket::Announcement, network::internal::Client_t::client_id, network::deserialize_to_packet(), log_warn, network::ClientPacket::msg_type, network::ClientPacket::Ping, network::ClientPacket::PlayerControl, network::ClientPacket::PlayerJoin, network::ClientPacket::PlayerLeave, process_announcement_packet(), process_ping_message(), process_player_control_packet(), process_player_join_packet(), process_player_leave_packet(), send_client_packet_to_all(), and TRACY_ZONE_SCOPED.
Referenced by tick().
start()
static std::thread network::Server::start (int port) [inline], [static]
References network::g_server, and run().
Referenced by run(), and network::Info::set_role().
stop()
static void network::Server::stop () [inline], [static]
References network::g_server.
Referenced by network::Info::cleanup_server().
tick()
void network::Server::tick (float dt) [inline], [private]
References current_game_state, current_menu_state, AtomicQueue< T >::empty(), AtomicQueue< T >::front(), network::ClientPacket::GameState, network::ClientPacket::GameStateInfo::host_game_state, network::ClientPacket::GameStateInfo::host_menu_state, incoming_message_queue, log_trace, next_map_tick, next_map_tick_reset, next_player_rare_tick, next_player_rare_tick_reset, next_update_timer, packet_queue, pharmacy_map, players, AtomicQueue< T >::pop_front(), MenuState::s_is_game(), send_client_packet_to_all(), send_map_state(), send_player_rare_data(), server_p, server_process_message_string(), AtomicQueue< T >::size(), TriggerOnDt::test(), TRACY_FRAME_MARK, TRACY_ZONE, TRACY_ZONE_NAMED, and TRACY_ZONE_SCOPED.
Referenced by run().
Member Data Documentation
current_game_state
game::State network::Server::current_game_state [private]
Referenced by tick().
current_menu_state
menu::State network::Server::current_menu_state [private]
Referenced by tick().
incoming_message_queue
AtomicQueue<ClientMessage> network::Server::incoming_message_queue [private]
Referenced by server_enqueue_message_string(), and tick().
next_map_tick
float network::Server::next_map_tick = 0 [private]
Referenced by tick().
next_map_tick_reset
float network::Server::next_map_tick_reset = 50 [private]
Referenced by tick().
next_player_rare_tick
float network::Server::next_player_rare_tick = 0 [private]
Referenced by tick().
next_player_rare_tick_reset
float network::Server::next_player_rare_tick_reset = 100 [private]
Referenced by tick().
next_update_timer
TriggerOnDt network::Server::next_update_timer = TriggerOnDt(5.f) [private]
Referenced by tick().
packet_queue
AtomicQueue<ClientPacket> network::Server::packet_queue [private]
Referenced by tick().
pharmacy_map
std::shared_ptr<Map> network::Server::pharmacy_map [private]
Referenced by send_map_state(), Server(), and tick().
players
std::map<int, std::shared_ptr<Entity> > network::Server::players [private]
Referenced by process_player_control_packet(), process_player_join_packet(), process_player_leave(), send_player_rare_data(), Server(), and tick().
running
std::atomic<bool> network::Server::running [private]
Referenced by run().
server_p
std::shared_ptr<internal::Server> network::Server::server_p [private]
Referenced by process_player_join_packet(), process_player_leave(), send_client_packet_to_all(), send_client_packet_to_client(), Server(), and tick().
thread_id
std::thread::id network::Server::thread_id [private]
Referenced by run().
The documentation for this struct was generated from the following file:
src/network/server.h