ui::StateManager Struct Reference
#include <ui_state.h>
Public Member Functions
void addState (const uuid id, const std::shared_ptr< UIState > &state)
template<typename T >
std::shared_ptr< T > getAndCreateIfNone (const uuid id)
std::shared_ptr< UIState > get (const uuid id)
template<typename T >
std::shared_ptr< T > get_as (const uuid id)
Public Attributes
std::map< uuid, std::shared_ptr< UIState > > states
Member Function Documentation
addState()
void ui::StateManager::addState (const uuid id, const std::shared_ptr< UIState > & state) [inline]
References states.
Referenced by getAndCreateIfNone().
get()
std::shared_ptr< UIState > ui::StateManager::get (const uuid id) [inline]
References states.
get_as()
template<typename T >
std::shared_ptr< T > ui::StateManager::get_as (const uuid id) [inline]
References states.
Referenced by ui::UIContext::get_widget_state().
getAndCreateIfNone()
template<typename T >
std::shared_ptr< T > ui::StateManager::getAndCreateIfNone (const uuid id) [inline]
References addState(), and states.
Referenced by ui::UIContext::widget_init().
Member Data Documentation
states
std::map<uuid, std::shared_ptr<UIState> > ui::StateManager::states
Referenced by addState(), get(), get_as(), and getAndCreateIfNone().
The documentation for this struct was generated from the following file:
src/engine/ui_state.h