ToastLayer Struct Reference
#include <toastlayer.h>
Public Member Functions
ToastLayer ()
virtual void onEvent (Event &) override
virtual void onUpdate (float dt) override
virtual void onDraw (float) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
virtual void onEvent (Event &)=0
const std::string & getname () const
Public Member Functions inherited from FontSizeCache
virtual void init ()
void set_font (raylib::Font f)
float get_font_size_impl (const std::string &content, float width, float height, float spacing) const
float get_font_size (const std::string &content, float width, float height, float spacing)
Public Attributes
const float toastPctHeight = 0.05f
const float toastPctWidth = 0.25f
const float toastPctBottomPadding = 0.01f
Public Attributes inherited from Layer
int id
std::string name
Public Attributes inherited from FontSizeCache
raylib::Font font
std::unordered_map< size_t, float > _font_size_memo
Constructor & Destructor Documentation
ToastLayer()
ToastLayer::ToastLayer () [inline]
References FontSizeCache::init().
Member Function Documentation
onDraw()
virtual void ToastLayer::onDraw (float) [inline], [override], [virtual]
Implements Layer.
References ui::theme::Accent, ui::DEFAULT_THEME, ui::theme::Error, ui::theme::Font, ui::UITheme::from_usage(), FontSizeCache::get_font_size(), ui::theme::Primary, ui::theme::Secondary, toastPctBottomPadding, toastPctHeight, toastPctWidth, TOASTS, WIN_HF(), and WIN_WF().
onEvent()
virtual void ToastLayer::onEvent (Event &) [inline], [override], [virtual]
Implements Layer.
onUpdate()
virtual void ToastLayer::onUpdate (float dt) [inline], [override], [virtual]
Implements Layer.
References toasts::update().
Member Data Documentation
toastPctBottomPadding
const float ToastLayer::toastPctBottomPadding = 0.01f
Referenced by onDraw().
toastPctHeight
const float ToastLayer::toastPctHeight = 0.05f
Referenced by onDraw().
toastPctWidth
const float ToastLayer::toastPctWidth = 0.25f
Referenced by onDraw().
The documentation for this struct was generated from the following file:
src/toastlayer.h