GameMapInfo Struct Reference
#include <level_info.h>
Public Member Functions
void update_seed (const std::string &s)
virtual void onUpdate (float dt) override
virtual void onDrawUI (float) override
Public Member Functions inherited from LevelInfo
virtual void onUpdate (float dt)
virtual void onDraw (float dt) const
virtual void onDrawUI (float)
void grab_things ()
void ensure_generated_map (const std::string &new_seed)
virtual void generate_map ()=0
Public Attributes
size_t hashed_seed
std::mt19937 generator
std::uniform_int_distribution dist
std::optional< Round > active_round
Public Attributes inherited from LevelInfo
bool was_generated = false
SystemManager system_manager
Entities entities
Entities::size_type num_entities
Items items
Items::size_type num_items
std::string seed
Private Member Functions
auto get_rand_walkable ()
virtual void generate_map () override
template<typename S >
void serialize (S &s)
Member Function Documentation
generate_map()
virtual void GameMapInfo::generate_map () [inline], [override], [private], [virtual]
Implements LevelInfo.
References EntityHelper::addEntity(), ItemHelper::addItem(), generate_and_insert_walls(), get_rand_walkable(), EntityHelper::invalidatePathCache(), LevelInfo::seed, server_entities_DO_NOT_USE, server_items_DO_NOT_USE, and TILESIZE.
get_rand_walkable()
auto GameMapInfo::get_rand_walkable () [inline], [private]
References dist, generator, EntityHelper::isWalkable(), and TILESIZE.
Referenced by generate_map().
onDrawUI()
virtual void GameMapInfo::onDrawUI (float) [inline], [override], [virtual]
Reimplemented from LevelInfo.
References active_round.
Referenced by Map::onDrawUI().
onUpdate()
virtual void GameMapInfo::onUpdate (float dt) [inline], [override], [virtual]
Reimplemented from LevelInfo.
References active_round, and LevelInfo::onUpdate().
Referenced by Map::onUpdate().
serialize()
template<typename S >
void GameMapInfo::serialize (S & s) [inline], [private]
References active_round, and hashed_seed.
update_seed()
void GameMapInfo::update_seed (const std::string & s) [inline]
References active_round, dist, generator, hashed_seed, hashString(), make_engine(), MAX_MAP_SIZE, and LevelInfo::seed.
Referenced by Map::update_seed().
Member Data Documentation
active_round
std::optional<Round> GameMapInfo::active_round
Referenced by onDrawUI(), onUpdate(), serialize(), and update_seed().
dist
std::uniform_int_distribution GameMapInfo::dist
Referenced by get_rand_walkable(), and update_seed().
generator
std::mt19937 GameMapInfo::generator
Referenced by get_rand_walkable(), and update_seed().
hashed_seed
size_t GameMapInfo::hashed_seed
Referenced by serialize(), and update_seed().
The documentation for this struct was generated from the following file:
src/level_info.h