raylib Namespace Reference
Classes
struct WaveTextConfig
Typedefs
typedef struct raylib::WaveTextConfig WaveTextConfig
Functions
static void DrawPctFilledCircle (const vec2 position, float radius, Color backgroundColor, Color foregroundColor, float pct_filled, float startAngle=180)
static void DrawLineStrip2Din3D (const std::vector< vec2 > &points, Color color)
static void DrawRect2Din3D (Vector3 position, float width, float height, Color color=RED)
static void DrawCubeCustom (Vector3 position, float width, float height, float length, float front_facing_angle, Color face_color, Color base_color)
static void DrawFloatingText (const vec3 &position, Font font, const char *text, Color color=BLACK)
static void DrawTextCodepoint3D (Font font, int codepoint, vec3 position, float fontSize, bool backface, Color tint)
static void DrawText3D (Font font, const char *text, vec3 position, float fontSize, float fontSpacing, float lineSpacing, bool backface, Color tint)
static vec3 MeasureText3D (Font font, const char *text, float fontSize, float fontSpacing, float lineSpacing)
static void DrawTextWave3D (Font font, const char *text, vec3 position, float fontSize, float fontSpacing, float lineSpacing, bool backface, WaveTextConfig *config, float time, Color tint)
static vec3 MeasureTextWave3D (Font font, const char *text, float fontSize, float fontSpacing, float lineSpacing)
Variables
const bool SHOW_LETTER_BOUNDRY = false
const bool SHOW_TEXT_BOUNDRY = false
Typedef Documentation
WaveTextConfig
typedef struct raylib::WaveTextConfig raylib::WaveTextConfig
Function Documentation
DrawCubeCustom()
static void raylib::DrawCubeCustom (Vector3 position, float width, float height, float length, float front_facing_angle, Color face_color, Color base_color) [static]
DrawFloatingText()
static void raylib::DrawFloatingText (const vec3 & position, Font font, const char * text, Color color = BLACK) [static]
References DrawText3D(), and TILESIZE.
Referenced by Entity::render_floating_name().
DrawLineStrip2Din3D()
static void raylib::DrawLineStrip2Din3D (const std::vector< vec2 > & points, Color color) [static]
References TILESIZE, and vec::to3().
DrawPctFilledCircle()
static void raylib::DrawPctFilledCircle (const vec2 position, float radius, Color backgroundColor, Color foregroundColor, float pct_filled, float startAngle = 180) [static]
Referenced by Round::onDraw().
DrawRect2Din3D()
static void raylib::DrawRect2Din3D (Vector3 position, float width, float height, Color color = RED) [static]
References TILESIZE.
DrawText3D()
static void raylib::DrawText3D (Font font, const char * text, vec3 position, float fontSize, float fontSpacing, float lineSpacing, bool backface, Color tint) [static]
References DrawText3D(), and DrawTextCodepoint3D().
Referenced by DrawFloatingText(), and DrawText3D().
DrawTextCodepoint3D()
static void raylib::DrawTextCodepoint3D (Font font, int codepoint, vec3 position, float fontSize, bool backface, Color tint) [static]
Referenced by DrawText3D(), and DrawTextWave3D().
DrawTextWave3D()
static void raylib::DrawTextWave3D (Font font, const char * text, vec3 position, float fontSize, float fontSpacing, float lineSpacing, bool backface, WaveTextConfig * config, float time, Color tint) [static]
References DrawTextCodepoint3D(), DrawTextWave3D(), raylib::WaveTextConfig::waveOffset, raylib::WaveTextConfig::waveRange, and raylib::WaveTextConfig::waveSpeed.
Referenced by DrawTextWave3D().
MeasureText3D()
static vec3 raylib::MeasureText3D (Font font, const char * text, float fontSize, float fontSpacing, float lineSpacing) [static]
References MeasureText3D().
Referenced by MeasureText3D().
MeasureTextWave3D()
static vec3 raylib::MeasureTextWave3D (Font font, const char * text, float fontSize, float fontSpacing, float lineSpacing) [static]
References MeasureTextWave3D().
Referenced by MeasureTextWave3D().
Variable Documentation
SHOW_LETTER_BOUNDRY
const bool raylib::SHOW_LETTER_BOUNDRY = false
SHOW_TEXT_BOUNDRY
const bool raylib::SHOW_TEXT_BOUNDRY = false