ItemContainer< I > Struct Template Reference
#include <item_container.h>
Public Member Functions
ItemContainer ()
ItemContainer (vec2 pos)
virtual bool can_place_item_into (std::shared_ptr< Item > item=nullptr) override
virtual void in_round_update (float dt) override
Public Member Functions inherited from Furniture
Furniture (vec3 pos, Color)
Furniture (vec2 pos, Color)
virtual bool add_to_navmesh () override
virtual bool can_rotate () const
virtual bool can_be_picked_up ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr) override
virtual bool has_held_item () const
Public Member Functions inherited from Entity
template<typename T >
bool has () const
template<typename T , typename... TArgs>
T & addComponent (TArgs &&... args)
template<typename T >
T & get () const
Entity (vec3 p)
Entity (vec2 p)
virtual ~Entity ()
virtual void announce (std::string text)
virtual bool collides (BoundingBox b) const
virtual BoundingBox raw_bounds () const
virtual BoundingBox bounds () const
vec3 snap_position () const
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void update (float dt) final
Private Member Functions
template<typename S >
void serialize (S &s)
Additional Inherited Members
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, Transform::Transform::FrontFaceDirection direction)
static Entity * create_entity (vec3 pos, Color face_color, Color base_color)
static Entity * create_person (vec3 pos, Color face_color, Color base_color)
static Entity * create_aiperson (vec3 pos, Color face_color, Color base_color)
static Entity * create_customer (vec2 pos, Color base_color)
Public Attributes inherited from Entity
int id
ComponentBitSet componentSet
ComponentArray componentArray
bool cleanup = false
bool is_held = false
Protected Member Functions inherited from Furniture
Furniture ()
void add_static_components ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void in_round_update (float)
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Constructor & Destructor Documentation
ItemContainer() [1/2]
template<typename I >
ItemContainer< I >::ItemContainer () [inline]
ItemContainer() [2/2]
template<typename I >
ItemContainer< I >::ItemContainer (vec2 pos) [inline], [explicit]
Member Function Documentation
can_place_item_into()
template<typename I >
virtual bool ItemContainer< I >::can_place_item_into (std::shared_ptr< Item > item = nullptr) [inline], [override], [virtual]
Reimplemented from Furniture.
in_round_update()
template<typename I >
virtual void ItemContainer< I >::in_round_update (float dt) [inline], [override], [virtual]
Reimplemented from Entity.
References ItemHelper::addItem(), Entity::in_round_update(), CanHoldItem::is_holding_item(), and CanHoldItem::item().
serialize()
template<typename I >
template<typename S >
void ItemContainer< I >::serialize (S & s) [inline], [private]
The documentation for this struct was generated from the following file:
src/furniture/item_container.h