Ailment Struct Reference
#include <ailment.h>
Classes
struct Config
Public Types
enum class Type { None
, Test
, Hooked
, Insomnia
 }
enum class Speed { Slow
, Okay
, Default
, Fast
 }
enum class Stagger { None
, Little
, Some
, Lots
 }
Public Member Functions
float speed_multiplier ()
float stagger ()
float overall ()
Ailment ()
Ailment (const Config &opt)
~Ailment ()
std::string icon_name () const
Static Public Member Functions
static Ailment * make_max_ailment ()
static Ailment * make_insomnia ()
static Ailment * make_hooked ()
Public Attributes
struct Ailment::Config config
std::array< Symptom, 10 > symptoms
std::array< std::shared_ptr< Ailment >, 10 > comorbids
int num_comorbids = 0
Protected Member Functions
float overall_mult ()
Private Member Functions
float clamp (float val, float mn=0.1f, float mx=1.f)
template<typename S >
void serialize (S &s)
Private Attributes
int stagger_dir = 0
Member Enumeration Documentation
Speed
enum class Ailment::Speed [strong]
Enumerator
Slow
Okay
Default
Fast
Stagger
enum class Ailment::Stagger [strong]
Enumerator
None
Little
Some
Lots
Type
enum class Ailment::Type [strong]
Enumerator
None
Test
Hooked
Insomnia
Constructor & Destructor Documentation
Ailment() [1/2]
Ailment::Ailment () [inline]
Referenced by make_hooked(), make_insomnia(), and make_max_ailment().
Ailment() [2/2]
Ailment::Ailment (const Config & opt) [inline], [explicit]
 Ailment()
Ailment::~Ailment () [inline]
Member Function Documentation
clamp()
float Ailment::clamp (float val, float mn = 0.1f, float mx = 1.f) [inline], [private]
Referenced by overall(), speed_multiplier(), and stagger().
icon_name()
std::string Ailment::icon_name () const [inline]
References config, Hooked, Insomnia, None, Test, and Ailment::Config::type.
make_hooked()
static Ailment * Ailment::make_hooked () [inline], [static]
References Ailment(), Default, Hooked, Lots, and make_insomnia().
make_insomnia()
static Ailment * Ailment::make_insomnia () [inline], [static]
References Ailment(), Insomnia, None, and Okay.
Referenced by make_customer(), and make_hooked().
make_max_ailment()
static Ailment * Ailment::make_max_ailment () [inline], [static]
References Ailment(), Lots, Slow, and Test.
overall()
float Ailment::overall () [inline]
References clamp(), and overall_mult().
Referenced by speed_multiplier(), and stagger().
overall_mult()
float Ailment::overall_mult () [inline], [protected]
Referenced by overall().
serialize()
template<typename S >
void Ailment::serialize (S & s) [inline], [private]
References comorbids, config, num_comorbids, and symptoms.
speed_multiplier()
float Ailment::speed_multiplier () [inline]
References clamp(), comorbids, config, Default, Fast, num_comorbids, Okay, overall(), Slow, and Ailment::Config::speed.
stagger()
float Ailment::stagger () [inline]
References clamp(), comorbids, config, Little, Lots, None, num_comorbids, overall(), Some, Ailment::Config::stagger, and stagger_dir.
Member Data Documentation
comorbids
std::array<std::shared_ptr<Ailment>, 10> Ailment::comorbids
Referenced by serialize(), speed_multiplier(), and stagger().
config
struct Ailment::Config Ailment::config
Referenced by icon_name(), serialize(), speed_multiplier(), and stagger().
num_comorbids
int Ailment::num_comorbids = 0
Referenced by serialize(), speed_multiplier(), and stagger().
stagger_dir
int Ailment::stagger_dir = 0 [private]
Referenced by stagger().
symptoms
std::array<Symptom, 10> Ailment::symptoms
Referenced by serialize().
The documentation for this struct was generated from the following file:
src/dataclass/ailment.h