StateManager2< T > Struct Template Reference
#include <statemanager.h>
Public Member Functions
T read () const
T previous () const
T go_back ()
void clear_history ()
bool is (T s) const
bool is_not (T s) const
const std::string_view tostring () const
void register_on_change (const std::function< void(T, T)> &nfunc)
void set (T ns)
virtual T default_value () const =0
void reset ()
virtual ~StateManager2 ()
Private Member Functions
void call_on_change (T ns, T os)
Private Attributes
std::stack< T > prev
std::vector< std::function< void(T, T)> > on_change_action_list
T state
Constructor & Destructor Documentation
 StateManager2()
template<typename T >
virtual StateManager2< T >::~StateManager2 () [inline], [virtual]
Member Function Documentation
call_on_change()
template<typename T >
void StateManager2< T >::call_on_change (T ns, T os) [inline], [private]
References StateManager2< T >::on_change_action_list.
Referenced by StateManager2< T >::set().
clear_history()
template<typename T >
void StateManager2< T >::clear_history () [inline]
References StateManager2< T >::prev.
Referenced by StateManager2< T >::reset().
default_value()
template<typename T >
virtual T StateManager2< T >::default_value () const [pure virtual]
Implemented in MenuState, and GameState.
Referenced by StateManager2< T >::reset().
go_back()
template<typename T >
T StateManager2< T >::go_back () [inline]
References log_info, StateManager2< T >::prev, and StateManager2< T >::state.
is()
template<typename T >
bool StateManager2< T >::is (T s) const [inline]
References StateManager2< T >::state.
is_not()
template<typename T >
bool StateManager2< T >::is_not (T s) const [inline]
References StateManager2< T >::state.
previous()
template<typename T >
T StateManager2< T >::previous () const [inline]
References StateManager2< T >::prev.
read()
template<typename T >
T StateManager2< T >::read () const [inline]
References StateManager2< T >::state.
register_on_change()
template<typename T >
void StateManager2< T >::register_on_change (const std::function< void(T, T)> & nfunc) [inline]
References StateManager2< T >::on_change_action_list.
reset()
template<typename T >
void StateManager2< T >::reset () [inline]
References StateManager2< T >::clear_history(), StateManager2< T >::default_value(), and StateManager2< T >::set().
set()
template<typename T >
void StateManager2< T >::set (T ns) [inline]
References StateManager2< T >::call_on_change(), log_info, log_warn, StateManager2< T >::prev, and StateManager2< T >::state.
Referenced by StateManager2< T >::reset().
tostring()
template<typename T >
const std::string_view StateManager2< T >::tostring () const [inline]
References StateManager2< T >::state.
Member Data Documentation
on_change_action_list
template<typename T >
std::vector<std::function<void(T, T)> > StateManager2< T >::on_change_action_list [private]
Referenced by StateManager2< T >::call_on_change(), and StateManager2< T >::register_on_change().
prev
template<typename T >
std::stack<T> StateManager2< T >::prev [private]
Referenced by StateManager2< T >::clear_history(), StateManager2< T >::go_back(), StateManager2< T >::previous(), and StateManager2< T >::set().
state
template<typename T >
T StateManager2< T >::state [private]
Referenced by StateManager2< T >::go_back(), StateManager2< T >::is(), StateManager2< T >::is_not(), StateManager2< T >::read(), StateManager2< T >::set(), and StateManager2< T >::tostring().
The documentation for this struct was generated from the following file:
src/engine/statemanager.h