src/game.cpp File Reference
#include `engine/tracy.h`
#include `external_include.h`
#include <argh.h>
#include `globals.h`
#include `engine.h`
#include `layers/aboutlayer.h`
#include `layers/fpslayer.h`
#include `layers/gamedebuglayer.h`
#include `layers/gamelayer.h`
#include `layers/menulayer.h`
#include `layers/menustatelayer.h`
#include `layers/networklayer.h`
#include `layers/pauselayer.h`
#include `layers/settingslayer.h`
#include `layers/streamersafelayer.h`
#include `layers/toastlayer.h`
#include `layers/versionlayer.h`
#include `./tests/all_tests.h`
Macros
#define BUILD_WITHOUT_STEAM
#define ENABLE_TRACING 1
#define ENABLE_DEV_FLAGS 1
Functions
void startup ()
int setup_multiplayer_test (bool is_host=false)
void process_dev_flags (char *argv[])
int main (int argc, char *argv[])
Macro Definition Documentation
BUILD_WITHOUT_STEAM
#define BUILD_WITHOUT_STEAM
ENABLE_DEV_FLAGS
#define ENABLE_DEV_FLAGS 1
ENABLE_TRACING
#define ENABLE_TRACING 1
Function Documentation
main()
int main (int argc, char * argv[])
References defer, process_dev_flags(), register_all_components(), tests::run_all(), setup_multiplayer_test(), and startup().
process_dev_flags()
void process_dev_flags (char * argv[])
References ENABLE_MODELS, and ENABLE_SOUND.
Referenced by main().
setup_multiplayer_test()
int setup_multiplayer_test (bool is_host = false)
References network::mp_test::enabled, network::mp_test::is_host, and menu::Network.
Referenced by main().
startup()
void startup ()
References GAME_FOLDER, SETTINGS_FILE_NAME, WIN_H(), and WIN_W().
Referenced by main().