Library< T > Struct Template Reference
#include <library.h>
Public Types
enum struct Error { DUPLICATE_NAME
, NO_MATCH
 }
using Storage = std::map< std::string, T >
typedef Storage::iterator iterator
typedef Storage::const_iterator const_iterator
Public Member Functions
auto size ()
auto begin ()
auto end ()
auto begin () const
auto end () const
auto rbegin () const
auto rend () const
auto rbegin ()
auto rend ()
auto empty () const
const tl::expected< std::string, Error > add (const char *name, const T &item)
T & get (const std::string &name)
const T & get (const std::string &name) const
bool contains (const std::string &name) const
virtual void load (const char *filename, const char *name)
virtual T convert_filename_to_object (const char *filename)=0
void unload_all ()
virtual void unload (T)=0
tl::expected< T, Error > get_random_match (const std::string &key) const
auto lookup (const std::string &key) const -> std::pair< const_iterator, const_iterator >
Public Attributes
Storage storage
Member Typedef Documentation
const_iterator
template<typename T >
typedef Storage::const_iterator Library< T >::const_iterator
iterator
template<typename T >
typedef Storage::iterator Library< T >::iterator
Storage
template<typename T >
using Library< T >::Storage = std::map<std::string, T>
Member Enumeration Documentation
Error
template<typename T >
enum struct Library::Error [strong]
Enumerator
DUPLICATE_NAME
NO_MATCH
Member Function Documentation
add()
template<typename T >
const tl::expected< std::string, Error > Library< T >::add (const char * name, const T & item) [inline]
References Library< T >::DUPLICATE_NAME, log_info, and Library< T >::storage.
Referenced by Library< T >::load().
begin() [1/2]
template<typename T >
auto Library< T >::begin () [inline]
References Library< T >::storage.
Referenced by Library< T >::get_random_match().
begin() [2/2]
template<typename T >
auto Library< T >::begin () const [inline]
References Library< T >::storage.
contains()
template<typename T >
bool Library< T >::contains (const std::string & name) const [inline]
References Library< T >::storage.
Referenced by Library< T >::get().
convert_filename_to_object()
template<typename T >
virtual T Library< T >::convert_filename_to_object (const char * filename) [pure virtual]
Implemented in ModelLibrary::ModelLibraryImpl, MusicLibrary::MusicLibraryImpl, ShaderLibrary::ShaderLibraryImpl, SoundLibrary::SoundLibraryImpl, and TextureLibrary::TextureLibraryImpl.
Referenced by Library< T >::load().
empty()
template<typename T >
auto Library< T >::empty () const [inline]
References Library< T >::storage.
end() [1/2]
template<typename T >
auto Library< T >::end () [inline]
References Library< T >::storage.
end() [2/2]
template<typename T >
auto Library< T >::end () const [inline]
References Library< T >::storage.
get() [1/2]
template<typename T >
T & Library< T >::get (const std::string & name) [inline]
References Library< T >::contains(), log_warn, and Library< T >::storage.
get() [2/2]
template<typename T >
const T & Library< T >::get (const std::string & name) const [inline]
References Library< T >::contains(), log_warn, and Library< T >::storage.
get_random_match()
template<typename T >
tl::expected< T, Error > Library< T >::get_random_match (const std::string & key) const [inline]
References Library< T >::begin(), log_warn, Library< T >::lookup(), Library< T >::NO_MATCH, and randIn().
load()
template<typename T >
virtual void Library< T >::load (const char * filename, const char * name) [inline], [virtual]
References Library< T >::add(), Library< T >::convert_filename_to_object(), and log_trace.
lookup()
template<typename T >
auto Library< T >::lookup (const std::string & key) const -> std::pair<const_iterator, const_iterator> [inline]
References Library< T >::storage.
Referenced by Library< T >::get_random_match().
rbegin() [1/2]
template<typename T >
auto Library< T >::rbegin () [inline]
References Library< T >::storage.
rbegin() [2/2]
template<typename T >
auto Library< T >::rbegin () const [inline]
References Library< T >::storage.
rend() [1/2]
template<typename T >
auto Library< T >::rend () [inline]
References Library< T >::storage.
rend() [2/2]
template<typename T >
auto Library< T >::rend () const [inline]
References Library< T >::storage.
size()
template<typename T >
auto Library< T >::size () [inline]
References Library< T >::storage.
unload()
template<typename T >
virtual void Library< T >::unload (T) [pure virtual]
Implemented in ModelLibrary::ModelLibraryImpl, MusicLibrary::MusicLibraryImpl, ShaderLibrary::ShaderLibraryImpl, SoundLibrary::SoundLibraryImpl, and TextureLibrary::TextureLibraryImpl.
Referenced by Library< T >::unload_all().
unload_all()
template<typename T >
void Library< T >::unload_all () [inline]
References log_info, Library< T >::storage, and Library< T >::unload().
Member Data Documentation
storage
template<typename T >
Storage Library< T >::storage
Referenced by Library< T >::add(), Library< T >::begin(), Library< T >::contains(), Library< T >::empty(), Library< T >::end(), Library< T >::get(), Library< T >::lookup(), Library< T >::rbegin(), Library< T >::rend(), Library< T >::size(), and Library< T >::unload_all().
The documentation for this struct was generated from the following file:
src/engine/library.h