system_manager::input_process_manager::inround Namespace Reference
Functions
void work_furniture (const std::shared_ptr< Entity > player, float frame_dt)
void handle_drop (const std::shared_ptr< Entity > &player)
void handle_grab (const std::shared_ptr< Entity > &player)
void handle_grab_or_drop (const std::shared_ptr< Entity > &player)
Function Documentation
handle_drop()
void system_manager::input_process_manager::inround::handle_drop (const std::shared_ptr< Entity > & player) [inline]
References CanHoldItem::empty(), Item::FURNITURE, EntityHelper::getClosestMatchingFurniture(), IsItemContainer< I >::is_matching_item(), CanHoldItem::item(), CanHighlightOthers::reach(), and Transform::snap_position().
Referenced by handle_grab_or_drop().
handle_grab()
void system_manager::input_process_manager::inround::handle_grab (const std::shared_ptr< Entity > & player) [inline]
References EntityHelper::getClosestMatchingFurniture(), CanHoldItem::item(), Item::PLAYER, CanHighlightOthers::reach(), and TILESIZE.
Referenced by handle_grab_or_drop().
handle_grab_or_drop()
void system_manager::input_process_manager::inround::handle_grab_or_drop (const std::shared_ptr< Entity > & player) [inline]
References handle_drop(), and handle_grab().
Referenced by system_manager::input_process_manager::process_input().
work_furniture()
void system_manager::input_process_manager::inround::work_furniture (const std::shared_ptr< Entity > player, float frame_dt) [inline]
References HasWork::do_work, EntityHelper::getClosestMatchingFurniture(), game::Planning, and CanHighlightOthers::reach().
Referenced by system_manager::input_process_manager::process_input().