Item Struct Reference
#include <item.h>
Public Types
enum HeldBy {
NONE
, ITEM
, PLAYER
, FURNITURE
,
CUSTOMER
 }
Public Member Functions
Item (vec3 p, Color c)
Item (vec2 p, Color c)
virtual ~Item ()
vec3 snap_position () const
virtual bool is_collidable ()
virtual vec3 model_scale () const
virtual void render (bool render_held_item=true) const
virtual void update_position (const vec3 &p)
virtual BoundingBox bounds () const
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual bool collides (BoundingBox b) const
virtual std::optional< raylib::Model > model () const
virtual bool eat (std::shared_ptr< Item > item)
virtual bool can_eat (std::shared_ptr< Item > item)
virtual bool has_holding_ability () const
virtual bool empty () const
Public Attributes
int id
float item_size = TILESIZE / 2
Color color
vec3 raw_position
vec3 position
bool cleanup = false
HeldBy held_by = NONE
std::shared_ptr< Item > held_item
Protected Member Functions
Item ()
Private Member Functions
template<typename S >
void serialize (S &s)
Member Enumeration Documentation
HeldBy
enum Item::HeldBy
Enumerator
NONE
ITEM
PLAYER
FURNITURE
CUSTOMER
Constructor & Destructor Documentation
Item() [1/3]
Item::Item () [inline], [protected]
Item() [2/3]
Item::Item (vec3 p, Color c) [inline]
References snap_position().
Item() [3/3]
Item::Item (vec2 p, Color c) [inline]
 Item()
virtual Item::~Item () [inline], [virtual]
Member Function Documentation
bounds()
virtual BoundingBox Item::bounds () const [inline], [virtual]
References get_bounds(), and size().
Referenced by collides().
can_eat()
virtual bool Item::can_eat (std::shared_ptr< Item > item) [inline], [virtual]
References empty(), has_holding_ability(), and log_info.
Referenced by eat().
collides()
virtual bool Item::collides (BoundingBox b) const [inline], [virtual]
References bounds().
eat()
virtual bool Item::eat (std::shared_ptr< Item > item) [inline], [virtual]
References can_eat(), and ITEM.
empty()
virtual bool Item::empty () const [inline], [virtual]
References has_holding_ability(), and held_item.
Referenced by can_eat(), and Bag::model().
has_holding_ability()
virtual bool Item::has_holding_ability () const [inline], [virtual]
Reimplemented in Bag.
Referenced by can_eat(), and empty().
is_collidable()
virtual bool Item::is_collidable () [inline], [virtual]
model()
virtual std::optional< raylib::Model > Item::model () const [inline], [virtual]
Reimplemented in Pill, PillBottle, and Bag.
Referenced by render().
model_scale()
virtual vec3 Item::model_scale () const [inline], [virtual]
Reimplemented in Pill, and PillBottle.
Referenced by render().
raw_bounds()
virtual BoundingBox Item::raw_bounds () const [inline], [virtual]
References get_bounds(), and size().
render()
virtual void Item::render (bool render_held_item = true) const [inline], [virtual]
References held_by, ITEM, model(), model_scale(), position, size(), and ui::color::white.
serialize()
template<typename S >
void Item::serialize (S & s) [inline], [private]
References cleanup, color, held_by, held_item, item_size, position, and raw_position.
size()
virtual vec3 Item::size () const [inline], [virtual]
References item_size.
Referenced by bounds(), raw_bounds(), and render().
snap_position()
vec3 Item::snap_position () const [inline]
References vec::snap().
Referenced by Item().
update_position()
virtual void Item::update_position (const vec3 & p) [inline], [virtual]
Member Data Documentation
cleanup
bool Item::cleanup = false
Referenced by serialize().
color
Color Item::color
Referenced by serialize().
held_by
HeldBy Item::held_by = NONE
Referenced by render(), and serialize().
held_item
std::shared_ptr<Item> Item::held_item
Referenced by empty(), and serialize().
id
int Item::id
item_size
float Item::item_size = TILESIZE / 2
Referenced by serialize(), and size().
position
vec3 Item::position
Referenced by render(), and serialize().
raw_position
vec3 Item::raw_position
Referenced by serialize().
The documentation for this struct was generated from the following file:
src/item.h