ui Namespace Reference
Namespaces
namespace autolayout
namespace color
namespace components
namespace theme
Classes
struct ButtonConfig
struct ButtonListState
struct CheckboxState
struct DropdownConfig
struct DropdownState
struct IUIContextInputManager
struct IUIContextLastFrame
struct IUIContextParentStacking
struct IUIContextRenderTextures
struct IUIContextTheming
struct ScrollViewState
struct SizeExpectation
struct SliderState
struct State
struct StateManager
struct TextfieldState
struct ToggleState
struct UIContext
struct UIState
struct UITheme
struct uuid
struct Widget
Typedefs
typedef std::function< TextfieldValidationDecisionFlag(const std::string &)> TextFieldValidationFn
Enumerations
enum struct TextfieldValidationDecisionFlag { None = 0
, StopNewInput = 1 << 0
, Valid = 1 << 1
, Invalid = 1 << 2
 }
enum SizeMode {
Null
, Pixels
, Text
, Percent
,
Children
 }
enum GrowFlags { None = (1 << 0)
, Row = (1 << 1)
, Column = (1 << 2)
 }
Functions
bool text (const Widget &widget, const std::string &content, theme::Usage color_usage=theme::Usage::Font)
bool button (const Widget &widget, const std::string &content=``)
bool button_list (const Widget &widget, const std::vector< std::string > &options, int *selectedIndex=nullptr, bool *hasFocus=nullptr)
bool dropdown (const Widget &widget, const std::vector< std::string > &options, bool *dropdownState, int *selectedIndex)
bool slider (const Widget &widget, float *value, float mnf, float mxf)
bool operator! (TextfieldValidationDecisionFlag f)
bool validation_test (TextfieldValidationDecisionFlag flag, TextfieldValidationDecisionFlag mask)
bool textfield (const Widget &widget, std::string &content, TextFieldValidationFn validation={})
bool checkbox (const Widget &widget, bool *cbState=nullptr, std::string *label=nullptr)
bool is_hot (const uuid &id)
bool is_active (const uuid &id)
bool is_active_or_hot (const uuid &id)
bool is_active_and_hot (const uuid &id)
void active_if_mouse_inside (const uuid id, const Rectangle &rect)
bool has_kb_focus (const uuid &id)
void try_to_grab_kb (const uuid id)
void draw_if_kb_focus (const uuid &id, std::function< void(void)> cb)
void handle_tabbing (const uuid id)
void _draw_focus_ring (const Widget &widget, theme::Usage usage=theme::Usage::Accent)
UIContext::LastFrame init_widget (const Widget &widget, const char *func)
bool padding (const Widget &widget)
bool div (const Widget &widget)
bool slider (const Widget &widget, bool vertical, float *value, float mnf, float mxf)
bool scroll_view (const Widget &widget, std::function< void()> children, float *startingLocation=nullptr)
UIContext & get ()
std::ostream & operator<< (std::ostream &os, const SizeExpectation &exp)
std::ostream & operator<< (std::ostream &os, const Widget &w)
std::ostream & operator<< (std::ostream &os, const uuid &obj)
Variables
const menu::State STATE = menu::State::UI
static std::shared_ptr< UIContext > _uicontext
UIContext * globalContext
static const UITheme DEFAULT_THEME = UITheme()
static const UITheme GRAYSCALE
static uuid ROOT_ID = MK_UUID(-1, -1)
static uuid FAKE_ID = MK_UUID(-2, -1)
Typedef Documentation
TextFieldValidationFn
typedef std::function<TextfieldValidationDecisionFlag(const std::string&)> ui::TextFieldValidationFn
Enumeration Type Documentation
GrowFlags
enum ui::GrowFlags
Enumerator
None
Row
Column
SizeMode
enum ui::SizeMode
Enumerator
Null
Pixels
Text
Percent
Children
TextfieldValidationDecisionFlag
enum struct ui::TextfieldValidationDecisionFlag [strong]
Enumerator
None
StopNewInput
Valid
Invalid
Function Documentation
_draw_focus_ring()
void ui::_draw_focus_ring (const Widget & widget, theme::Usage usage = theme::Usage::Accent) [inline]
References draw_if_kb_focus(), get(), and ui::Widget::id.
Referenced by button(), slider(), and textfield().
active_if_mouse_inside()
void ui::active_if_mouse_inside (const uuid id, const Rectangle & rect) [inline]
References ui::UIContext::active_id, get(), ui::UIContext::hot_id, is_active(), ui::IUIContextInputManager::is_mouse_inside(), and ROOT_ID.
Referenced by button(), scroll_view(), slider(), and textfield().
button()
bool ui::button (const Widget & widget, const std::string & content = ``)
References _draw_focus_ring(), ui::UIContext::_draw_text(), active_if_mouse_inside(), button(), ui::UIContext::draw_widget_rect(), get(), handle_tabbing(), has_kb_focus(), ui::Widget::id, init_widget(), is_active_and_hot(), ui::UIContext::kb_focus_id, MouseInfo::leftDown, ui::Widget::me, ui::IUIContextInputManager::mouse_info, ui::IUIContextInputManager::pressed(), ui::IUIContextLastFrame::LastFrame::rect, ui::Widget::rect, try_to_grab_kb(), and WidgetPress.
Referenced by SettingsLayer::back_button(), button(), button_list(), checkbox(), NetworkLayer::draw_base_screen(), NetworkLayer::draw_connected_screen(), SettingsLayer::draw_keybindings(), NetworkLayer::draw_username(), dropdown(), and BasePauseLayer::onDraw().
button_list()
bool ui::button_list (const Widget & widget, const std::vector< std::string > & options, int * selectedIndex = nullptr, bool * hasFocus = nullptr)
References button(), button_list(), get(), has_kb_focus(), ui::Widget::id, init_widget(), ui::UIContext::kb_focus_id, ui::UIContext::make_temp_widget(), ui::Widget::me, MK_UUID_LOOP, ui::uuid::ownerLayer, ui::IUIContextParentStacking::pop_parent(), ui::IUIContextParentStacking::push_parent(), ui::ButtonListState::selected, ui::State< T >::set(), ValueDown, ValueUp, and ui::UIContext::widget_init().
Referenced by button_list(), and dropdown().
checkbox()
bool ui::checkbox (const Widget & widget, bool * cbState = nullptr, std::string * label = nullptr)
References button(), ui::State< T >::changed_since, checkbox(), get(), ui::Widget::id, init_widget(), ui::ToggleState::on, and ui::UIContext::widget_init().
Referenced by checkbox(), NetworkLayer::draw_connected_screen(), SettingsLayer::enable_post_processing(), and SettingsLayer::streamer_safe_box().
div()
bool ui::div (const Widget & widget)
References div(), and init_widget().
Referenced by div(), NetworkLayer::draw_base_screen(), NetworkLayer::draw_connected_screen(), SettingsLayer::draw_ui(), NetworkLayer::draw_username(), SettingsLayer::enable_post_processing(), SettingsLayer::master_volume(), SettingsLayer::music_volume(), NetworkLayer::onDraw(), BasePauseLayer::onDraw(), SettingsLayer::resolution_switcher(), and SettingsLayer::streamer_safe_box().
draw_if_kb_focus()
void ui::draw_if_kb_focus (const uuid & id, std::function< void(void)> cb) [inline]
References has_kb_focus().
Referenced by _draw_focus_ring().
dropdown()
bool ui::dropdown (const Widget & widget, const std::vector< std::string > & options, bool * dropdownState, int * selectedIndex)
References button(), button_list(), dropdown(), get(), has_kb_focus(), ui::Widget::id, init_widget(), ui::UIContext::kb_focus_id, ui::UIContext::make_temp_widget(), ui::Widget::me, MK_UUID, ui::ToggleState::on, ui::uuid::ownerLayer, ui::IUIContextParentStacking::pop_parent(), ui::IUIContextParentStacking::push_parent(), ui::State< T >::set(), ui::Widget::size_expected, Size_Px, ui::SizeExpectation::value, ValueDown, ValueUp, and ui::UIContext::widget_init().
Referenced by dropdown(), and SettingsLayer::resolution_switcher().
get()
UIContext & ui::get () [inline]
References ui::UIContext::get().
Referenced by _draw_focus_ring(), active_if_mouse_inside(), button(), button_list(), checkbox(), dropdown(), handle_tabbing(), has_kb_focus(), init_widget(), is_active(), is_hot(), ui::components::mk_but_pad(), ui::components::mk_button(), ui::components::mk_column(), ui::components::mk_icon_button(), ui::components::mk_padding(), ui::components::mk_root(), ui::components::mk_row(), ui::components::mk_text(), ui::components::mk_text_id(), scroll_view(), slider(), text(), textfield(), and try_to_grab_kb().
handle_tabbing()
void ui::handle_tabbing (const uuid id) [inline]
References get(), has_kb_focus(), ui::UIContext::kb_focus_id, ui::UIContext::last_processed, and ROOT_ID.
Referenced by button(), slider(), and textfield().
has_kb_focus()
bool ui::has_kb_focus (const uuid & id) [inline]
References get().
Referenced by button(), button_list(), draw_if_kb_focus(), dropdown(), handle_tabbing(), slider(), textfield(), and try_to_grab_kb().
init_widget()
UIContext::LastFrame ui::init_widget (const Widget & widget, const char * func)
References ui::IUIContextParentStacking::add_child(), get(), ui::IUIContextLastFrame::get_last_frame(), ui::Widget::id, init_widget(), ui::Widget::me, ui::Widget::rect, ui::UIContext::schedule_render_call(), and ui::IUIContextLastFrame::write_last_frame().
Referenced by button(), button_list(), checkbox(), div(), dropdown(), init_widget(), padding(), scroll_view(), slider(), text(), and textfield().
is_active()
bool ui::is_active (const uuid & id) [inline]
References get().
Referenced by active_if_mouse_inside(), is_active_and_hot(), and is_active_or_hot().
is_active_and_hot()
bool ui::is_active_and_hot (const uuid & id) [inline]
References is_active(), and is_hot().
Referenced by button(), and textfield().
is_active_or_hot()
bool ui::is_active_or_hot (const uuid & id) [inline]
References is_active(), and is_hot().
is_hot()
bool ui::is_hot (const uuid & id) [inline]
////// ////// ////// ////// ////// ////// //////
References get().
Referenced by is_active_and_hot(), is_active_or_hot(), and scroll_view().
operator!()
bool ui::operator! (TextfieldValidationDecisionFlag f) [inline]
References None.
operator<<() [1/3]
std::ostream & ui::operator<< (std::ostream & os, const SizeExpectation & exp)
References Children, ui::SizeExpectation::mode, Null, Percent, Pixels, ui::SizeExpectation::strictness, Text, and ui::SizeExpectation::value.
operator<<() [2/3]
std::ostream & ui::operator<< (std::ostream & os, const uuid & obj)
operator<<() [3/3]
std::ostream & ui::operator<< (std::ostream & os, const Widget & w)
References ui::Widget::print().
padding()
bool ui::padding (const Widget & widget)
References init_widget(), and padding().
Referenced by SettingsLayer::back_button(), NetworkLayer::draw_base_screen(), NetworkLayer::draw_connected_screen(), SettingsLayer::draw_root_settings(), SettingsLayer::draw_ui(), SettingsLayer::master_volume(), SettingsLayer::music_volume(), NetworkLayer::onDraw(), BasePauseLayer::onDraw(), padding(), and SettingsLayer::resolution_switcher().
scroll_view()
bool ui::scroll_view (const Widget & widget, std::function< void()> children, float * startingLocation = nullptr)
References active_if_mouse_inside(), ui::IUIContextRenderTextures::draw_texture(), get(), ui::IUIContextRenderTextures::get_new_render_texture(), ui::Widget::id, init_widget(), is_hot(), ui::IUIContextLastFrame::LastFrame::rect, ui::Widget::rect, scroll_view(), ui::IUIContextRenderTextures::turn_off_texture_mode(), ui::IUIContextRenderTextures::turn_on_render_texture(), ui::UIContext::widget_init(), ui::ScrollViewState::yoffset, and ui::IUIContextInputManager::yscrolled.
Referenced by scroll_view().
slider() [1/2]
bool ui::slider (const Widget & widget, bool vertical, float * value, float mnf, float mxf)
References _draw_focus_ring(), ui::UIContext::active_id, active_if_mouse_inside(), ui::State< T >::changed_since, ui::UIContext::draw_widget(), ui::UIContext::draw_widget_rect(), get(), ui::UIContext::get_widget_state(), handle_tabbing(), has_kb_focus(), ui::Widget::id, init_widget(), ui::IUIContextInputManager::is_held_down(), ui::UIContext::kb_focus_id, ui::Widget::me, ui::IUIContextInputManager::mouse_info, MouseInfo::pos, ui::IUIContextLastFrame::LastFrame::rect, ui::Widget::rect, slider(), try_to_grab_kb(), ui::State< T >::value, ui::SliderState::value, ValueLeft, ValueRight, and ui::UIContext::widget_init().
slider() [2/2]
bool ui::slider (const Widget & widget, float * value, float mnf, float mxf)
Referenced by SettingsLayer::master_volume(), SettingsLayer::music_volume(), and slider().
text()
bool ui::text (const Widget & widget, const std::string & content, theme::Usage color_usage = theme::Usage::Font)
References get(), init_widget(), ui::Widget::me, ui::UIContext::schedule_draw_text(), and text().
Referenced by NetworkLayer::draw_connected_screen(), NetworkLayer::draw_ip_input_screen(), NetworkLayer::draw_username(), NetworkLayer::draw_username_picker(), SettingsLayer::enable_post_processing(), SettingsLayer::master_volume(), SettingsLayer::music_volume(), SettingsLayer::resolution_switcher(), SettingsLayer::streamer_safe_box(), and text().
textfield()
bool ui::textfield (const Widget & widget, std::string & content, TextFieldValidationFn validation = {})
References _draw_focus_ring(), ui::UIContext::_draw_text(), active_if_mouse_inside(), ui::TextfieldState::buffer, ui::State< T >::changed_since, ui::UIContext::draw_widget(), get(), ext::get_clipboard_text(), ui::UIContext::get_widget_state(), handle_tabbing(), has_kb_focus(), ui::Widget::id, init_widget(), is_active_and_hot(), ui::UIContext::kb_focus_id, ui::Widget::me, ui::IUIContextLastFrame::LastFrame::rect, ui::Widget::rect, textfield(), try_to_grab_kb(), validation_test(), ui::UIContext::widget_init(), WidgetBackspace, WidgetCtrl, and WidgetPaste.
Referenced by NetworkLayer::draw_ip_input_screen(), NetworkLayer::draw_username_picker(), and textfield().
try_to_grab_kb()
void ui::try_to_grab_kb (const uuid id) [inline]
References get(), has_kb_focus(), ui::UIContext::kb_focus_id, and ROOT_ID.
Referenced by button(), slider(), and textfield().
validation_test()
bool ui::validation_test (TextfieldValidationDecisionFlag flag, TextfieldValidationDecisionFlag mask) [inline]
Referenced by textfield().
Variable Documentation
_uicontext
std::shared_ptr<UIContext> ui::_uicontext [static]
Referenced by ui::UIContext::get().
DEFAULT_THEME
const UITheme ui::DEFAULT_THEME = UITheme() [static]
Referenced by ui::IUIContextTheming::active_theme(), ui::IUIContextTheming::init(), and ToastLayer::onDraw().
FAKE_ID
uuid ui::FAKE_ID = MK_UUID(-2, -1) [static]
Referenced by ui::UIContext::cleanup().
globalContext
UIContext* ui::globalContext
Referenced by ui::UIContext::begin(), ui::UIContext::cleanup(), and ui::UIContext::get().
GRAYSCALE
const UITheme ui::GRAYSCALE [static]
Initial value:
=
    UITheme(color::white, color::grey, color::grey, color::black,
            color::cool_grey, color::off_white,
            
            color::off_white)
ROOT_ID
uuid ui::ROOT_ID = MK_UUID(-1, -1) [static]
Referenced by active_if_mouse_inside(), SettingsLayer::back_button(), ui::UIContext::begin(), ui::UIContext::cleanup(), ui::Widget::default_id(), NetworkLayer::draw_base_screen(), NetworkLayer::draw_connected_screen(), NetworkLayer::draw_ip_input_screen(), SettingsLayer::draw_keybindings(), NetworkLayer::draw_username(), NetworkLayer::draw_username_picker(), SettingsLayer::enable_post_processing(), handle_tabbing(), ui::UIContext::init(), SettingsLayer::master_volume(), SettingsLayer::music_volume(), BasePauseLayer::onDraw(), ui::UIContext::reset_tabbing_if_not_visible(), SettingsLayer::streamer_safe_box(), and try_to_grab_kb().
STATE
const menu::State ui::STATE = menu::State::UI
Referenced by ui::IUIContextInputManager::is_held_down(), ui::IUIContextInputManager::pressed(), ui::IUIContextInputManager::pressedButtonWithoutEat(), ui::IUIContextInputManager::pressedWithoutEat(), ui::IUIContextInputManager::process_gamepad_axis_event(), ui::IUIContextInputManager::process_gamepad_button_event(), and ui::IUIContextInputManager::process_keyevent().