AboutLayer Struct Reference
#include <aboutlayer.h>
Public Member Functions
AboutLayer ()
virtual ~AboutLayer ()
virtual void onEvent (Event &event) override
bool onKeyPressed (KeyPressedEvent &event)
void draw_ui (float dt)
virtual void onUpdate (float) override
virtual void onDraw (float dt) override
Public Member Functions inherited from Layer
Layer (const std::string &n=`layer`)
virtual ~Layer ()
virtual void onAttach ()
virtual void onDetach ()
virtual void onUpdate (float elapsed)=0
virtual void onDraw (float elapsed)=0
virtual void onEvent (Event &)=0
const std::string & getname () const
Public Attributes
std::shared_ptr< ui::UIContext > ui_context
const std::string about_info
Public Attributes inherited from Layer
int id
std::string name
Constructor & Destructor Documentation
AboutLayer()
AboutLayer::AboutLayer () [inline]
References ui_context.
 AboutLayer()
virtual AboutLayer::~AboutLayer () [inline], [virtual]
Member Function Documentation
draw_ui()
void AboutLayer::draw_ui (float dt) [inline]
References about_info, ui::components::mk_button(), ui::components::mk_padding(), ui::components::mk_root(), MK_UUID, Size_FullH, Size_Pct, Size_Px, and ui_context.
Referenced by onDraw().
onDraw()
virtual void AboutLayer::onDraw (float dt) [inline], [override], [virtual]
Implements Layer.
References menu::About, ext::clear_background(), draw_ui(), and ui_context.
onEvent()
virtual void AboutLayer::onEvent (Event & event) [inline], [override], [virtual]
Implements Layer.
References EventDispatcher::dispatch(), and onKeyPressed().
onKeyPressed()
bool AboutLayer::onKeyPressed (KeyPressedEvent & event) [inline]
References menu::About, KeyEvent::keycode, and ui_context.
Referenced by onEvent().
onUpdate()
virtual void AboutLayer::onUpdate (float) [inline], [override], [virtual]
Implements Layer.
References menu::About.
Member Data Documentation
about_info
const std::string AboutLayer::about_info
Initial value:
= R"(
A game by:
    Gabe
    Brett
    Alice)"
Referenced by draw_ui().
ui_context
std::shared_ptr<ui::UIContext> AboutLayer::ui_context
Referenced by AboutLayer(), draw_ui(), onDraw(), and onKeyPressed().
The documentation for this struct was generated from the following file:
src/aboutlayer.h