Player Struct Reference
#include <player.h>
Public Member Functions
Player ()
Player (vec3 p, Color face_color_in, Color base_color_in)
Player (vec2 p, Color face_color_in, Color base_color_in)
Player (vec2 location)
virtual void render_normal () const override
virtual void render_debug_mode () const override
virtual bool is_collidable () override
virtual vec3 update_xaxis_position (float dt) override
virtual vec3 update_zaxis_position (float dt) override
virtual void always_update (float dt) override
virtual vec3 get_position_after_input (UserInputs inpts)
void rotate_furniture ()
void work_furniture (float frame_dt)
void handle_in_game_grab_or_drop ()
void handle_in_planning_grab_or_drop ()
virtual void grab_or_drop ()
Public Member Functions inherited from BasePlayer
BasePlayer (vec3 p, Color face_color_in, Color base_color_in)
BasePlayer (vec2 p, Color face_color_in, Color base_color_in)
BasePlayer ()
BasePlayer (vec2 location)
virtual float base_speed () override
virtual vec3 update_xaxis_position (float dt) override=0
virtual vec3 update_zaxis_position (float dt) override=0
void highlight_facing_furniture ()
virtual void planning_update (float dt) override
Public Member Functions inherited from Person
Person (vec3 p, Color face_color_in, Color base_color_in)
Person (vec2 p, Color face_color_in, Color base_color_in)
Person (vec3 p, Color c)
Person (vec2 p, Color c)
virtual vec3 update_xaxis_position (float dt)=0
virtual vec3 update_zaxis_position (float dt)=0
virtual float base_speed ()
virtual vec3 size () const override
void select_next_character_model ()
virtual std::optional< ModelInfo > model () const override
void handle_collision (int facedir_x, vec3 new_pos_x, int facedir_z, vec3 new_pos_z)
std::tuple< int, int > get_face_direction (vec3 new_pos_x, vec3 new_pos_z)
void update_facing_direction (int facedir_x, int facedir_z)
virtual void always_update (float dt) override
Public Member Functions inherited from Entity
FrontFaceDirection offsetFaceDirection (FrontFaceDirection startingDirection, float offset) const
Entity (vec3 p, Color face_color_in, Color base_color_in)
Entity (vec2 p, Color face_color_in, Color base_color_in)
Entity (vec3 p, Color c)
Entity (vec2 p, Color c)
virtual ~Entity ()
void update_name (const std::string &new_name)
virtual bool can_take_item_from () const
virtual bool collides (BoundingBox b) const
virtual BoundingBox bounds () const
virtual void update_position (const vec3 &p)
void rotate_facing_clockwise ()
virtual vec2 tile_infront (int distance)
virtual bool add_to_navmesh ()
virtual bool is_collidable ()
virtual void on_pickup ()
virtual void on_drop (vec3 location)
virtual void render () const final
virtual void update (float dt) final
Public Attributes
const menu::State state = menu::State::Game
std::string username
std::vector< UserInput > inputs
bool is_ghost_player = false
Public Attributes inherited from BasePlayer
float player_reach = 1.25f
std::shared_ptr< Furniture > held_furniture
Public Attributes inherited from Entity
const std::map< FrontFaceDirection, float > FrontFaceDirectionMap
const std::map< int, FrontFaceDirection > DirectionToFrontFaceMap
int id
vec3 raw_position
vec3 prev_position
vec3 position
vec3 pushed_force {0.0, 0.0, 0.0}
Color face_color
Color base_color
bool cleanup = false
bool is_highlighted = false
bool is_held = false
FrontFaceDirection face_direction = FrontFaceDirection::FORWARD
std::shared_ptr< Item > held_item = nullptr
int name_length = 1
std::string name = ``
Additional Inherited Members
Public Types inherited from Entity
enum FrontFaceDirection { FORWARD = 0x1
, RIGHT = 0x2
, BACK = 0x4
, LEFT = 0x8
 }
Static Public Member Functions inherited from Entity
static vec2 tile_infront_given_pos (vec2 tile, int distance, FrontFaceDirection direction)
Protected Member Functions inherited from Person
Person ()
Protected Member Functions inherited from Entity
Entity ()
virtual vec3 size () const
virtual BoundingBox raw_bounds () const
virtual void render_debug_mode () const
virtual void render_highlighted () const
virtual void render_normal () const
virtual void render_floating_name () const
virtual std::optional< ModelInfo > model () const
vec3 snap_position () const
virtual void update_held_item_position ()
virtual vec2 get_heading ()
virtual void turn_to_face_entity (Entity *target)
virtual void always_update (float)
virtual void planning_update (float)
virtual void in_round_update (float)
virtual bool is_snappable ()
virtual bool can_place_item_into (std::shared_ptr< Item >=nullptr)
Constructor & Destructor Documentation
Player() [1/4]
Player::Player () [inline]
Player() [2/4]
Player::Player (vec3 p, Color face_color_in, Color base_color_in) [inline]
Player() [3/4]
Player::Player (vec2 p, Color face_color_in, Color base_color_in) [inline]
Player() [4/4]
Player::Player (vec2 location) [inline]
Member Function Documentation
always_update()
virtual void Player::always_update (float dt) [inline], [override], [virtual]
Reimplemented from Person.
References Entity::always_update(), inputs, and state.
get_position_after_input()
virtual vec3 Player::get_position_after_input (UserInputs inpts) [inline], [virtual]
References BasePlayer::base_speed(), Person::get_face_direction(), grab_or_drop(), Person::handle_collision(), Entity::position, Entity::raw_position, rotate_furniture(), state, Person::update_facing_direction(), and work_furniture().
grab_or_drop()
virtual void Player::grab_or_drop () [inline], [virtual]
References handle_in_game_grab_or_drop(), handle_in_planning_grab_or_drop(), game::Planning, and GameState::s_in_round().
Referenced by get_position_after_input().
handle_in_game_grab_or_drop()
void Player::handle_in_game_grab_or_drop () [inline]
References Entity::face_direction, Item::FURNITURE, Entity::held_item, Item::PLAYER, BasePlayer::player_reach, Entity::position, vec::snap(), TILESIZE, and vec::to2().
Referenced by grab_or_drop().
handle_in_planning_grab_or_drop()
void Player::handle_in_planning_grab_or_drop () [inline]
References Entity::face_direction, BasePlayer::held_furniture, BasePlayer::player_reach, Entity::position, Entity::tile_infront(), vec::to2(), and vec::to3().
Referenced by grab_or_drop().
is_collidable()
virtual bool Player::is_collidable () [inline], [override], [virtual]
Reimplemented from Entity.
References is_ghost_player.
render_debug_mode()
virtual void Player::render_debug_mode () const [inline], [override], [virtual]
Reimplemented from Entity.
References is_ghost_player, and Entity::render_normal().
render_normal()
virtual void Player::render_normal () const [inline], [override], [virtual]
Reimplemented from Entity.
References is_ghost_player, and Entity::render_normal().
rotate_furniture()
void Player::rotate_furniture () [inline]
References game::Planning, BasePlayer::player_reach, Entity::position, and vec::to2().
Referenced by get_position_after_input().
update_xaxis_position()
virtual vec3 Player::update_xaxis_position (float dt) [inline], [override], [virtual]
Implements BasePlayer.
References inputs, Entity::raw_position, and state.
update_zaxis_position()
virtual vec3 Player::update_zaxis_position (float dt) [inline], [override], [virtual]
Implements BasePlayer.
References inputs, Entity::raw_position, and state.
work_furniture()
void Player::work_furniture (float frame_dt) [inline]
References game::Planning, BasePlayer::player_reach, Entity::position, and vec::to2().
Referenced by get_position_after_input().
Member Data Documentation
inputs
std::vector<UserInput> Player::inputs
Referenced by always_update(), update_xaxis_position(), and update_zaxis_position().
is_ghost_player
bool Player::is_ghost_player = false
Referenced by is_collidable(), render_debug_mode(), and render_normal().
state
const menu::State Player::state = menu::State::Game
Referenced by always_update(), get_position_after_input(), update_xaxis_position(), and update_zaxis_position().
username
std::string Player::username
The documentation for this struct was generated from the following file:
src/player.h